/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { compactMap } from "../lib/primitives.js";
import { pathToFunc } from "../lib/url.js";
import { JwksOpServerList } from "../models/jwksop.js";
import { APIPromise } from "../types/async.js";
/**
 * JSON Web Key Set
 *
 * @remarks
 * JSON Web Key Set Endpoint (RFC 7517).
 * <br><br>
 * Returns the public keys used to verify JWT signatures for ID tokens
 * and access tokens.
 * <br><br>
 * <b>Use Cases:</b><br>
 * - Verifying ID token signatures<br>
 * - Verifying access token signatures (if JWT-based)
 * <br><br>
 * <b>Note:</b><br>
 * - For HS256 (symmetric) signing, this returns empty keys<br>
 * - For RS256 (asymmetric) signing, returns public RSA keys<br>
 * - Keys should be cached with appropriate TTL
 */
export function openIDConnectJwks(client$, options) {
    return new APIPromise($do(client$, options));
}
async function $do(client$, options) {
    const baseURL$ = options?.serverURL
        || pathToFunc(JwksOpServerList[0], { charEncoding: "percent" })();
    const path$ = pathToFunc("/.well-known/jwks.json")();
    const headers$ = new Headers(compactMap({
        Accept: "application/json",
    }));
    const context = {
        options: client$._options,
        baseURL: baseURL$ ?? "",
        operationID: "jwks",
        oAuth2Scopes: null,
        resolvedSecurity: null,
        securitySource: null,
        retryConfig: options?.retries
            || client$._options.retryConfig
            || { strategy: "none" },
        retryCodes: options?.retryCodes || [
            "429",
            "500",
            "502",
            "503",
            "504",
        ],
    };
    const requestRes = client$._createRequest(context, {
        method: "GET",
        baseURL: baseURL$,
        path: path$,
        headers: headers$,
        userAgent: client$._options.userAgent,
        timeoutMs: options?.timeoutMs || client$._options.timeoutMs
            || -1,
    }, options);
    if (!requestRes.ok) {
        return [requestRes, { status: "invalid" }];
    }
    const req$ = requestRes.value;
    const doResult = await client$._do(req$, {
        context,
        errorCodes: [],
        retryConfig: context.retryConfig,
        retryCodes: context.retryCodes,
    });
    if (!doResult.ok) {
        return [doResult, { status: "request-error", request: req$ }];
    }
    return [doResult, {
            status: "complete",
            "request": req$,
            response: doResult.value,
        }];
}
//# sourceMappingURL=openIDConnectJwks.js.map