/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { encodeJSON } from "../lib/encodings.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { CreateTeamRequest$zodSchema, } from "../models/createteamop.js";
import { APIPromise } from "../types/async.js";
/**
 * Create a team
 *
 * @remarks
 * Create a new team within the organization for project collaboration and resource sharing.<br><br>
 * <b>Overview:</b><br>
 * Teams are collaborative units that group users together for specific projects, departments, or initiatives. Teams have their own resources, permissions, and member hierarchies.<br><br>
 * <b>Team Structure:</b><br>
 * <ul>
 * <li><b>Owner:</b> Creator of the team, full administrative control</li>
 * <li><b>Admins:</b> Can manage members and settings</li>
 * <li><b>Members:</b> Standard access to team resources</li>
 * <li><b>Viewers:</b> Read-only access</li>
 * </ul>
 * <b>What Gets Created:</b><br>
 * <ul>
 * <li>Team entity with unique identifier</li>
 * <li>Owner role automatically assigned to creator</li>
 * <li>Team workspace for shared resources</li>
 * <li>Default permission settings</li>
 * </ul>
 * <b>Initial Members:</b><br>
 * You can optionally add initial members with their roles during creation using the <code>userRoles</code> array.<br><br>
 * <b>Validation:</b><br>
 * <ul>
 * <li>Team name is required and must be unique in the org</li>
 * <li>Name: 1-100 characters</li>
 * <li>Description: Optional, max 500 characters</li>
 * </ul>
 */
export function teamsCreateTeam(client$, request, options) {
    return new APIPromise($do(client$, request, options));
}
async function $do(client$, request, options) {
    const parsed$ = safeParse(request, (value$) => CreateTeamRequest$zodSchema.parse(value$), "Input validation failed");
    if (!parsed$.ok) {
        return [parsed$, { status: "invalid" }];
    }
    const payload$ = parsed$.value;
    const body$ = encodeJSON("body", payload$, { explode: true });
    const path$ = pathToFunc("/teams")();
    const headers$ = new Headers(compactMap({
        "Content-Type": "application/json",
        Accept: "application/json",
    }));
    const securityInput = await extractSecurity(client$._options.security);
    const requestSecurity = resolveGlobalSecurity(securityInput);
    const context = {
        options: client$._options,
        baseURL: options?.serverURL ?? client$._baseURL ?? "",
        operationID: "createTeam",
        oAuth2Scopes: null,
        resolvedSecurity: requestSecurity,
        securitySource: client$._options.security,
        retryConfig: options?.retries
            || client$._options.retryConfig
            || { strategy: "none" },
        retryCodes: options?.retryCodes || [
            "429",
            "500",
            "502",
            "503",
            "504",
        ],
    };
    const requestRes = client$._createRequest(context, {
        security: requestSecurity,
        method: "POST",
        baseURL: options?.serverURL,
        path: path$,
        headers: headers$,
        body: body$,
        userAgent: client$._options.userAgent,
        timeoutMs: options?.timeoutMs || client$._options.timeoutMs
            || -1,
    }, options);
    if (!requestRes.ok) {
        return [requestRes, { status: "invalid" }];
    }
    const req$ = requestRes.value;
    const doResult = await client$._do(req$, {
        context,
        errorCodes: [],
        retryConfig: context.retryConfig,
        retryCodes: context.retryCodes,
    });
    if (!doResult.ok) {
        return [doResult, { status: "request-error", request: req$ }];
    }
    return [doResult, {
            status: "complete",
            "request": req$,
            response: doResult.value,
        }];
}
//# sourceMappingURL=teamsCreateTeam.js.map