/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGetPermissions } from "../../funcs/agentsGetPermissions.js";
import { GetAgentPermissionsRequest$zodSchema } from "../../models/getagentpermissionsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAgentPermissionsRequest$zodSchema,
};

export const tool$agentsGetPermissions: ToolDefinition<typeof args> = {
  name: "agents-get-permissions",
  description: `Get agent permissions

Get the current permission configuration for an agent.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsGetPermissions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
