/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsDeleteAgent } from "../../funcs/agentsDeleteAgent.js";
import { DeleteAgentRequest$zodSchema } from "../../models/deleteagentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteAgentRequest$zodSchema,
};

export const tool$agentsDeleteAgent: ToolDefinition<typeof args> = {
  name: "agents-delete-agent",
  description: `Delete agent

Soft-delete an agent (tombstone) in the graph database.

**Overview:**
The Python query service marks the agent instance deleted inside a transaction.
List and search endpoints exclude tombstoned agents. Toolsets, tools, and
knowledge linked to the agent are not removed by this call.

**Permissions:**
Only the agent owner may delete (\`can_delete\` on the permission check).

**Warning:**
All conversations with this agent will become inaccessible.

**Observed gateway behavior (localhost integration tests):**
Unknown \`agentKey\`, deleting an already-deleted agent, and \`GET /agents/{agentKey}\`
after delete currently return **HTTP 500** with an \`ErrorResponse\` body (message
often mentions the agent or "not found"), not 404. The Python backend raises 404
for not-found when called directly; the Node proxy may surface 500 instead.
`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsDeleteAgent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
