/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsUpdateAgentConversationMessageFeedback } from "../../funcs/agentsUpdateAgentConversationMessageFeedback.js";
import { UpdateAgentConversationMessageFeedbackRequest$zodSchema } from "../../models/updateagentconversationmessagefeedbackop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateAgentConversationMessageFeedbackRequest$zodSchema,
};

export const tool$agentsUpdateAgentConversationMessageFeedback: ToolDefinition<
  typeof args
> = {
  name: "agents-update-agent-conversation-message-feedback",
  description: `Submit feedback for an agent message

Append structured feedback to a bot-response message in an agent
conversation. Uses the same request body shape as
\`updateMessageFeedback\` (helpfulness, categories, comments). Feedback
can only be submitted on \`bot_response\` messages.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsUpdateAgentConversationMessageFeedback(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
