/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsListAgentConversations } from "../../funcs/agentsListAgentConversations.js";
import { ListAgentConversationsRequest$zodSchema } from "../../models/listagentconversationsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAgentConversationsRequest$zodSchema,
};

export const tool$agentsListAgentConversations: ToolDefinition<typeof args> = {
  name: "agents-list-agent-conversations",
  description: `List agent conversations

Paginated list of conversations for the agent (owned and shared-with-me),
excluding archived threads.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsListAgentConversations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
