/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTemplatesGetAgentTemplate } from "../../funcs/agentTemplatesGetAgentTemplate.js";
import { GetAgentTemplateRequest$zodSchema } from "../../models/getagenttemplateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAgentTemplateRequest$zodSchema,
};

export const tool$agentTemplatesGetAgentTemplate: ToolDefinition<typeof args> =
  {
    name: "agent-templates-get-agent-template",
    description: `Get agent template

Retrieve a specific agent template by ID.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await agentTemplatesGetAgentTemplate(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
