/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsDeleteAgentConversationChatAttachment } from "../../funcs/agentsDeleteAgentConversationChatAttachment.js";
import { DeleteAgentConversationChatAttachmentRequest$zodSchema } from "../../models/deleteagentconversationchatattachmentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteAgentConversationChatAttachmentRequest$zodSchema,
};

export const tool$agentsDeleteAgentConversationChatAttachment: ToolDefinition<
  typeof args
> = {
  name: "agents-delete-agent-conversation-chat-attachment",
  description: `Delete an agent chat attachment

Deletes a previously uploaded attachment by proxying \`DELETE\` to the query service
(\`/api/v1/chat/attachments/{recordId}\`). The Node handler always ends the response **without
a JSON body** on success (empty body); the **status code** is the upstream status, or **204**
if none is returned.

On validation failure in the gateway (invalid / blank path params), the response is **400**
with a small JSON error object. Same fire-and-forget semantics as
\`DELETE /conversations/attachments/{recordId}\` on the client.
`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsDeleteAgentConversationChatAttachment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
