/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aiModelsProvidersGetByType } from "../../funcs/aiModelsProvidersGetByType.js";
import { GetModelsByTypeRequest$zodSchema } from "../../models/getmodelsbytypeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetModelsByTypeRequest$zodSchema,
};

export const tool$aiModelsProvidersGetByType: ToolDefinition<typeof args> = {
  name: "ai-models-providers-get-by-type",
  description: `Get models by type

Get all configured models of a specific type.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await aiModelsProvidersGetByType(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
