/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationConfigurationConfigureSso } from "../../funcs/authenticationConfigurationConfigureSso.js";
import { SSOAuthConfig$zodSchema } from "../../models/ssoauthconfig.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SSOAuthConfig$zodSchema,
};

export const tool$authenticationConfigurationConfigureSso: ToolDefinition<
  typeof args
> = {
  name: "authentication-configuration-configure-sso",
  description: `Configure SAML SSO authentication

Set up SAML 2.0 Single Sign-On with your identity provider (Okta, OneLogin, etc.).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await authenticationConfigurationConfigureSso(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
