/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configurationManagerGetSlackBotConfigs } from "../../funcs/configurationManagerGetSlackBotConfigs.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$configurationManagerGetSlackBotConfigs: ToolDefinition = {
  name: "configuration-manager-get-slack-bot-configs",
  description: `Get Slack bot configurations

Retrieve all Slack bot configurations for the organization.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await configurationManagerGetSlackBotConfigs(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
