/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configurationManagerGetSharePointCredentials } from "../../funcs/configurationManagerGetSharePointCredentials.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$configurationManagerGetSharePointCredentials: ToolDefinition =
  {
    name: "configuration-manager-get-share-point-credentials",
    description: `Get SharePoint credentials

<b>⚠️ Deprecated:</b> This endpoint is deprecated and will be removed in a future release.<br><br>
Retrieve SharePoint connector credentials.
`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    tool: async (client, ctx) => {
      const [result] = await configurationManagerGetSharePointCredentials(
        client,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
