/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorRegistryGetConnectorSchema } from "../../funcs/connectorRegistryGetConnectorSchema.js";
import { GetConnectorSchemaRequest$zodSchema } from "../../models/getconnectorschemaop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetConnectorSchemaRequest$zodSchema,
};

export const tool$connectorRegistryGetConnectorSchema: ToolDefinition<
  typeof args
> = {
  name: "connector-registry-get-connector-schema",
  description: `Get connector configuration schema

Get the configuration schema for a specific connector type.<br><br>
<b>Overview:</b><br>
Returns JSON Schema definitions for authentication, sync settings, and
filter options. Use this to dynamically build configuration forms.<br><br>
<b>Schema Sections:</b><br>
<ul>
<li><b>authSchema:</b> Fields for authentication (credentials, tokens)</li>
<li><b>syncSchema:</b> Sync settings (schedule, incremental options)</li>
<li><b>filterSchema:</b> Filter field definitions</li>
</ul>
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await connectorRegistryGetConnectorSchema(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
