/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorInstancesListActiveAgents } from "../../funcs/connectorInstancesListActiveAgents.js";
import { ListActiveAgentConnectorsRequest$zodSchema } from "../../models/listactiveagentconnectorsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListActiveAgentConnectorsRequest$zodSchema.optional(),
};

export const tool$connectorInstancesListActiveAgents: ToolDefinition<
  typeof args
> = {
  name: "connector-instances-list-active-agents",
  description: `List active agent connectors

Get connector instances enabled for AI agent integration.<br><br>
<b>Overview:</b><br>
Returns connectors where <code>agentEnabled: true</code>.
These are available to AI agents for querying and actions.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await connectorInstancesListActiveAgents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
