/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorOAuthGetTokenFromCode } from "../../funcs/connectorOAuthGetTokenFromCode.js";
import { GetTokenFromCodeRequest$zodSchema } from "../../models/gettokenfromcodeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTokenFromCodeRequest$zodSchema,
};

export const tool$connectorOAuthGetTokenFromCode: ToolDefinition<typeof args> =
  {
    name: "connector-O-auth-get-token-from-code",
    description: `Exchange Google authorization code for tokens

<b>⚠️ Deprecated:</b> Legacy Google Workspace token exchange endpoint. Use the generic
OAuth flow via <code>/connectors/{connectorId}/oauth/authorize</code> instead.<br><br>
<b>Overview:</b><br>
Exchanges a Google OAuth authorization code for access and refresh tokens,
stores the credentials, and enables the Google Workspace connector.<br><br>
<b>What Happens:</b><br>
<ol>
<li>Retrieves Google Workspace OAuth config (client ID/secret)</li>
<li>Exchanges the authorization code for tokens via Google's token endpoint</li>
<li>Verifies the ID token</li>
<li>Stores access and refresh tokens in configuration manager</li>
<li>Creates or enables the Google Workspace connector</li>
<li>Publishes an AppEnabledEvent for the sync service</li>
</ol>
<b>Admin Only:</b><br>
Requires organization admin privileges.
`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await connectorOAuthGetTokenFromCode(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
