/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorInstancesUpdateConnectorName } from "../../funcs/connectorInstancesUpdateConnectorName.js";
import { UpdateConnectorNameRequestRequest$zodSchema } from "../../models/updateconnectornameop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateConnectorNameRequestRequest$zodSchema,
};

export const tool$connectorInstancesUpdateConnectorName: ToolDefinition<
  typeof args
> = {
  name: "connector-instances-update-connector-name",
  description: `Update connector instance name

Update the display name of a connector instance.<br><br>
<b>Note:</b> This only updates the display name, not the connector configuration.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await connectorInstancesUpdateConnectorName(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
