/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorOAuthConfigurationSetGoogleWorkspaceConfig } from "../../funcs/connectorOAuthConfigurationSetGoogleWorkspaceConfig.js";
import { GoogleWorkspaceOAuthConfig$zodSchema } from "../../models/googleworkspaceoauthconfig.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GoogleWorkspaceOAuthConfig$zodSchema,
};

export const tool$connectorOAuthConfigurationSetGoogleWorkspaceConfig:
  ToolDefinition<typeof args> = {
    name: "connector-O-auth-configuration-set-google-9fb",
    description: `Configure Google Workspace OAuth

Set up OAuth credentials for Google Workspace connector. Required for user authentication with Google Drive, Gmail, etc.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await connectorOAuthConfigurationSetGoogleWorkspaceConfig(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
