/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorOAuthGetOAuthAuthorizationUrl } from "../../funcs/connectorOAuthGetOAuthAuthorizationUrl.js";
import { GetOAuthAuthorizationUrlRequest$zodSchema } from "../../models/getoauthauthorizationurlop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetOAuthAuthorizationUrlRequest$zodSchema,
};

export const tool$connectorOAuthGetOAuthAuthorizationUrl: ToolDefinition<
  typeof args
> = {
  name: "connector-O-auth-get-O-auth-authorization-url",
  description: `Get OAuth authorization URL

Generate an OAuth authorization URL to start the OAuth flow.<br><br>
<b>Flow:</b><br>
<ol>
<li>Call this endpoint to get the authorization URL</li>
<li>Redirect user's browser to the URL</li>
<li>User authenticates with the provider</li>
<li>Provider redirects to callback with authorization code</li>
<li>Callback exchanges code for tokens automatically</li>
</ol>
<b>State Parameter:</b><br>
The response includes a <code>state</code> value that encodes the
connector ID. This is validated in the callback.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await connectorOAuthGetOAuthAuthorizationUrl(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
