/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsUpdateConversationTitle } from "../../funcs/conversationsUpdateConversationTitle.js";
import { UpdateConversationTitleRequest$zodSchema } from "../../models/updateconversationtitleop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateConversationTitleRequest$zodSchema,
};

export const tool$conversationsUpdateConversationTitle: ToolDefinition<
  typeof args
> = {
  name: "conversations-update-conversation-title",
  description: `Update conversation title

Update the title of a conversation.

**Overview:**

Conversation titles are auto-generated from the first query by default.
Use this endpoint to set a custom, more descriptive title.

**Title limits:**

- Minimum: 1 character
- Maximum: 200 characters

**Permissions:**

The conversation must exist, belong to the calling user's organization,
be owned by the caller (matched on \`userId\`), and not be soft-deleted.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await conversationsUpdateConversationTitle(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
