/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsGetAllConversations } from "../../funcs/conversationsGetAllConversations.js";
import { GetAllConversationsRequest$zodSchema } from "../../models/getallconversationsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetAllConversationsRequest$zodSchema.optional(),
};

export const tool$conversationsGetAllConversations: ToolDefinition<
  typeof args
> = {
  name: "conversations-get-all-conversations",
  description: `List all conversations

Retrieve paginated conversations for the authenticated user.

**Overview:**

Use the optional \`source\` query parameter to choose which list to return:
\`owned\` — only conversations you own (\`userId\` matches the current user).
\`shared\` — conversations where you have recipient access
(\`isShared\` and your user appears in \`sharedWith\`), without the owner-only branch.
Defaults to \`owned\` when omitted. Each call returns one list; call twice if you need both.

**Filtering:**

- Only non-archived conversations are returned by default
- Use \`/conversations/show/archives\` for archived conversations

**Sorting:**

Conversations are sorted by last activity timestamp (most recent first) by default.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await conversationsGetAllConversations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
