/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsUpdateMessageFeedback } from "../../funcs/conversationsUpdateMessageFeedback.js";
import { UpdateMessageFeedbackRequest$zodSchema } from "../../models/updatemessagefeedbackop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateMessageFeedbackRequest$zodSchema,
};

export const tool$conversationsUpdateMessageFeedback: ToolDefinition<
  typeof args
> = {
  name: "conversations-update-message-feedback",
  description: `Submit feedback on AI response

Append a feedback entry to a bot-response message.

**Overview**

Feedback helps improve AI response quality over time. You can record an
overall helpfulness signal, issue categories, and free-text comments.
Each call appends a new entry to the message; previous entries are
preserved.

**Feedback options**

- \`isHelpful\` — overall thumbs up/down.
- \`categories\` — issue or positive categories from a fixed list.
- \`comments\` — free-text \`positive\` and \`negative\`.

**Restrictions**

Feedback can only be submitted on \`bot_response\` messages — user
queries and system messages are rejected with \`400\`.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await conversationsUpdateMessageFeedback(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
