/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsShare } from "../../funcs/conversationsShare.js";
import { ShareConversationRequest$zodSchema } from "../../models/shareconversationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ShareConversationRequest$zodSchema,
};

export const tool$conversationsShare: ToolDefinition<typeof args> = {
  name: "conversations-share",
  description: `Share conversation with users

Share a conversation with other users in your organization.<br><br>
<b>Overview:</b><br>
Allows the conversation owner to grant access to other users.
Shared users can view the conversation and optionally add messages.<br><br>
<b>Access Levels:</b><br>
<ul>
<li><code>read</code> - Can view conversation and messages (default)</li>
<li><code>write</code> - Can view and add new messages</li>
</ul>
<b>Permissions:</b><br>
Only the conversation initiator (owner) can share. Users must belong
to the same organization.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await conversationsShare(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
