/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsSearchArchivedConversations } from "../../funcs/conversationsSearchArchivedConversations.js";
import { SearchArchivedConversationsRequest$zodSchema } from "../../models/searcharchivedconversationsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SearchArchivedConversationsRequest$zodSchema,
};

export const tool$conversationsSearchArchivedConversations: ToolDefinition<
  typeof args
> = {
  name: "conversations-search-archived-conversations",
  description: `Search archived conversations

Search across all archived conversations (assistant and agent) for the authenticated user.

**Overview:**

Performs a case-insensitive substring match against conversation titles and message content
across both assistant (\`Conversation\`) and agent (\`AgentConversation\`) archived collections.
Results are merged server-side and sorted by \`lastActivityAt\` descending.

**Search parameter:**

The \`search\` query parameter is required, must be a non-empty string, and is capped at
1000 characters. Requests that omit it or exceed the cap return \`400\`.

**Pagination:**

Results are paginated using \`page\` and \`limit\`. The response includes a \`pagination\`
block with total counts and a \`summary\` block that breaks matches down by source.

**Item shape:**

Each item is a conversation list entry (no \`messages\` payload — that field is omitted
for performance) tagged with \`source\`, plus computed \`isOwner\`, \`accessLevel\`,
\`archivedAt\`, and \`archivedBy\`. \`agentKey\` is present only when \`source\` is \`agent\`.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await conversationsSearchArchivedConversations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
