/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentManagementCreateDocumentBufferRaw } from "../../funcs/documentManagementCreateDocumentBufferRaw.js";
import { CreateDocumentBufferRawRequest$zodSchema } from "../../models/createdocumentbufferrawop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateDocumentBufferRawRequest$zodSchema,
};

export const tool$documentManagementCreateDocumentBufferRaw: ToolDefinition<
  typeof args
> = {
  name: "document-management-create-document-buffer-raw",
  description: `Create/update document buffer

<b>⚠️ Deprecated:</b> This endpoint is deprecated and will be removed in a future release.<br><br>
Create or update the binary buffer of a document.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await documentManagementCreateDocumentBufferRaw(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
