/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentManagementRollBackToPreviousVersion } from "../../funcs/documentManagementRollBackToPreviousVersion.js";
import { RollBackToPreviousVersionRequest$zodSchema } from "../../models/rollbacktopreviousversionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RollBackToPreviousVersionRequest$zodSchema,
};

export const tool$documentManagementRollBackToPreviousVersion: ToolDefinition<
  typeof args
> = {
  name: "document-management-roll-back-to-previous-version",
  description: `Roll back to previous version

<b>⚠️ Deprecated:</b> This endpoint is deprecated and will be removed in a future release.<br><br>
Roll back a document to its previous version.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await documentManagementRollBackToPreviousVersion(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
