/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentManagementUploadDirectDocument } from "../../funcs/documentManagementUploadDirectDocument.js";
import { UploadDirectDocumentRequest$zodSchema } from "../../models/uploaddirectdocumentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UploadDirectDocumentRequest$zodSchema,
};

export const tool$documentManagementUploadDirectDocument: ToolDefinition<
  typeof args
> = {
  name: "document-management-upload-direct-document",
  description: `Direct upload document

<b>⚠️ Deprecated:</b> This endpoint is deprecated and will be removed in a future release.<br><br>
Upload a document directly without intermediate processing.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await documentManagementUploadDirectDocument(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
