/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { knowledgeBasesReindexFailedRecords } from "../../funcs/knowledgeBasesReindexFailedRecords.js";
import { ReindexFailedRecordsRequest$zodSchema } from "../../models/reindexfailedrecordsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ReindexFailedRecordsRequest$zodSchema,
};

export const tool$knowledgeBasesReindexFailedRecords: ToolDefinition<
  typeof args
> = {
  name: "knowledge-bases-reindex-failed-records",
  description: `Reindex failed records for connector

Trigger reindexing of records that previously failed to index for a specific connector.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await knowledgeBasesReindexFailedRecords(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
