/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthAppsRegenerateOAuthAppSecret } from "../../funcs/oAuthAppsRegenerateOAuthAppSecret.js";
import { RegenerateOAuthAppSecretRequest$zodSchema } from "../../models/regenerateoauthappsecretop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RegenerateOAuthAppSecretRequest$zodSchema,
};

export const tool$oAuthAppsRegenerateOAuthAppSecret: ToolDefinition<
  typeof args
> = {
  name: "O-auth-apps-regenerate-O-auth-app-secret",
  description: `Regenerate client secret

Generates a fresh client secret for an OAuth app. The previous secret is invalidated immediately — any client still presenting it will fail token exchange at \`POST /oauth2/token\` until updated.

The new secret is returned in this response **only** and cannot be retrieved later. Pair this call with credential propagation to every integration that uses the app. If the rotation was triggered by a suspected leak, also call \`POST /oauth-clients/{appId}/revoke-all-tokens\` to invalidate already-issued access and refresh tokens instead of waiting for their natural expiry.

Creator-only: even org admins cannot rotate secrets for other users' apps.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthAppsRegenerateOAuthAppSecret(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
