/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthConfigurationListToolsetOAuthConfigs } from "../../funcs/oAuthConfigurationListToolsetOAuthConfigs.js";
import { ListToolsetOAuthConfigsRequest$zodSchema } from "../../models/listtoolsetoauthconfigsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListToolsetOAuthConfigsRequest$zodSchema,
};

export const tool$oAuthConfigurationListToolsetOAuthConfigs: ToolDefinition<
  typeof args
> = {
  name: "O-auth-configuration-list-toolset-O-auth-configs",
  description: `List OAuth configs by toolset type`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthConfigurationListToolsetOAuthConfigs(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
