/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthConfigurationUpdateToolsetOAuthConfig } from "../../funcs/oAuthConfigurationUpdateToolsetOAuthConfig.js";
import { UpdateToolsetOAuthConfigRequest$zodSchema } from "../../models/updatetoolsetoauthconfigop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateToolsetOAuthConfigRequest$zodSchema,
};

export const tool$oAuthConfigurationUpdateToolsetOAuthConfig: ToolDefinition<
  typeof args
> = {
  name: "O-auth-configuration-update-toolset-O-auth-config",
  description: `Update OAuth config`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await oAuthConfigurationUpdateToolsetOAuthConfig(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
