/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationAuthConfigSetUpAuthConfig } from "../../funcs/organizationAuthConfigSetUpAuthConfig.js";
import { OrgAuthConfigCreateRequest$zodSchema } from "../../models/orgauthconfigcreaterequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: OrgAuthConfigCreateRequest$zodSchema,
};

export const tool$organizationAuthConfigSetUpAuthConfig: ToolDefinition<
  typeof args
> = {
  name: "organization-auth-config-set-up-auth-config",
  description: `Set up auth configuration

Set up or initialize the organization's authentication configuration.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await organizationAuthConfigSetUpAuthConfig(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
