/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationAuthConfigGetAuthMethods } from "../../funcs/organizationAuthConfigGetAuthMethods.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$organizationAuthConfigGetAuthMethods: ToolDefinition = {
  name: "organization-auth-config-get-auth-methods",
  description: `Get organization authentication methods

Retrieve the configured authentication methods for the organization.

**Response Structure:**

Returns an array of authentication steps, each containing:
- \`order\`: Step number (1-3)
- \`allowedMethods\`: Array of methods allowed for that step

**Example Response:**

\`\`\`json
{
  "authMethods": [
    { "order": 1, "allowedMethods": [{ "type": "password" }, { "type": "google" }] },
    { "order": 2, "allowedMethods": [{ "type": "otp" }] }
  ]
}
\`\`\`

**Admin Access Required:** Only organization admins can view auth configuration.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await organizationAuthConfigGetAuthMethods(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
