/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { platformSettingsGetCustomSystemPrompt } from "../../funcs/platformSettingsGetCustomSystemPrompt.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$platformSettingsGetCustomSystemPrompt: ToolDefinition = {
  name: "platform-settings-get-custom-system-prompt",
  description: `Get custom system prompt

Get custom system prompt.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await platformSettingsGetCustomSystemPrompt(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
