/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { semanticSearchArchive } from "../../funcs/semanticSearchArchive.js";
import { ArchiveSearchRequest$zodSchema } from "../../models/archivesearchop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ArchiveSearchRequest$zodSchema,
};

export const tool$semanticSearchArchive: ToolDefinition<typeof args> = {
  name: "semantic-search-archive",
  description: `Archive search

Archive a search to hide it from the main history list.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await semanticSearchArchive(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
