/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { semanticSearchGetSearchById } from "../../funcs/semanticSearchGetSearchById.js";
import { GetSearchByIdRequest$zodSchema } from "../../models/getsearchbyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSearchByIdRequest$zodSchema,
};

export const tool$semanticSearchGetSearchById: ToolDefinition<typeof args> = {
  name: "semantic-search-get-search-by-id",
  description: `Get search by ID

Retrieve a previously persisted search by its id, scoped to the
caller's org.

The response body is always an **array** containing zero or one
persisted search document. An unknown id returns an empty array
with a \`200\` status — callers should check array length rather
than relying on a \`404\`.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await semanticSearchGetSearchById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
