/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storageConfigurationCreateLocal } from "../../funcs/storageConfigurationCreateLocal.js";
import { CreateLocalStorageConfigRequest$zodSchema } from "../../models/createlocalstorageconfigop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateLocalStorageConfigRequest$zodSchema,
};

export const tool$storageConfigurationCreateLocal: ToolDefinition<typeof args> =
  {
    name: "storage-configuration-create-local",
    description: `Configure Local Storage

Configure local filesystem as the storage backend for file uploads and document storage. Suitable for development or on-premise deployments.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await storageConfigurationCreateLocal(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
