/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teamsListTeams } from "../../funcs/teamsListTeams.js";
import { ListTeamsRequest$zodSchema } from "../../models/listteamsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListTeamsRequest$zodSchema.optional(),
};

export const tool$teamsListTeams: ToolDefinition<typeof args> = {
  name: "teams-list-teams",
  description: `List teams

Retrieve all teams in the organization with optional search and pagination.<br><br>
<b>Overview:</b><br>
This endpoint returns teams the authenticated user can access. Admins see all teams; regular users see teams they're members of.<br><br>
<b>Response Data per Team:</b><br>
<ul>
<li>Team metadata (name, description)</li>
<li>Member count</li>
<li>Owner information</li>
<li>Creation timestamp</li>
</ul>
<b>Search:</b><br>
The search parameter performs fuzzy matching on team names and descriptions.<br><br>
<b>Visibility Rules:</b><br>
<ul>
<li><b>Admins:</b> See all organization teams</li>
<li><b>Users:</b> See only teams they belong to</li>
</ul>
<b>Sorting:</b><br>
Results are sorted by name alphabetically by default.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await teamsListTeams(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
