/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teamsCreateTeam } from "../../funcs/teamsCreateTeam.js";
import { CreateTeamRequest$zodSchema } from "../../models/createteamop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateTeamRequest$zodSchema,
};

export const tool$teamsCreateTeam: ToolDefinition<typeof args> = {
  name: "teams-create-team",
  description: `Create a team

Create a new team within the organization for project collaboration and resource sharing.<br><br>
<b>Overview:</b><br>
Teams are collaborative units that group users together for specific projects, departments, or initiatives. Teams have their own resources, permissions, and member hierarchies.<br><br>
<b>Team Structure:</b><br>
<ul>
<li><b>Owner:</b> Creator of the team, full administrative control</li>
<li><b>Admins:</b> Can manage members and settings</li>
<li><b>Members:</b> Standard access to team resources</li>
<li><b>Viewers:</b> Read-only access</li>
</ul>
<b>What Gets Created:</b><br>
<ul>
<li>Team entity with unique identifier</li>
<li>Owner role automatically assigned to creator</li>
<li>Team workspace for shared resources</li>
<li>Default permission settings</li>
</ul>
<b>Initial Members:</b><br>
You can optionally add initial members with their roles during creation using the <code>userRoles</code> array.<br><br>
<b>Validation:</b><br>
<ul>
<li>Team name is required and must be unique in the org</li>
<li>Name: 1-100 characters</li>
<li>Description: Optional, max 500 characters</li>
</ul>
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await teamsCreateTeam(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
