/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teamsUpdateTeamUsersPermissions } from "../../funcs/teamsUpdateTeamUsersPermissions.js";
import { UpdateTeamUsersPermissionsRequest$zodSchema } from "../../models/updateteamuserspermissionsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateTeamUsersPermissionsRequest$zodSchema,
};

export const tool$teamsUpdateTeamUsersPermissions: ToolDefinition<typeof args> =
  {
    name: "teams-update-team-users-permissions",
    description: `Update team users permissions

<b>⚠️ Deprecated:</b> This endpoint is deprecated and will be removed in a future release.<br><br>
Update permissions for users within a team.
`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await teamsUpdateTeamUsersPermissions(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
