/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsetInstancesGetToolsetInstances } from "../../funcs/toolsetInstancesGetToolsetInstances.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$toolsetInstancesGetToolsetInstances: ToolDefinition = {
  name: "toolset-instances-get-toolset-instances",
  description: `List toolset instances

List all toolset instances configured for the organization.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await toolsetInstancesGetToolsetInstances(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
