/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsetInstancesReauthenticateToolset } from "../../funcs/toolsetInstancesReauthenticateToolset.js";
import { ReauthenticateToolsetRequest$zodSchema } from "../../models/reauthenticatetoolsetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ReauthenticateToolsetRequest$zodSchema,
};

export const tool$toolsetInstancesReauthenticateToolset: ToolDefinition<
  typeof args
> = {
  name: "toolset-instances-reauthenticate-toolset",
  description: `Reauthenticate toolset

Clear toolset OAuth credentials and mark as unauthenticated, requiring re-authentication.<br><br>
Only applicable to OAuth-configured toolsets.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await toolsetInstancesReauthenticateToolset(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
