/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { toolsetInstancesRemoveToolsetCredentials } from "../../funcs/toolsetInstancesRemoveToolsetCredentials.js";
import { RemoveToolsetCredentialsRequest$zodSchema } from "../../models/removetoolsetcredentialsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RemoveToolsetCredentialsRequest$zodSchema,
};

export const tool$toolsetInstancesRemoveToolsetCredentials: ToolDefinition<
  typeof args
> = {
  name: "toolset-instances-remove-toolset-credentials",
  description: `Remove toolset credentials`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await toolsetInstancesRemoveToolsetCredentials(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
