/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userAccountInitAuth } from "../../funcs/userAccountInitAuth.js";
import { InitAuthRequest$zodSchema } from "../../models/initauthrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: InitAuthRequest$zodSchema.optional(),
};

export const tool$userAccountInitAuth: ToolDefinition<typeof args> = {
  name: "user-account-init-auth",
  description: `Initialize authentication session

Start a server-side authentication session and discover which sign-in methods are
configured for the organization. This is the first step in the multi-step login flow.

**Request body (optional)**

- You may omit the body, send an empty JSON object \`{}\`, or send \`{ "email": "..." }\`.
- \`email\` in the body is optional and kept for legacy reasons; omitting it does not prevent
  initialization. The web client typically calls this endpoint without a body and sends
  \`email\` on \`/authenticate\` instead.
- When provided, \`email\` is stored on the session for correlation with subsequent steps.

**Flow:**

1. Call this endpoint (optional JSON body as above).
2. Receive a session token in the \`x-session-token\` response header.
3. Send that token on subsequent \`/authenticate\` requests (\`x-session-token\` header).
4. Use \`allowedMethods\` and \`authProviders\` from the response to render the login UI.

**Session token**

- Returned as header \`x-session-token\`.
- Required for \`/authenticate\` (and related steps) until it expires.

**Multi-factor authentication**

If the organization has MFA, complete multiple authentication steps; each step may
return the next step's allowed methods.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await userAccountInitAuth(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
