/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userAccountAuthenticate } from "../../funcs/userAccountAuthenticate.js";
import { AuthenticateRequestRequest$zodSchema } from "../../models/authenticateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AuthenticateRequestRequest$zodSchema,
};

export const tool$userAccountAuthenticate: ToolDefinition<typeof args> = {
  name: "user-account-authenticate",
  description: `Authenticate user with credentials

Authenticate a user using the specified method and credentials.
Requires a valid session token from \`/initAuth\`.

**Credential Formats by Method:**

- \`password\`: \`{ "credentials": { "password": "your-password" } }\`
- \`otp\`: \`{ "credentials": { "otp": "123456" } }\` (6-digit code, valid for 10 minutes)
- \`google\`: \`{ "credentials": "google-id-token-string" }\`
- \`microsoft\`: \`{ "credentials": { "accessToken": "...", "idToken": "..." } }\`
- \`azureAd\`: \`{ "credentials": { "accessToken": "...", "idToken": "..." } }\`
- \`oauth\`: \`{ "credentials": { "accessToken": "...", "idToken": "..." } }\`
- \`samlSso\`: Handled via redirect flow (use \`/saml/signIn\` instead)

**Multi-Step Response:**

If organization uses MFA, successful authentication returns:
- \`status: "success"\` with \`nextStep\` and \`allowedMethods\` for next step

**Fully Authenticated Response:**

After completing all steps:
- \`message: "Fully authenticated"\` with \`accessToken\` (1hr) and \`refreshToken\` (7d)

**Security:**

- Account locks after 5 consecutive failed attempts
- CAPTCHA may be required if enabled (pass \`cf-turnstile-response\`)
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await userAccountAuthenticate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
