/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGroupsGetGroupStatistics } from "../../funcs/userGroupsGetGroupStatistics.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$userGroupsGetGroupStatistics: ToolDefinition = {
  name: "user-groups-get-group-statistics",
  description: `Get group statistics

Retrieve statistics for all user groups including member counts.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await userGroupsGetGroupStatistics(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
