/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SDKCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool, registerDynamicTools } from "./tools.js";
import { tool$agentsArchiveAgentConversation } from "./tools/agentsArchiveAgentConversation.js";
import { tool$agentsCreateAgent } from "./tools/agentsCreateAgent.js";
import { tool$agentsDeleteAgent } from "./tools/agentsDeleteAgent.js";
import { tool$agentsDeleteAgentConversationById } from "./tools/agentsDeleteAgentConversationById.js";
import { tool$agentsDeleteAgentConversationChatAttachment } from "./tools/agentsDeleteAgentConversationChatAttachment.js";
import { tool$agentsGetAgent } from "./tools/agentsGetAgent.js";
import { tool$agentsGetAgentConversationById } from "./tools/agentsGetAgentConversationById.js";
import { tool$agentsListAgentArchivedConversationsGrouped } from "./tools/agentsListAgentArchivedConversationsGrouped.js";
import { tool$agentsListAgentConversationArchives } from "./tools/agentsListAgentConversationArchives.js";
import { tool$agentsListAgentConversations } from "./tools/agentsListAgentConversations.js";
import { tool$agentsListAgents } from "./tools/agentsListAgents.js";
import { tool$agentsUnarchiveAgentConversation } from "./tools/agentsUnarchiveAgentConversation.js";
import { tool$agentsUpdateAgent } from "./tools/agentsUpdateAgent.js";
import { tool$agentsUpdateAgentConversationMessageFeedback } from "./tools/agentsUpdateAgentConversationMessageFeedback.js";
import { tool$agentsUpdateAgentConversationTitle } from "./tools/agentsUpdateAgentConversationTitle.js";
import { tool$agentsUploadAgentConversationChatAttachments } from "./tools/agentsUploadAgentConversationChatAttachments.js";
import { tool$aiModelsProvidersGetAvailableModelsByType } from "./tools/aiModelsProvidersGetAvailableModelsByType.js";
import { tool$conversationsArchiveConversation } from "./tools/conversationsArchiveConversation.js";
import { tool$conversationsDeleteConversationById } from "./tools/conversationsDeleteConversationById.js";
import { tool$conversationsGetAllConversations } from "./tools/conversationsGetAllConversations.js";
import { tool$conversationsGetArchivedConversations } from "./tools/conversationsGetArchivedConversations.js";
import { tool$conversationsGetConversationById } from "./tools/conversationsGetConversationById.js";
import { tool$conversationsSearchArchivedConversations } from "./tools/conversationsSearchArchivedConversations.js";
import { tool$conversationsUnarchiveConversation } from "./tools/conversationsUnarchiveConversation.js";
import { tool$conversationsUpdateConversationTitle } from "./tools/conversationsUpdateConversationTitle.js";
import { tool$conversationsUpdateMessageFeedback } from "./tools/conversationsUpdateMessageFeedback.js";
import { tool$knowledgeHubGetKnowledgeHubChildNodes } from "./tools/knowledgeHubGetKnowledgeHubChildNodes.js";
import { tool$knowledgeHubGetKnowledgeHubRootNodes } from "./tools/knowledgeHubGetKnowledgeHubRootNodes.js";
import { tool$oAuthAppsActivateOAuthApp } from "./tools/oAuthAppsActivateOAuthApp.js";
import { tool$oAuthAppsCreateOAuthApp } from "./tools/oAuthAppsCreateOAuthApp.js";
import { tool$oAuthAppsDeleteOAuthApp } from "./tools/oAuthAppsDeleteOAuthApp.js";
import { tool$oAuthAppsGetOAuthApp } from "./tools/oAuthAppsGetOAuthApp.js";
import { tool$oAuthAppsListOAuthApps } from "./tools/oAuthAppsListOAuthApps.js";
import { tool$oAuthAppsListOAuthAppTokens } from "./tools/oAuthAppsListOAuthAppTokens.js";
import { tool$oAuthAppsListOAuthScopes } from "./tools/oAuthAppsListOAuthScopes.js";
import { tool$oAuthAppsRegenerateOAuthAppSecret } from "./tools/oAuthAppsRegenerateOAuthAppSecret.js";
import { tool$oAuthAppsRevokeAllOAuthAppTokens } from "./tools/oAuthAppsRevokeAllOAuthAppTokens.js";
import { tool$oAuthAppsSuspendOAuthApp } from "./tools/oAuthAppsSuspendOAuthApp.js";
import { tool$oAuthAppsUpdateOAuthApp } from "./tools/oAuthAppsUpdateOAuthApp.js";
import { tool$oAuthProviderOauthIntrospect } from "./tools/oAuthProviderOauthIntrospect.js";
import { tool$oAuthProviderOauthRevoke } from "./tools/oAuthProviderOauthRevoke.js";
import { tool$oAuthProviderOauthToken } from "./tools/oAuthProviderOauthToken.js";
import { tool$openIDConnectOauthUserInfo } from "./tools/openIDConnectOauthUserInfo.js";
import { tool$organizationAuthConfigGetAuthMethods } from "./tools/organizationAuthConfigGetAuthMethods.js";
import { tool$organizationAuthConfigSetUpAuthConfig } from "./tools/organizationAuthConfigSetUpAuthConfig.js";
import { tool$organizationAuthConfigUpdateAuthMethod } from "./tools/organizationAuthConfigUpdateAuthMethod.js";
import { tool$organizationsGetCurrentOrganization } from "./tools/organizationsGetCurrentOrganization.js";
import { tool$semanticSearchArchiveSearch } from "./tools/semanticSearchArchiveSearch.js";
import { tool$semanticSearchDeleteSearchById } from "./tools/semanticSearchDeleteSearchById.js";
import { tool$semanticSearchDeleteSearchHistory } from "./tools/semanticSearchDeleteSearchHistory.js";
import { tool$semanticSearchGetSearchById } from "./tools/semanticSearchGetSearchById.js";
import { tool$semanticSearchSearch } from "./tools/semanticSearchSearch.js";
import { tool$semanticSearchSearchHistory } from "./tools/semanticSearchSearchHistory.js";
import { tool$semanticSearchUnarchiveSearch } from "./tools/semanticSearchUnarchiveSearch.js";
import { tool$userAccountAuthenticate } from "./tools/userAccountAuthenticate.js";
import { tool$userAccountInitAuth } from "./tools/userAccountInitAuth.js";
import { tool$userAccountResetPassword } from "./tools/userAccountResetPassword.js";
import { tool$webSearchGetWebSearchProviders } from "./tools/webSearchGetWebSearchProviders.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => SDKCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
  instance_url?: SDKOptions["instance_url"] | undefined;
}) {
  const server = new McpServer({
    name: "SDK",
    version: "0.0.1",
  });

  const getClient = deps.getSDK || (() =>
    new SDKCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      instance_url: deps.instance_url,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$oAuthProviderOauthToken);
  tool(tool$oAuthProviderOauthRevoke);
  tool(tool$oAuthProviderOauthIntrospect);
  tool(tool$openIDConnectOauthUserInfo);
  tool(tool$oAuthAppsListOAuthApps);
  tool(tool$oAuthAppsCreateOAuthApp);
  tool(tool$oAuthAppsListOAuthScopes);
  tool(tool$oAuthAppsGetOAuthApp);
  tool(tool$oAuthAppsUpdateOAuthApp);
  tool(tool$oAuthAppsDeleteOAuthApp);
  tool(tool$oAuthAppsRegenerateOAuthAppSecret);
  tool(tool$oAuthAppsSuspendOAuthApp);
  tool(tool$oAuthAppsActivateOAuthApp);
  tool(tool$oAuthAppsListOAuthAppTokens);
  tool(tool$oAuthAppsRevokeAllOAuthAppTokens);
  tool(tool$userAccountInitAuth);
  tool(tool$userAccountAuthenticate);
  tool(tool$userAccountResetPassword);
  tool(tool$organizationAuthConfigGetAuthMethods);
  tool(tool$organizationAuthConfigUpdateAuthMethod);
  tool(tool$organizationAuthConfigSetUpAuthConfig);
  tool(tool$organizationsGetCurrentOrganization);
  tool(tool$knowledgeHubGetKnowledgeHubRootNodes);
  tool(tool$knowledgeHubGetKnowledgeHubChildNodes);
  tool(tool$conversationsGetAllConversations);
  tool(tool$conversationsGetArchivedConversations);
  tool(tool$conversationsSearchArchivedConversations);
  tool(tool$conversationsGetConversationById);
  tool(tool$conversationsDeleteConversationById);
  tool(tool$conversationsUpdateConversationTitle);
  tool(tool$conversationsArchiveConversation);
  tool(tool$conversationsUnarchiveConversation);
  tool(tool$conversationsUpdateMessageFeedback);
  tool(tool$semanticSearchSearch);
  tool(tool$semanticSearchSearchHistory);
  tool(tool$semanticSearchDeleteSearchHistory);
  tool(tool$semanticSearchGetSearchById);
  tool(tool$semanticSearchDeleteSearchById);
  tool(tool$semanticSearchArchiveSearch);
  tool(tool$semanticSearchUnarchiveSearch);
  tool(tool$agentsListAgents);
  tool(tool$agentsCreateAgent);
  tool(tool$agentsGetAgent);
  tool(tool$agentsUpdateAgent);
  tool(tool$agentsDeleteAgent);
  tool(tool$agentsListAgentArchivedConversationsGrouped);
  tool(tool$agentsListAgentConversationArchives);
  tool(tool$agentsUploadAgentConversationChatAttachments);
  tool(tool$agentsDeleteAgentConversationChatAttachment);
  tool(tool$agentsUpdateAgentConversationMessageFeedback);
  tool(tool$agentsArchiveAgentConversation);
  tool(tool$agentsUnarchiveAgentConversation);
  tool(tool$agentsUpdateAgentConversationTitle);
  tool(tool$agentsDeleteAgentConversationById);
  tool(tool$agentsGetAgentConversationById);
  tool(tool$agentsListAgentConversations);
  tool(tool$aiModelsProvidersGetAvailableModelsByType);
  tool(tool$webSearchGetWebSearchProviders);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
