/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { aiModelsProvidersList } from "../../funcs/aiModelsProvidersList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$aiModelsProvidersList: ToolDefinition = {
  name: "ai-models-providers-list",
  description: `Get all AI model providers

List all configured AI model providers with their configurations.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await aiModelsProvidersList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
