/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorInstancesListConfigured } from "../../funcs/connectorInstancesListConfigured.js";
import { ListConfiguredConnectorsRequest$zodSchema } from "../../models/listconfiguredconnectorsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListConfiguredConnectorsRequest$zodSchema.optional(),
};

export const tool$connectorInstancesListConfigured: ToolDefinition<
  typeof args
> = {
  name: "connector-instances-list-configured",
  description: `List configured connector instances

Get all connector instances that have completed configuration.<br><br>
<b>Overview:</b><br>
Returns instances where <code>isConfigured: true</code>.
These have all required settings but may not be active yet.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await connectorInstancesListConfigured(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
