/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorOAuthConfigurationSetAtlassianConfig } from "../../funcs/connectorOAuthConfigurationSetAtlassianConfig.js";
import { AtlassianConfig$zodSchema } from "../../models/atlassianconfig.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AtlassianConfig$zodSchema,
};

export const tool$connectorOAuthConfigurationSetAtlassianConfig: ToolDefinition<
  typeof args
> = {
  name: "connector-O-auth-configuration-set-atlassian-config",
  description: `Configure Atlassian OAuth

Set up OAuth credentials for Atlassian (Confluence/Jira) connector.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await connectorOAuthConfigurationSetAtlassianConfig(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
