/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { conversationsUnshare } from "../../funcs/conversationsUnshare.js";
import { UnshareConversationRequest$zodSchema } from "../../models/unshareconversationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UnshareConversationRequest$zodSchema,
};

export const tool$conversationsUnshare: ToolDefinition<typeof args> = {
  name: "conversations-unshare",
  description: `Revoke conversation access

Remove sharing access from users.<br><br>
<b>Overview:</b><br>
Removes specified users from the conversation's sharedWith list.
Those users will no longer be able to access the conversation.<br><br>
<b>Permissions:</b><br>
Only the conversation owner can revoke access.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await conversationsUnshare(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
