/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentBufferGet } from "../../funcs/documentBufferGet.js";
import { GetDocumentBufferRequest$zodSchema } from "../../models/getdocumentbufferop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetDocumentBufferRequest$zodSchema,
};

export const tool$documentBufferGet: ToolDefinition<typeof args> = {
  name: "document-buffer-get",
  description: `Get document buffer

Retrieve the raw binary content of a document as a buffer. Used for in-memory document processing.<br><br>
<b>Overview:</b><br>
Returns the complete file content as a binary buffer. This is useful for server-side document processing, content analysis, or format conversion.<br><br>
<b>Use Cases:</b><br>
<ul>
<li>Document parsing and text extraction</li>
<li>Format conversion pipelines</li>
<li>Content analysis and indexing</li>
<li>Thumbnail generation</li>
</ul>
<b>Version Support:</b><br>
Specify <code>version</code> to get a specific historical version's content.<br><br>
<b>Memory Considerations:</b><br>
Large files will consume significant memory. For files &gt;100MB, consider using streaming download instead.<br><br>
<b>Response Format:</b><br>
Returns Node.js Buffer object serialized as JSON with type and data array.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await documentBufferGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
