/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { openidConnectUserinfo } from "../../funcs/openidConnectUserinfo.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$openidConnectUserinfo: ToolDefinition = {
  name: "openid-connect-userinfo",
  description: `Get authenticated user information

OpenID Connect UserInfo Endpoint.
<br><br>
Returns claims about the authenticated user. Requires a valid access token
with the \`openid\` scope.
<br><br>
<b>Available Claims:</b><br>
- \`sub\` - Subject identifier (user ID)<br>
- \`name\`, \`given_name\`, \`family_name\` - Name claims (with \`profile\` scope)<br>
- \`email\`, \`email_verified\` - Email claims (with \`email\` scope)
<br><br>
<b>Authentication:</b><br>
Pass the access token as a Bearer token: \`Authorization: Bearer {access_token}\`
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await openidConnectUserinfo(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
