/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publicUrlsGetConnector } from "../../funcs/publicUrlsGetConnector.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$publicUrlsGetConnector: ToolDefinition = {
  name: "public-urls-get-connector",
  description: `Get connector public URL

Get connector public URL.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await publicUrlsGetConnector(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
