/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storageConfigurationCreateS3 } from "../../funcs/storageConfigurationCreateS3.js";
import { CreateS3StorageConfigRequest$zodSchema } from "../../models/creates3storageconfigop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateS3StorageConfigRequest$zodSchema,
};

export const tool$storageConfigurationCreateS3: ToolDefinition<typeof args> = {
  name: "storage-configuration-create-s3",
  description: `Configure AWS S3 Storage

Configure AWS S3 as the storage backend for file uploads and document storage. Requires an S3 bucket and IAM credentials with appropriate permissions.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await storageConfigurationCreateS3(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
