/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teamsGetCreatedByUser } from "../../funcs/teamsGetCreatedByUser.js";
import { GetUserCreatedTeamsRequest$zodSchema } from "../../models/getusercreatedteamsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetUserCreatedTeamsRequest$zodSchema.optional(),
};

export const tool$teamsGetCreatedByUser: ToolDefinition<typeof args> = {
  name: "teams-get-created-by-user",
  description: `Get teams created by current user

Retrieve all teams that were created by the authenticated user.<br><br>
<b>Response Details:</b><br>
<ul>
<li>Only includes teams where user is the original creator</li>
<li>User may or may not still be the owner (ownership can be transferred)</li>
<li>Useful for tracking team creation history</li>
</ul>
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await teamsGetCreatedByUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
