/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { agentsGet } from "../../funcs/agentsGet.js";
import { GetAgentRequest$zodSchema } from "../../models/getagentop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetAgentRequest$zodSchema,
};
export const tool$agentsGet = {
    name: "agents-get",
    description: `Get agent

Retrieve agent details by its unique key.`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await agentsGet(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=agentsGet.js.map