/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { agentsList } from "../../funcs/agentsList.js";
import { formatResult } from "../tools.js";
export const tool$agentsList = {
    name: "agents-list",
    description: `List agents

Retrieve all agents available to the authenticated user.<br><br>
<b>Overview:</b><br>
Returns agents created by the user plus public agents in the organization.
Each agent has unique capabilities defined by its tools and knowledge scope.
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    tool: async (client, ctx) => {
        const [result] = await agentsList(client, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=agentsList.js.map