/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { aiModelsConfigurationGetAIModelsConfig } from "../../funcs/aiModelsConfigurationGetAIModelsConfig.js";
import { formatResult } from "../tools.js";
export const tool$aiModelsConfigurationGetAIModelsConfig = {
    name: "AI-models-configuration-get-AI-models-config",
    description: `Get all AI models configuration

Retrieve all configured AI model providers grouped by type.`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    tool: async (client, ctx) => {
        const [result] = await aiModelsConfigurationGetAIModelsConfig(client, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=aiModelsConfigurationGetAIModelsConfig.js.map