/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { authenticationConfigurationSetOAuthConfig } from "../../funcs/authenticationConfigurationSetOAuthConfig.js";
import { GenericOAuthConfig$zodSchema } from "../../models/genericoauthconfig.js";
import { formatResult } from "../tools.js";
const args = {
    request: GenericOAuthConfig$zodSchema,
};
export const tool$authenticationConfigurationSetOAuthConfig = {
    name: "authentication-configuration-set-O-auth-config",
    description: `Configure generic OAuth provider

Set up a custom OAuth 2.0 authentication provider.`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await authenticationConfigurationSetOAuthConfig(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=authenticationConfigurationSetOAuthConfig.js.map