/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { authenticationConfigurationsSetMicrosoft } from "../../funcs/authenticationConfigurationsSetMicrosoft.js";
import { MicrosoftAuthConfig$zodSchema } from "../../models/microsoftauthconfig.js";
import { formatResult } from "../tools.js";
const args = {
    request: MicrosoftAuthConfig$zodSchema,
};
export const tool$authenticationConfigurationsSetMicrosoft = {
    name: "authentication-configurations-set-microsoft",
    description: `Configure Microsoft authentication

Set up Microsoft account as an authentication provider.`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await authenticationConfigurationsSetMicrosoft(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=authenticationConfigurationsSetMicrosoft.js.map