/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { authenticationConfigurationSetSsoAuthConfig } from "../../funcs/authenticationConfigurationSetSsoAuthConfig.js";
import { SSOAuthConfig$zodSchema } from "../../models/ssoauthconfig.js";
import { formatResult } from "../tools.js";
const args = {
    request: SSOAuthConfig$zodSchema,
};
export const tool$authenticationConfigurationSetSsoAuthConfig = {
    name: "authentication-configuration-set-sso-auth-config",
    description: `Configure SAML SSO authentication

Set up SAML 2.0 Single Sign-On with your identity provider (Okta, OneLogin, etc.).`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await authenticationConfigurationSetSsoAuthConfig(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=authenticationConfigurationSetSsoAuthConfig.js.map