/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { connectorInstancesCreate } from "../../funcs/connectorInstancesCreate.js";
import { CreateConnectorRequest$zodSchema } from "../../models/createconnectorrequest.js";
import { formatResult } from "../tools.js";
const args = {
    request: CreateConnectorRequest$zodSchema,
};
export const tool$connectorInstancesCreate = {
    name: "connector-instances-create",
    description: `Create connector instance

Create a new connector instance from a registry type.<br><br>
<b>Overview:</b><br>
Creates a new connector instance that can then be configured and enabled.
The instance is created in an unconfigured state and needs authentication
and filter setup before it can be activated.<br><br>
<b>Scope Permissions:</b><br>
<ul>
<li><code>team</code> scope requires admin privileges</li>
<li><code>personal</code> scope available to all users</li>
</ul>
<b>Next Steps After Creation:</b><br>
<ol>
<li>Configure authentication via <code>PUT /{id}/config/auth</code></li>
<li>Complete OAuth flow if needed via <code>GET /{id}/oauth/authorize</code></li>
<li>Set up filters via <code>POST /{id}/filters</code></li>
<li>Enable connector via <code>POST /{id}/toggle</code></li>
</ol>
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await connectorInstancesCreate(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=connectorInstancesCreate.js.map