/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { connectorConfigurationUpdateFiltersSync } from "../../funcs/connectorConfigurationUpdateFiltersSync.js";
import { UpdateConnectorFiltersSyncConfigRequest$zodSchema } from "../../models/updateconnectorfilterssyncconfigop.js";
import { formatResult } from "../tools.js";
const args = {
    request: UpdateConnectorFiltersSyncConfigRequest$zodSchema,
};
export const tool$connectorConfigurationUpdateFiltersSync = {
    name: "connector-configuration-update-filters-sync",
    description: `Update filters and sync configuration

Update filter selections and sync settings without touching auth.<br><br>
<b>Use Case:</b><br>
Use this to change what data is synced or adjust sync schedule
without re-authenticating.
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await connectorConfigurationUpdateFiltersSync(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=connectorConfigurationUpdateFiltersSync.js.map