/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { connectorsReindexRecord } from "../../funcs/connectorsReindexRecord.js";
import { ReindexRecordRequest$zodSchema } from "../../models/reindexrecordop.js";
import { formatResult } from "../tools.js";
const args = {
    request: ReindexRecordRequest$zodSchema,
};
export const tool$connectorsReindexRecord = {
    name: "connectors-reindex-record",
    description: `Reindex single record

Trigger reindexing for a specific record.<br><br>
<b>Overview:</b><br>
Reprocesses the record's content to update search indexes and AI embeddings. Useful after content changes or to fix indexing failures.<br><br>
<b>Depth Parameter:</b><br>
Controls processing depth for complex documents (-1 for full depth, 0-100 for limited).
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await connectorsReindexRecord(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=connectorsReindexRecord.js.map