/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { crawlingJobsGetStatus } from "../../funcs/crawlingJobsGetStatus.js";
import { GetCrawlingJobStatusRequest$zodSchema } from "../../models/getcrawlingjobstatusop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetCrawlingJobStatusRequest$zodSchema,
};
export const tool$crawlingJobsGetStatus = {
    name: "crawling-jobs-get-status",
    description: `Get crawling job status

Retrieve the current status of a scheduled crawling job for a specific connector.<br><br>

<b>Overview:</b><br>
Returns detailed information about the most recent crawling job for the specified connector,
including its current state, progress, timing information, and any error details.<br><br>

<b>Job States:</b><br>
<ul>
<li><b>waiting:</b> Job is queued and waiting to be processed</li>
<li><b>active:</b> Job is currently being processed by a worker</li>
<li><b>completed:</b> Job finished successfully</li>
<li><b>failed:</b> Job failed after exhausting retry attempts</li>
<li><b>delayed:</b> Job is scheduled for future execution</li>
<li><b>paused:</b> Job has been manually paused</li>
</ul>

<b>Access Control:</b><br>
Same as scheduling - team connectors require admin, personal connectors require creator.
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await crawlingJobsGetStatus(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=crawlingJobsGetStatus.js.map