/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { doclingServiceDoclingCreateBlocks } from "../../funcs/doclingServiceDoclingCreateBlocks.js";
import { DoclingCreateBlocksRequest$zodSchema } from "../../models/doclingcreateblocksop.js";
import { formatResult } from "../tools.js";
const args = {
    request: DoclingCreateBlocksRequest$zodSchema,
};
export const tool$doclingServiceDoclingCreateBlocks = {
    name: "docling-service-docling-create-blocks",
    description: `[Docling Service] Create blocks from parse result (Phase 2)

⚠️ <b>INTERNAL SERVICE ENDPOINT</b><br><br>

Phase 2 of two-phase PDF processing - create blocks from parse result.<br><br>

<b>Service:</b> Docling Service<br>
<b>Port:</b> 8081<br>
<b>Base URL:</b> <code>http://localhost:8081</code><br><br>

<b>Authentication:</b> Internal only - called by Indexing Service<br><br>

<b>Note:</b> This endpoint creates content blocks from a previously parsed
PDF document. It may involve LLM calls for table processing.
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await doclingServiceDoclingCreateBlocks(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=doclingServiceDoclingCreateBlocks.js.map