/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { documentUploadGetDirectUploadUrl } from "../../funcs/documentUploadGetDirectUploadUrl.js";
import { GetDirectUploadUrlRequest$zodSchema } from "../../models/getdirectuploadurlop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetDirectUploadUrlRequest$zodSchema,
};
export const tool$documentUploadGetDirectUploadUrl = {
    name: "document-upload-get-direct-upload-url",
    description: `Get direct upload URL

Generate a presigned URL for direct client-to-storage upload, bypassing the server for large files.<br><br>
<b>Overview:</b><br>
This endpoint provides a presigned URL that allows clients to upload directly to storage (S3/Azure) without routing through the server. Essential for large file uploads.<br><br>
<b>Direct Upload Flow:</b><br>
<ol>
<li>Create document placeholder with <code>/placeholder</code></li>
<li>Call this endpoint with document ID</li>
<li>Receive presigned URL and document ID</li>
<li>Client uploads file directly to presigned URL (PUT request)</li>
<li>Document becomes available once upload completes</li>
</ol>
<b>Benefits:</b><br>
<ul>
<li>No server memory consumption for large files</li>
<li>Direct transfer to storage (faster)</li>
<li>Client-side progress tracking</li>
<li>Reduced server bandwidth</li>
</ul>
<b>URL Validity:</b><br>
Presigned URLs typically expire after 1 hour. Upload must complete before expiration.<br><br>
<b>Note:</b> Only available for S3 and Azure Blob storage. Local storage does not support direct upload.
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await documentUploadGetDirectUploadUrl(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=documentUploadGetDirectUploadUrl.js.map