/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { metricsCollectionSetMetricsServerUrl } from "../../funcs/metricsCollectionSetMetricsServerUrl.js";
import { SetMetricsServerUrlRequest$zodSchema } from "../../models/setmetricsserverurlop.js";
import { formatResult } from "../tools.js";
const args = {
    request: SetMetricsServerUrlRequest$zodSchema,
};
export const tool$metricsCollectionSetMetricsServerUrl = {
    name: "metrics-collection-set-metrics-server-url",
    description: `Configure metrics server URL

Set the remote server URL where metrics will be pushed.

**Use Cases:**
- Self-hosted analytics: Point to your own Prometheus-compatible endpoint
- Custom monitoring: Integrate with your organization's monitoring stack
- Development: Use a local endpoint for testing

**URL Requirements:**
- Must be a valid URL (http or https)
- Server must accept POST requests with JSON payload
- Server should return 2xx status for successful pushes

**Admin Access Required:** This endpoint requires administrator privileges.
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await metricsCollectionSetMetricsServerUrl(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=metricsCollectionSetMetricsServerUrl.js.map