/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { oauthAppsListScopes } from "../../funcs/oauthAppsListScopes.js";
import { formatResult } from "../tools.js";
export const tool$oauthAppsListScopes = {
    name: "oauth-apps-list-scopes",
    description: `List available scopes

List all available OAuth scopes that can be requested by apps.
<br><br>
Returns scope names, descriptions, and categories for display
in app configuration UI.
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    tool: async (client, ctx) => {
        const [result] = await oauthAppsListScopes(client, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=oauthAppsListScopes.js.map