/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { oauthAppsListTokens } from "../../funcs/oauthAppsListTokens.js";
import { ListOAuthAppTokensRequest$zodSchema } from "../../models/listoauthapptokensop.js";
import { formatResult } from "../tools.js";
const args = {
    request: ListOAuthAppTokensRequest$zodSchema,
};
export const tool$oauthAppsListTokens = {
    name: "oauth-apps-list-tokens",
    description: `List app tokens

List all active tokens issued to an OAuth app.
<br><br>
Useful for monitoring app usage and identifying tokens to revoke.
<br><br>
<b>Admin Only:</b> Requires admin privileges.
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await oauthAppsListTokens(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=oauthAppsListTokens.js.map