/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { oauthConfigurationListByType } from "../../funcs/oauthConfigurationListByType.js";
import { ListOAuthConfigsByTypeRequest$zodSchema } from "../../models/listoauthconfigsbytypeop.js";
import { formatResult } from "../tools.js";
const args = {
    request: ListOAuthConfigsByTypeRequest$zodSchema,
};
export const tool$oauthConfigurationListByType = {
    name: "oauth-configuration-list-by-type",
    description: `List OAuth configs for connector type

Get all OAuth configurations for a specific connector type.`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await oauthConfigurationListByType(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=oauthConfigurationListByType.js.map