/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { organizationsUpdateOrganization } from "../../funcs/organizationsUpdateOrganization.js";
import { UpdateOrganizationRequest$zodSchema } from "../../models/updateorganizationop.js";
import { formatResult } from "../tools.js";
const args = {
    request: UpdateOrganizationRequest$zodSchema,
};
export const tool$organizationsUpdateOrganization = {
    name: "organizations-update-organization",
    description: `Update organization

Update organization profile and settings information.<br><br>
<b>Overview:</b><br>
This endpoint allows administrators to update the organization's profile information, contact details, and address. Used in the organization settings section of the admin panel.<br><br>
<b>Updatable Fields:</b><br>
<ul>
<li><code>registeredName</code>: Official registered/legal name of the organization</li>
<li><code>shortName</code>: Short display name used in UI</li>
<li><code>phoneNumber</code>: Primary contact phone number</li>
<li><code>permanentAddress</code>: Full address object with street, city, state, country, postal code</li>
</ul>
<b>Restrictions:</b><br>
<ul>
<li>Only organization admins can perform updates</li>
<li>Contact email cannot be changed through this endpoint</li>
<li>Account type cannot be changed after creation</li>
</ul>
<b>Side Effects:</b><br>
<ul>
<li>Organization update event is published</li>
<li>Cached organization data is invalidated</li>
<li>Changes are reflected immediately across all services</li>
</ul>
<b>Validation:</b><br>
<ul>
<li>Phone number must be valid international format</li>
<li>Address fields have maximum length constraints</li>
<li>Names cannot be empty if provided</li>
</ul>
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await organizationsUpdateOrganization(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=organizationsUpdateOrganization.js.map