/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { permissionsUpdateKBPermissions } from "../../funcs/permissionsUpdateKBPermissions.js";
import { UpdateKBPermissionsRequest$zodSchema } from "../../models/updatekbpermissionsop.js";
import { formatResult } from "../tools.js";
const args = {
    request: UpdateKBPermissionsRequest$zodSchema,
};
export const tool$permissionsUpdateKBPermissions = {
    name: "permissions-update-KB-permissions",
    description: `Update permissions

Update permission roles for users or teams.<br><br>
<b>Required Permission:</b> OWNER or ORGANIZER
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await permissionsUpdateKBPermissions(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=permissionsUpdateKBPermissions.js.map