/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { queryServiceQueryServiceChatStream } from "../../funcs/queryServiceQueryServiceChatStream.js";
import { formatResult } from "../tools.js";
export const tool$queryServiceQueryServiceChatStream = {
    name: "query-service-query-service-chat-stream",
    description: `[Query Service] Streaming chat with knowledge base

⚠️ <b>INTERNAL SERVICE ENDPOINT</b><br><br>

Streaming conversational AI endpoint with real-time token delivery.<br><br>

<b>Service:</b> Query Service<br>
<b>Port:</b> 8000<br>
<b>Base URL:</b> <code>http://localhost:8000</code><br><br>

<b>Authentication:</b> Requires user JWT token (proxied from main API) or scoped service token<br><br>

<b>SSE Events:</b><br>
<ul>
<li><code>status</code>: Processing status updates</li>
<li><code>chunk</code>: Token/text chunks</li>
<li><code>citations</code>: Source citations</li>
<li><code>done</code>: Stream complete</li>
<li><code>error</code>: Error occurred</li>
</ul>
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    tool: async (client, ctx) => {
        const [result] = await queryServiceQueryServiceChatStream(client, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=queryServiceQueryServiceChatStream.js.map