/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { recordsGetById } from "../../funcs/recordsGetById.js";
import { GetRecordByIdRequest$zodSchema } from "../../models/getrecordbyidop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetRecordByIdRequest$zodSchema,
};
export const tool$recordsGetById = {
    name: "records-get-by-id",
    description: `Get record by ID

Retrieve detailed information about a specific record.<br><br>
<b>Overview:</b><br>
Returns complete record metadata including name, type, indexing status, storage information, and version history.<br><br>
<b>File Conversion:</b><br>
Use the optional <code>convertTo</code> parameter to request file format conversion (e.g., PDF to text).
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await recordsGetById(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=recordsGetById.js.map