/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { semanticSearchGetById } from "../../funcs/semanticSearchGetById.js";
import { GetSearchByIdRequest$zodSchema } from "../../models/getsearchbyidop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetSearchByIdRequest$zodSchema,
};
export const tool$semanticSearchGetById = {
    name: "semantic-search-get-by-id",
    description: `Get search by ID

Retrieve a specific search result by its ID.<br><br>
<b>Overview:</b><br>
Returns the full search record including query, all results,
and any sharing/archive status.
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await semanticSearchGetById(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=semanticSearchGetById.js.map