/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { teamsGetById } from "../../funcs/teamsGetById.js";
import { GetTeamByIdRequest$zodSchema } from "../../models/getteambyidop.js";
import { formatResult } from "../tools.js";
const args = {
    request: GetTeamByIdRequest$zodSchema,
};
export const tool$teamsGetById = {
    name: "teams-get-by-id",
    description: `Get team by ID

Retrieve detailed information about a specific team.<br><br>
<b>Overview:</b><br>
Returns complete team details including metadata, member list with roles, and resource information. Use this for team profile pages and detailed views.<br><br>
<b>Response Includes:</b><br>
<ul>
<li>Team metadata (name, description, slug)</li>
<li>Owner and creator information</li>
<li>Member count and list (with pagination)</li>
<li>Team settings and permissions</li>
<li>Creation and modification timestamps</li>
</ul>
<b>Authorization:</b><br>
<ul>
<li>Team members can view their team</li>
<li>Organization admins can view any team</li>
</ul>
`,
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await teamsGetById(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=teamsGetById.js.map