/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Template data for user invitation email
 */
export type AppUserInviteTemplateData = {
  invitee: string;
  orgName: string;
  link: string;
};

export const AppUserInviteTemplateData$zodSchema: z.ZodType<
  AppUserInviteTemplateData
> = z.object({
  invitee: z.string(),
  link: z.string(),
  orgName: z.string(),
}).describe("Template data for user invitation email");
