/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";

/**
 * Organization auth configuration created successfully
 */
export type CreateOrgAuthConfigResponseBody = {
  message?: string | undefined;
  orgId?: string | undefined;
  userId?: string | undefined;
};

export const CreateOrgAuthConfigResponseBody$zodSchema: z.ZodType<
  CreateOrgAuthConfigResponseBody
> = z.object({
  message: z.string().optional(),
  orgId: z.string().optional(),
  userId: z.string().optional(),
}).describe("Organization auth configuration created successfully");

export type CreateOrgAuthConfigResponse =
  | CreateOrgAuthConfigResponseBody
  | AuthError;

export const CreateOrgAuthConfigResponse$zodSchema: z.ZodType<
  CreateOrgAuthConfigResponse
> = z.union([
  z.lazy(() => CreateOrgAuthConfigResponseBody$zodSchema),
  AuthError$zodSchema,
]);
