/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CreateDocumentPlaceholderPermissions = {
  Owner: "owner",
  Editor: "editor",
  Commentator: "commentator",
  Readonly: "readonly",
} as const;
export type CreateDocumentPlaceholderPermissions = ClosedEnum<
  typeof CreateDocumentPlaceholderPermissions
>;

export const CreateDocumentPlaceholderPermissions$zodSchema = z.enum([
  "owner",
  "editor",
  "commentator",
  "readonly",
]);

/**
 * Custom metadata key-value pairs
 */
export type CreateDocumentPlaceholderMetaData = {};

export const CreateDocumentPlaceholderMetaData$zodSchema: z.ZodType<
  CreateDocumentPlaceholderMetaData
> = z.object({}).describe("Custom metadata key-value pairs");

/**
 * Request payload
 */
export type CreateDocumentPlaceholderRequest = {
  documentName: string;
  alternateDocumentName?: string | undefined;
  documentPath: string;
  permissions?: CreateDocumentPlaceholderPermissions | undefined;
  metaData?: CreateDocumentPlaceholderMetaData | undefined;
  isVersionedFile?: boolean | undefined;
  extension: string;
};

export const CreateDocumentPlaceholderRequest$zodSchema: z.ZodType<
  CreateDocumentPlaceholderRequest
> = z.object({
  alternateDocumentName: z.string().optional(),
  documentName: z.string(),
  documentPath: z.string(),
  extension: z.string(),
  isVersionedFile: z.boolean().default(false),
  metaData: z.lazy(() => CreateDocumentPlaceholderMetaData$zodSchema)
    .optional(),
  permissions: CreateDocumentPlaceholderPermissions$zodSchema.default("owner"),
}).describe("Request payload");
