/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteAgentConversationRequest = {
  agentKey: string;
  conversationId: string;
};

export const DeleteAgentConversationRequest$zodSchema: z.ZodType<
  DeleteAgentConversationRequest
> = z.object({
  agentKey: z.string(),
  conversationId: z.string(),
});
