/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ListAgentConversationsRequest = { agentKey: string };

export const ListAgentConversationsRequest$zodSchema: z.ZodType<
  ListAgentConversationsRequest
> = z.object({
  agentKey: z.string().describe("Agent identifier"),
});
