/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { KBPermission, KBPermission$zodSchema } from "./kbpermission.js";

export type ListKBPermissionsRequest = { kbId: string };

export const ListKBPermissionsRequest$zodSchema: z.ZodType<
  ListKBPermissionsRequest
> = z.object({
  kbId: z.string(),
});

/**
 * Permissions list retrieved
 */
export type ListKBPermissionsResponse = {
  kbId?: string | undefined;
  permissions?: Array<KBPermission> | undefined;
  totalCount?: number | undefined;
};

export const ListKBPermissionsResponse$zodSchema: z.ZodType<
  ListKBPermissionsResponse
> = z.object({
  kbId: z.string().optional(),
  permissions: z.array(KBPermission$zodSchema).optional(),
  totalCount: z.int().optional(),
}).describe("Permissions list retrieved");
