/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Target parent folder for the record
 */
export type MoveRecordRequestBody = { newParentId: string | null };

export const MoveRecordRequestBody$zodSchema: z.ZodType<MoveRecordRequestBody> =
  z.object({
    newParentId: z.string().nullable(),
  }).describe("Target parent folder for the record");

export type MoveRecordRequest = {
  kbId: string;
  recordId: string;
  body: MoveRecordRequestBody;
};

export const MoveRecordRequest$zodSchema: z.ZodType<MoveRecordRequest> = z
  .object({
    body: z.lazy(() => MoveRecordRequestBody$zodSchema),
    kbId: z.string().describe("Knowledge base ID"),
    recordId: z.string().describe("Record ID to move"),
  });
