/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request payload
 */
export type ToggleMetricsCollectionRequest = {
  enableMetricCollection: boolean;
};

export const ToggleMetricsCollectionRequest$zodSchema: z.ZodType<
  ToggleMetricsCollectionRequest
> = z.object({
  enableMetricCollection: z.boolean(),
}).describe("Request payload");

/**
 * Metrics collection toggled successfully
 */
export type ToggleMetricsCollectionResponse = { message?: string | undefined };

export const ToggleMetricsCollectionResponse$zodSchema: z.ZodType<
  ToggleMetricsCollectionResponse
> = z.object({
  message: z.string().optional(),
}).describe("Metrics collection toggled successfully");
