/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { User, User$zodSchema } from "./user.js";

/**
 * Request payload
 */
export type UpdateUserLastNameRequestBody = { lastName: string };

export const UpdateUserLastNameRequestBody$zodSchema: z.ZodType<
  UpdateUserLastNameRequestBody
> = z.object({
  lastName: z.string(),
}).describe("Request payload");

export type UpdateUserLastNameRequest = {
  id: string;
  body: UpdateUserLastNameRequestBody;
};

export const UpdateUserLastNameRequest$zodSchema: z.ZodType<
  UpdateUserLastNameRequest
> = z.object({
  body: z.lazy(() => UpdateUserLastNameRequestBody$zodSchema),
  id: z.string().describe("User ID (24-character MongoDB ObjectId)"),
});

/**
 * Last name updated successfully
 */
export type UpdateUserLastNameResponse = {
  success?: boolean | undefined;
  data?: User | undefined;
};

export const UpdateUserLastNameResponse$zodSchema: z.ZodType<
  UpdateUserLastNameResponse
> = z.object({
  data: User$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("Last name updated successfully");
