/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request payload
 */
export type UpdateUserFullNameRequestBody = { fullName: string };

export const UpdateUserFullNameRequestBody$zodSchema: z.ZodType<
  UpdateUserFullNameRequestBody
> = z.object({
  fullName: z.string(),
}).describe("Request payload");

export type UpdateUserFullNameRequest = {
  id: string;
  body: UpdateUserFullNameRequestBody;
};

export const UpdateUserFullNameRequest$zodSchema: z.ZodType<
  UpdateUserFullNameRequest
> = z.object({
  body: z.lazy(() => UpdateUserFullNameRequestBody$zodSchema),
  id: z.string(),
});
