/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const AccountCreationTemplateData$zodSchema = z.object({
    link: z.string(),
    orgName: z.string(),
}).describe("Template data for organization account creation welcome email");
//# sourceMappingURL=accountcreationtemplatedata.js.map