/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { AddMessageRequest$zodSchema, } from "./addmessagerequest.js";
export const AddAgentMessageRequest$zodSchema = z.object({
    agentKey: z.string(),
    body: AddMessageRequest$zodSchema,
    conversationId: z.string(),
});
//# sourceMappingURL=addagentmessageop.js.map