/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { AddMessageRequest$zodSchema, } from "./addmessagerequest.js";
export const AddMessageRequestRequest$zodSchema = z.object({
    body: AddMessageRequest$zodSchema,
    conversationId: z.string().describe("Unique conversation identifier"),
});
//# sourceMappingURL=addmessageop.js.map