/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const AddUsersToGroupRequest$zodSchema = z.object({
    groupId: z.string(),
    userIds: z.array(z.string()),
}).describe("Request payload");
export const AddUsersToGroupResponse$zodSchema = z.object({
    addedCount: z.int().optional(),
    message: z.string().optional(),
    skippedCount: z.int().optional(),
    success: z.boolean().optional(),
}).describe("Users added to group successfully");
//# sourceMappingURL=adduserstogroupop.js.map