/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ConfigSchema$zodSchema = z.object({})
    .describe("JSON Schema for template customization options");
export const AgentTemplate$zodSchema = z.object({
    category: z.string().optional(),
    configSchema: z.lazy(() => ConfigSchema$zodSchema).optional(),
    createdAt: z.iso.datetime({ offset: true }).optional(),
    createdBy: z.string().optional(),
    defaultSystemPrompt: z.string().optional(),
    description: z.string().optional(),
    isPublic: z.boolean().optional(),
    name: z.string().optional(),
    recommendedTools: z.array(z.string()).optional(),
    templateId: z.string().optional(),
}).describe("Reusable template for creating agents. Templates define the base\nconfiguration that can be customized when creating an agent instance.\n");
//# sourceMappingURL=agenttemplate.js.map