/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { AuthenticateRequest$zodSchema, } from "./authenticaterequest.js";
import { AuthenticateResponse$zodSchema, } from "./authenticateresponse.js";
import { AuthError$zodSchema } from "./autherror.js";
export const AuthenticateRequestRequest$zodSchema = z.object({
    body: AuthenticateRequest$zodSchema,
    xSessionToken: z.string().describe("Session token received from `/initAuth` endpoint"),
});
export const AuthenticateResponseResponse$zodSchema = z.union([
    AuthenticateResponse$zodSchema,
    AuthError$zodSchema,
]);
//# sourceMappingURL=authenticateop.js.map