/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const CheckUserIsAdminRequest$zodSchema = z.object({
    id: z.string().describe("User ID to check for admin privileges"),
});
export const CheckUserIsAdminResponse$zodSchema = z.object({
    adminGroups: z.array(z.string()).optional(),
    isAdmin: z.boolean().optional(),
    message: z.string().optional(),
    success: z.boolean().optional(),
}).describe("User has admin access");
//# sourceMappingURL=checkuserisadminop.js.map