/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * Toggle type: 'sync' for data synchronization, 'agent' for AI agent integration
 */
export const ConnectorToggleRequestType = {
    Sync: "sync",
    Agent: "agent",
};
export const ConnectorToggleRequestType$zodSchema = z.enum([
    "sync",
    "agent",
]).describe("Toggle type: 'sync' for data synchronization, 'agent' for AI agent integration");
export const ConnectorToggleRequest$zodSchema = z.object({
    type: ConnectorToggleRequestType$zodSchema,
}).describe("Request to toggle connector active status");
//# sourceMappingURL=connectortogglerequest.js.map