/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * Scope determines visibility and access control for connectors:<br>
 *
 * @remarks
 * <ul>
 * <li><code>team</code> - Available to all users in the organization (admin-only creation)</li>
 * <li><code>personal</code> - Private to the creating user only</li>
 * </ul>
 */
export const ConnectorScope = {
    Team: "team",
    Personal: "personal",
};
export const ConnectorScope$zodSchema = z.enum([
    "team",
    "personal",
]).describe("Scope determines visibility and access control for connectors:<br>\n<ul>\n<li><code>team</code> - Available to all users in the organization (admin-only creation)</li>\n<li><code>personal</code> - Private to the creating user only</li>\n</ul>\n");
//# sourceMappingURL=connectorscope.js.map