/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ConnectorAuthType$zodSchema, } from "./connectorauthtype.js";
import { ConnectorScope$zodSchema } from "./connectorscope.js";
export const ConnectorType$zodSchema = z.object({
    appGroup: z.string().optional(),
    appGroupId: z.string().optional(),
    authTypes: z.array(ConnectorAuthType$zodSchema).optional(),
    categories: z.array(z.string()).optional(),
    connectorType: z.string().optional(),
    description: z.string().optional(),
    displayName: z.string().optional(),
    iconPath: z.string().optional(),
    isBeta: z.boolean().optional(),
    supportedScopes: z.array(ConnectorScope$zodSchema).optional(),
    supportsAgent: z.boolean().optional(),
    supportsRealtime: z.boolean().optional(),
    supportsSync: z.boolean().optional(),
}).describe("A connector type from the registry. Represents an available integration\nthat can be configured as a connector instance.\n");
//# sourceMappingURL=connectortype.js.map