/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ScheduleConfig$zodSchema } from "./scheduleconfig.js";
export const CrawlingJobData$zodSchema = z.object({
    connector: z.string(),
    connectorId: z.string(),
    metadata: z.record(z.string(), z.any()).optional(),
    orgId: z.string(),
    scheduleConfig: ScheduleConfig$zodSchema,
    timestamp: z.iso.datetime({ offset: true }),
    userId: z.string(),
}).describe("Data payload stored with each crawling job in the queue");
//# sourceMappingURL=crawlingjobdata.js.map