/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const CreateOAuthAppRequestAllowedGrantType = {
    AuthorizationCode: "authorization_code",
    ClientCredentials: "client_credentials",
    RefreshToken: "refresh_token",
};
export const CreateOAuthAppRequestAllowedGrantType$zodSchema = z.enum([
    "authorization_code",
    "client_credentials",
    "refresh_token",
]);
export const CreateOAuthAppRequest$zodSchema = z.object({
    accessTokenLifetime: z.int().default(3600),
    allowedGrantTypes: z.array(CreateOAuthAppRequestAllowedGrantType$zodSchema)
        .optional(),
    allowedScopes: z.array(z.string()),
    description: z.string().optional(),
    homepageUrl: z.string().optional(),
    isConfidential: z.boolean().default(true),
    name: z.string(),
    privacyPolicyUrl: z.string().optional(),
    redirectUris: z.array(z.string()),
    refreshTokenLifetime: z.int().default(604800),
    termsOfServiceUrl: z.string().optional(),
}).describe("Request to create a new OAuth app");
//# sourceMappingURL=createoauthapprequest.js.map