/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const CreateAgentModelConfig$zodSchema = z.object({
    maxTokens: z.int().optional(),
    modelKey: z.string().optional(),
    temperature: z.number().optional(),
});
export const CreateAgentRequest$zodSchema = z
    .object({
    description: z.string().optional(),
    isPublic: z.boolean().default(false),
    knowledgeBases: z.array(z.string()).optional(),
    modelConfig: z.lazy(() => CreateAgentModelConfig$zodSchema).optional(),
    name: z.string(),
    systemPrompt: z.string().optional(),
    tools: z.array(z.string()).optional(),
}).describe("Request payload");
//# sourceMappingURL=createagentop.js.map