/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const CreateAgentTemplateConfigSchema$zodSchema = z.object({}).describe("JSON Schema for customization");
export const CreateAgentTemplateRequest$zodSchema = z.object({
    category: z.string().optional(),
    configSchema: z.lazy(() => CreateAgentTemplateConfigSchema$zodSchema)
        .optional(),
    defaultSystemPrompt: z.string().optional(),
    description: z.string().optional(),
    isPublic: z.boolean().default(false),
    name: z.string(),
    recommendedTools: z.array(z.string()).optional(),
}).describe("Request payload");
//# sourceMappingURL=createagenttemplateop.js.map