/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * Storage type identifier
 */
export const CreateAzureBlobStorageConfigStorageType = {
    AzureBlob: "azureBlob",
};
export const CreateAzureBlobStorageConfigStorageType$zodSchema = z.enum([
    "azureBlob",
]).describe("Storage type identifier");
export const CreateAzureBlobStorageConfigRequest$zodSchema = z.object({
    accountKey: z.string().optional(),
    accountName: z.string().optional(),
    azureBlobConnectionString: z.string().optional(),
    containerName: z.string(),
    endpointProtocol: z.string().default("https"),
    endpointSuffix: z.string().default("core.windows.net"),
    storageType: CreateAzureBlobStorageConfigStorageType$zodSchema,
}).describe("Request body for Configure Azure Blob Storage");
//# sourceMappingURL=createazureblobstorageconfigop.js.map