/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * Storage type identifier
 */
export const CreateLocalStorageConfigStorageType = {
    Local: "local",
};
export const CreateLocalStorageConfigStorageType$zodSchema = z.enum([
    "local",
]).describe("Storage type identifier");
export const CreateLocalStorageConfigRequest$zodSchema = z.object({
    baseUrl: z.string().optional(),
    mountName: z.string().default("PipesHub"),
    storageType: CreateLocalStorageConfigStorageType$zodSchema,
}).describe("Request body for Configure Local Storage");
//# sourceMappingURL=createlocalstorageconfigop.js.map