/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const CustomSystemPrompt$zodSchema = z
    .object({
    customSystemPrompt: z.string().optional(),
}).describe("Custom system prompt configuration");
//# sourceMappingURL=customsystemprompt.js.map