/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const DeleteConnectorInstanceRequest$zodSchema = z.object({
    connectorId: z.string(),
});
export const DeleteConnectorInstanceResponse$zodSchema = z.object({
    message: z.string().optional(),
    success: z.boolean().optional(),
}).describe("Connector deleted");
//# sourceMappingURL=deleteconnectorinstanceop.js.map