/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const DeleteFolderRequest$zodSchema = z
    .object({
    folderId: z.string(),
    kbId: z.string(),
});
//# sourceMappingURL=deletefolderop.js.map