/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const DeleteAgentConversationRequest$zodSchema = z.object({
    agentKey: z.string(),
    conversationId: z.string(),
});
//# sourceMappingURL=deleteagentconversationop.js.map