/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const DeleteTeamRequest$zodSchema = z
    .object({
    teamId: z.string().describe("Unique identifier of the team to delete"),
});
export const DeleteTeamResponse$zodSchema = z
    .object({
    message: z.string().optional(),
    success: z.boolean().optional(),
}).describe("Team deleted successfully");
//# sourceMappingURL=deleteteamop.js.map