/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * Must be "DELETE" to confirm deletion
 */
export const Confirm = {
    Delete: "DELETE",
};
export const Confirm$zodSchema = z.enum([
    "DELETE",
]).describe("Must be \"DELETE\" to confirm deletion");
export const DeleteOrganizationRequest$zodSchema = z.object({
    confirm: Confirm$zodSchema,
});
export const DeleteOrganizationResponse$zodSchema = z.object({
    message: z.string().optional(),
    success: z.boolean().optional(),
}).describe("Organization deleted successfully");
//# sourceMappingURL=deleteorganizationop.js.map