/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ModelType$zodSchema } from "./modeltype.js";
export const DeleteAIModelProviderRequest$zodSchema = z.object({
    modelKey: z.string(),
    modelType: ModelType$zodSchema,
});
//# sourceMappingURL=deleteaimodelproviderop.js.map