/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const DeleteKnowledgeBaseRequest$zodSchema = z.object({
    kbId: z.string().describe("Knowledge base ID"),
});
export const DeleteKnowledgeBaseResponse$zodSchema = z.object({
    message: z.string().optional(),
    success: z.boolean().optional(),
}).describe("Knowledge base deleted successfully");
//# sourceMappingURL=deleteknowledgebaseop.js.map