/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
export const DriveWebhookOpServerList = [
    /**
     * Connector Service (Internal)
     */
    "http://localhost:8088",
];
//# sourceMappingURL=drivewebhookop.js.map