/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { AuthError$zodSchema } from "./autherror.js";
import { OAuthExchangeResponse$zodSchema, } from "./oauthexchangeresponse.js";
export const ExchangeOAuthCodeResponse$zodSchema = z.union([
    OAuthExchangeResponse$zodSchema,
    AuthError$zodSchema,
]);
//# sourceMappingURL=exchangeoauthcodeop.js.map