/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const FollowUpQuestion$zodSchema = z.object({
    confidence: z.string().optional(),
    question: z.string().optional(),
    reasoning: z.string().optional(),
}).describe("AI-suggested follow-up question");
//# sourceMappingURL=followupquestion.js.map