/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ForgotPasswordResponse$zodSchema = z.object({
    message: z.string().optional(),
}).describe("Password reset email sent successfully (or email not found - same response for security)");
//# sourceMappingURL=forgotpasswordop.js.map