/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const GetAgentRequest$zodSchema = z.object({
    agentKey: z.string().describe("Unique agent identifier"),
});
//# sourceMappingURL=getagentop.js.map