/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ModelType$zodSchema } from "./modeltype.js";
export const GetAvailableModelsByTypeRequest$zodSchema = z.object({
    modelType: ModelType$zodSchema,
});
//# sourceMappingURL=getavailablemodelsbytypeop.js.map