/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Message$zodSchema } from "./message.js";
/**
 * Sort direction
 */
export const GetConversationByIdSortOrder = {
    Asc: "asc",
    Desc: "desc",
};
export const GetConversationByIdSortOrder$zodSchema = z.enum([
    "asc",
    "desc",
]).describe("Sort direction");
export const GetConversationByIdRequest$zodSchema = z.object({
    conversationId: z.string().describe("Unique conversation identifier"),
    limit: z.int().default(10).describe("Number of messages per page"),
    page: z.int().default(1).describe("Page number for message pagination"),
    sortBy: z.string().default("createdAt").describe("Field to sort messages by"),
    sortOrder: GetConversationByIdSortOrder$zodSchema.default("desc"),
});
/**
 * Current status of the conversation:
 *
 * @remarks
 * <ul>
 * <li><code>INPROGRESS</code> - AI is processing</li>
 * <li><code>COMPLETED</code> - Response ready</li>
 * <li><code>FAILED</code> - Error occurred</li>
 * </ul>
 */
export const GetConversationByIdStatus = {
    Inprogress: "INPROGRESS",
    Completed: "COMPLETED",
    Failed: "FAILED",
};
export const GetConversationByIdStatus$zodSchema = z.enum([
    "INPROGRESS",
    "COMPLETED",
    "FAILED",
]).describe("Current status of the conversation:\n<ul>\n<li><code>INPROGRESS</code> - AI is processing</li>\n<li><code>COMPLETED</code> - Response ready</li>\n<li><code>FAILED</code> - Error occurred</li>\n</ul>\n");
export const GetConversationByIdModelInfo$zodSchema = z.object({
    chatMode: z.string().optional(),
    modelKey: z.string().optional(),
    modelName: z.string().optional(),
    modelProvider: z.string().optional(),
}).describe("AI model configuration used");
export const GetConversationByIdAccessLevel = {
    Read: "read",
    Write: "write",
};
export const GetConversationByIdAccessLevel$zodSchema = z.enum([
    "read",
    "write",
]);
export const GetConversationByIdSharedWith$zodSchema = z.object({
    accessLevel: GetConversationByIdAccessLevel$zodSchema.optional(),
    userId: z.string().optional(),
});
export const GetConversationByIdPagination$zodSchema = z.object({
    limit: z.int().optional(),
    page: z.int().optional(),
    totalMessages: z.int().optional(),
    totalPages: z.int().optional(),
});
export const GetConversationByIdResponse$zodSchema = z.object({
    _id: z.string().optional(),
    archivedBy: z.string().optional(),
    createdAt: z.iso.datetime({ offset: true }).optional(),
    failReason: z.string().optional(),
    initiator: z.string().optional(),
    isArchived: z.boolean().default(false),
    isShared: z.boolean().default(false),
    lastActivityAt: z.int().optional(),
    messages: z.array(Message$zodSchema).optional(),
    modelInfo: z.lazy(() => GetConversationByIdModelInfo$zodSchema).optional(),
    orgId: z.string().optional(),
    pagination: z.lazy(() => GetConversationByIdPagination$zodSchema).optional(),
    shareLink: z.string().optional(),
    sharedWith: z.array(z.lazy(() => GetConversationByIdSharedWith$zodSchema))
        .optional(),
    status: GetConversationByIdStatus$zodSchema.optional(),
    title: z.string().optional(),
    updatedAt: z.iso.datetime({ offset: true }).optional(),
    userId: z.string().optional(),
}).describe("A conversation represents a chat session between a user and the AI.\nConversations maintain context across multiple messages and can be\nshared, archived, and organized.\n");
//# sourceMappingURL=getconversationbyidop.js.map