/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Document$zodSchema } from "./document.js";
export const GetDocumentByIdRequest$zodSchema = z.object({
    documentId: z.string().describe("Document ID (24-character MongoDB ObjectId)"),
});
export const GetDocumentByIdResponse$zodSchema = z.object({
    data: Document$zodSchema.optional(),
    success: z.boolean().optional(),
}).describe("Document details retrieved successfully");
//# sourceMappingURL=getdocumentbyidop.js.map