/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const GetDirectUploadUrlRequest$zodSchema = z.object({
    documentId: z.string().describe("Document ID from placeholder creation"),
});
export const GetDirectUploadUrlResponse$zodSchema = z.object({
    documentId: z.string().optional(),
    signedUrl: z.string().optional(),
    success: z.boolean().optional(),
}).describe("Direct upload URL generated successfully");
//# sourceMappingURL=getdirectuploadurlop.js.map