/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { UserGroup$zodSchema } from "./usergroup.js";
export const GetGroupsForUserRequest$zodSchema = z.object({
    userId: z.string().describe("Unique identifier of the user"),
});
export const GetGroupsForUserResponse$zodSchema = z.object({
    data: z.array(UserGroup$zodSchema).optional(),
    success: z.boolean().optional(),
}).describe("User's groups retrieved successfully");
//# sourceMappingURL=getgroupsforuserop.js.map