/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const GetOrganizationLogoResponse$zodSchema = z.object({
    hasLogo: z.boolean().optional(),
    logoUrl: z.string().optional(),
    success: z.boolean().optional(),
}).describe("Logo URL retrieved successfully");
//# sourceMappingURL=getorganizationlogoop.js.map