/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ConnectorType$zodSchema } from "./connectortype.js";
export const GetOAuthConnectorTypeRequest$zodSchema = z.object({
    connectorType: z.string(),
});
export const GetOAuthConnectorTypeResponse$zodSchema = z.object({
    connector: ConnectorType$zodSchema.optional(),
    success: z.boolean().optional(),
}).describe("Connector type retrieved");
//# sourceMappingURL=getoauthconnectortypeop.js.map