/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { User$zodSchema } from "./user.js";
export const GetUsersInGroupRequest$zodSchema = z.object({
    groupId: z.string().describe("Unique identifier of the user group"),
    limit: z.int().default(20).describe("Number of users per page"),
    page: z.int().default(1).describe("Page number for pagination (1-based)"),
});
export const GetUsersInGroupPagination$zodSchema = z.object({
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.int().optional(),
    totalPages: z.int().optional(),
});
export const GetUsersInGroupResponse$zodSchema = z.object({
    data: z.array(User$zodSchema).optional(),
    pagination: z.lazy(() => GetUsersInGroupPagination$zodSchema).optional(),
    success: z.boolean().optional(),
}).describe("Users in group retrieved successfully");
//# sourceMappingURL=getusersingroupop.js.map