/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Team$zodSchema } from "./team.js";
export const GetUserTeamsRequest$zodSchema = z
    .object({
    limit: z.int().default(20).describe("Number of teams per page"),
    page: z.int().default(1).describe("Page number for pagination (1-based)"),
});
export const GetUserTeamsRole = {
    Owner: "owner",
    Admin: "admin",
    Member: "member",
    Viewer: "viewer",
};
export const GetUserTeamsRole$zodSchema = z.enum([
    "owner",
    "admin",
    "member",
    "viewer",
]);
export const GetUserTeamsData$zodSchema = z.object({
    joinedAt: z.iso.datetime({ offset: true }).optional(),
    role: GetUserTeamsRole$zodSchema.optional(),
    team: Team$zodSchema.optional(),
});
export const GetUserTeamsPagination$zodSchema = z.object({
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.int().optional(),
});
export const GetUserTeamsResponse$zodSchema = z
    .object({
    data: z.array(z.lazy(() => GetUserTeamsData$zodSchema)).optional(),
    pagination: z.lazy(() => GetUserTeamsPagination$zodSchema).optional(),
    success: z.boolean().optional(),
}).describe("User's teams retrieved successfully");
//# sourceMappingURL=getuserteamsop.js.map