/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const GoogleWorkspaceOAuthConfig$zodSchema = z.object({
    clientId: z.string(),
    clientSecret: z.string(),
    enableRealTimeUpdates: z.boolean().default(false),
    topicName: z.string().optional(),
}).describe("Google Workspace OAuth configuration for connectors");
//# sourceMappingURL=googleworkspaceoauthconfig.js.map