/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const InitAuthRequest$zodSchema = z.object({
    email: z.string(),
}).describe("Request to initialize authentication session");
//# sourceMappingURL=initauthrequest.js.map