/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * User's role in this knowledge base
 */
export const UserRoleEnum = {
    Owner: "OWNER",
    Organizer: "ORGANIZER",
    Fileorganizer: "FILEORGANIZER",
    Writer: "WRITER",
    Commenter: "COMMENTER",
    Reader: "READER",
};
export const UserRoleEnum$zodSchema = z.enum([
    "OWNER",
    "ORGANIZER",
    "FILEORGANIZER",
    "WRITER",
    "COMMENTER",
    "READER",
]).describe("User's role in this knowledge base");
export const KnowledgeBase$zodSchema = z.object({
    _key: z.string().optional(),
    createdAtTimestamp: z.int().optional(),
    isDeleted: z.boolean().default(false),
    name: z.string(),
    orgId: z.string(),
    updatedAtTimestamp: z.int().optional(),
    userRole: UserRoleEnum$zodSchema.optional(),
});
//# sourceMappingURL=knowledgebase.js.map