/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ListAgentConversationsRequest$zodSchema = z.object({
    agentKey: z.string().describe("Agent identifier"),
});
//# sourceMappingURL=listagentconversationsop.js.map