/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { KnowledgeBase$zodSchema } from "./knowledgebase.js";
import { PaginationInfo$zodSchema } from "./paginationinfo.js";
/**
 * Field to sort by
 */
export const ListKnowledgeBasesSortBy = {
    Name: "name",
    CreatedAtTimestamp: "createdAtTimestamp",
    UpdatedAtTimestamp: "updatedAtTimestamp",
    UserRole: "userRole",
};
export const ListKnowledgeBasesSortBy$zodSchema = z.enum([
    "name",
    "createdAtTimestamp",
    "updatedAtTimestamp",
    "userRole",
]).describe("Field to sort by");
/**
 * Sort direction
 */
export const ListKnowledgeBasesSortOrder = {
    Asc: "asc",
    Desc: "desc",
};
export const ListKnowledgeBasesSortOrder$zodSchema = z.enum([
    "asc",
    "desc",
]).describe("Sort direction");
export const ListKnowledgeBasesRequest$zodSchema = z.object({
    limit: z.int().default(20).describe("Results per page (max 100)"),
    page: z.int().default(1).describe("Page number (1-indexed)"),
    permissions: z.string().describe("Filter by permission roles (comma-separated)").optional(),
    search: z.string().describe("Search query for KB names (max 1000 chars)")
        .optional(),
    sortBy: ListKnowledgeBasesSortBy$zodSchema.default("name"),
    sortOrder: ListKnowledgeBasesSortOrder$zodSchema.default("asc"),
});
export const ListKnowledgeBasesResponse$zodSchema = z.object({
    knowledgeBases: z.array(KnowledgeBase$zodSchema).optional(),
    pagination: PaginationInfo$zodSchema.optional(),
}).describe("Successful operation");
//# sourceMappingURL=listknowledgebasesop.js.map