/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Team$zodSchema } from "./team.js";
export const ListTeamsRequest$zodSchema = z.object({
    limit: z.int().default(10).describe("Number of results per page"),
    page: z.int().default(1).describe("Page number (1-based)"),
    search: z.string().describe("Search teams by name or description")
        .optional(),
});
export const ListTeamsPagination$zodSchema = z
    .object({
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.int().optional(),
    totalPages: z.int().optional(),
});
export const ListTeamsResponse$zodSchema = z
    .object({
    data: z.array(Team$zodSchema).optional(),
    pagination: z.lazy(() => ListTeamsPagination$zodSchema).optional(),
    success: z.boolean().optional(),
}).describe("Teams retrieved successfully");
//# sourceMappingURL=listteamsop.js.map