/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ConnectorInstance$zodSchema, } from "./connectorinstance.js";
import { ConnectorPagination$zodSchema, } from "./connectorpagination.js";
import { ConnectorScope$zodSchema } from "./connectorscope.js";
export const ListConnectorInstancesRequest$zodSchema = z.object({
    limit: z.int().default(20),
    page: z.int().default(1),
    scope: ConnectorScope$zodSchema.optional(),
    search: z.string().describe("Search by instance name").optional(),
});
export const ListConnectorInstancesResponse$zodSchema = z.object({
    connectors: z.array(ConnectorInstance$zodSchema).optional(),
    pagination: ConnectorPagination$zodSchema.optional(),
    success: z.boolean().optional(),
}).describe("Instances retrieved");
//# sourceMappingURL=listconnectorinstancesop.js.map