/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { KBPermission$zodSchema } from "./kbpermission.js";
export const ListKBPermissionsRequest$zodSchema = z.object({
    kbId: z.string(),
});
export const ListKBPermissionsResponse$zodSchema = z.object({
    kbId: z.string().optional(),
    permissions: z.array(KBPermission$zodSchema).optional(),
    totalCount: z.int().optional(),
}).describe("Permissions list retrieved");
//# sourceMappingURL=listkbpermissionsop.js.map