/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const Ratings$zodSchema = z.object({
    accuracy: z.int().optional(),
    clarity: z.int().optional(),
    completeness: z.int().optional(),
    relevance: z.int().optional(),
});
export const Category = {
    IncorrectInformation: "incorrect_information",
    MissingInformation: "missing_information",
    OutdatedInformation: "outdated_information",
    IrrelevantResponse: "irrelevant_response",
    TooVerbose: "too_verbose",
    TooBrief: "too_brief",
    FormattingIssues: "formatting_issues",
    CitationIssues: "citation_issues",
};
export const Category$zodSchema = z.enum([
    "incorrect_information",
    "missing_information",
    "outdated_information",
    "irrelevant_response",
    "too_verbose",
    "too_brief",
    "formatting_issues",
    "citation_issues",
]);
export const Comments$zodSchema = z.object({
    negative: z.string().optional(),
    positive: z.string().optional(),
    suggestions: z.string().optional(),
});
export const CitationFeedback$zodSchema = z.object({
    citationId: z.string().optional(),
    comment: z.string().optional(),
    isRelevant: z.boolean().optional(),
    relevanceScore: z.int().optional(),
});
export const MessageFeedback$zodSchema = z.object({
    categories: z.array(Category$zodSchema).optional(),
    citationFeedback: z.array(z.lazy(() => CitationFeedback$zodSchema))
        .optional(),
    comments: z.lazy(() => Comments$zodSchema).optional(),
    followUpQuestionsHelpful: z.boolean().optional(),
    isHelpful: z.boolean().optional(),
    ratings: z.lazy(() => Ratings$zodSchema).optional(),
}).describe("Comprehensive feedback on an AI response. Feedback helps improve\nthe AI's performance and response quality over time.\n");
//# sourceMappingURL=messagefeedback.js.map