/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * Type of AI model
 */
export const ModelType = {
    Llm: "llm",
    Embedding: "embedding",
    Ocr: "ocr",
    Slm: "slm",
    Reasoning: "reasoning",
    MultiModal: "multiModal",
    ImageGeneration: "imageGeneration",
    Tts: "tts",
    Stt: "stt",
};
export const ModelType$zodSchema = z.enum([
    "llm",
    "embedding",
    "ocr",
    "slm",
    "reasoning",
    "multiModal",
    "imageGeneration",
    "tts",
    "stt",
]).describe("Type of AI model");
//# sourceMappingURL=modeltype.js.map