/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const MonthlyScheduleConfigScheduleType = {
    Monthly: "monthly",
};
export const MonthlyScheduleConfigScheduleType$zodSchema = z.enum([
    "monthly",
]);
export const MonthlyScheduleConfig$zodSchema = z.object({
    dayOfMonth: z.int(),
    hour: z.int(),
    isEnabled: z.boolean().default(true),
    minute: z.int(),
    scheduleType: MonthlyScheduleConfigScheduleType$zodSchema,
    timezone: z.string().default("UTC"),
}).describe("Run crawling job on a specified day of each month");
//# sourceMappingURL=monthlyscheduleconfig.js.map