/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * Type of token
 */
export const TokenType = {
    Access: "access",
    Refresh: "refresh",
};
export const TokenType$zodSchema = z.enum([
    "access",
    "refresh",
]).describe("Type of token");
export const OAuthTokenListItem$zodSchema = z
    .object({
    createdAt: z.iso.datetime({ offset: true }).optional(),
    expiresAt: z.iso.datetime({ offset: true }).optional(),
    id: z.string().optional(),
    isRevoked: z.boolean().optional(),
    scopes: z.array(z.string()).optional(),
    tokenType: TokenType$zodSchema.optional(),
    userId: z.string().optional(),
}).describe("Information about an issued token");
//# sourceMappingURL=oauthtokenlistitem.js.map