/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * App status
 */
export const OAuthAppWithSecretStatus = {
    Active: "active",
    Suspended: "suspended",
    Revoked: "revoked",
};
export const OAuthAppWithSecretStatus$zodSchema = z.enum([
    "active",
    "suspended",
    "revoked",
]).describe("App status");
export const OAuthAppWithSecret$zodSchema = z
    .object({
    accessTokenLifetime: z.int().optional(),
    allowedGrantTypes: z.array(z.string()).optional(),
    allowedScopes: z.array(z.string()).optional(),
    clientId: z.string().optional(),
    clientSecret: z.string(),
    createdAt: z.iso.datetime({ offset: true }).optional(),
    description: z.string().optional(),
    homepageUrl: z.string().optional(),
    id: z.string().optional(),
    isConfidential: z.boolean().optional(),
    logoUrl: z.string().optional(),
    name: z.string().optional(),
    privacyPolicyUrl: z.string().optional(),
    redirectUris: z.array(z.string()).optional(),
    refreshTokenLifetime: z.int().optional(),
    slug: z.string().optional(),
    status: OAuthAppWithSecretStatus$zodSchema.optional(),
    termsOfServiceUrl: z.string().optional(),
    updatedAt: z.iso.datetime({ offset: true }).optional(),
}).describe("OAuth app details (without secret)");
//# sourceMappingURL=oauthappwithsecret.js.map