/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const QueryListToolsOpServerList = [
    /**
     * Query Service
     */
    "http://localhost:8000",
];
export const ParametersT$zodSchema = z.object({})
    .describe("Tool parameter definitions");
export const QueryListToolsResponse$zodSchema = z.object({
    description: z.string().optional(),
    name: z.string().optional(),
    parameters: z.lazy(() => ParametersT$zodSchema).optional(),
    tags: z.array(z.string()).optional(),
});
//# sourceMappingURL=querylisttoolsop.js.map