/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ReindexFailedConnectorRecordsRequest$zodSchema = z.object({
    app: z.string(),
    connectorId: z.string(),
}).describe("Request body for Reindex failed connector records");
//# sourceMappingURL=reindexfailedconnectorrecordsop.js.map