/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { AuthError$zodSchema } from "./autherror.js";
import { PasswordResetResponse$zodSchema, } from "./passwordresetresponse.js";
export const ResetPasswordResponse$zodSchema = z.union([
    PasswordResetResponse$zodSchema,
    AuthError$zodSchema,
]);
//# sourceMappingURL=resetpasswordop.js.map