/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const RevokeAllOAuthAppTokensRequest$zodSchema = z.object({
    appId: z.string().describe("OAuth app ID"),
});
export const RevokeAllOAuthAppTokensResponse$zodSchema = z.object({
    count: z.int().optional(),
    message: z.string().optional(),
}).describe("All tokens revoked");
//# sourceMappingURL=revokealloauthapptokensop.js.map