/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Document$zodSchema } from "./document.js";
export const RollBackToPreviousVersionRequestBody$zodSchema = z.object({
    note: z.string(),
    version: z.string(),
}).describe("Request payload");
export const RollBackToPreviousVersionRequest$zodSchema = z.object({
    body: z.lazy(() => RollBackToPreviousVersionRequestBody$zodSchema),
    documentId: z.string().describe("Document ID (24-character MongoDB ObjectId)"),
});
export const RollBackToPreviousVersionResponse$zodSchema = z.object({
    data: Document$zodSchema.optional(),
    message: z.string().optional(),
    success: z.boolean().optional(),
}).describe("Document rolled back successfully");
//# sourceMappingURL=rollbacktopreviousversionop.js.map