/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { SearchResultItem$zodSchema, } from "./searchresultitem.js";
export const SearchResultAccessLevel = {
    Read: "read",
    Write: "write",
};
export const SearchResultAccessLevel$zodSchema = z.enum([
    "read",
    "write",
]);
export const SearchResultSharedWith$zodSchema = z.object({
    accessLevel: SearchResultAccessLevel$zodSchema.optional(),
    userId: z.string().optional(),
});
export const SearchResult$zodSchema = z.object({
    _id: z.string().optional(),
    createdAt: z.iso.datetime({ offset: true }).optional(),
    isArchived: z.boolean().default(false),
    isShared: z.boolean().default(false),
    orgId: z.string().optional(),
    query: z.string().optional(),
    records: z.record(z.string(), z.string()).optional(),
    results: z.array(SearchResultItem$zodSchema).optional(),
    searchId: z.string().optional(),
    sharedWith: z.array(z.lazy(() => SearchResultSharedWith$zodSchema))
        .optional(),
    userId: z.string().optional(),
}).describe("Result of a semantic search operation, containing matching\ndocument chunks with relevance scores.\n");
//# sourceMappingURL=searchresult.js.map