/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { SemanticSearchFilters$zodSchema, } from "./semanticsearchfilters.js";
export const SemanticSearchRequest$zodSchema = z.object({
    chatMode: z.string().optional(),
    filters: SemanticSearchFilters$zodSchema.optional(),
    limit: z.int().default(10),
    modelFriendlyName: z.string().optional(),
    modelKey: z.string().optional(),
    modelName: z.string().optional(),
    query: z.string(),
}).describe("Request body for `POST /search`. Performs a semantic vector search\nacross the caller's organization and persists a search record that\ncan later be retrieved via `GET /search/{searchId}`.<br><br>\n<b>How Semantic Search Works:</b><br>\n<ol>\n<li>Query is converted to vector embeddings</li>\n<li>Similar content is found using vector similarity</li>\n<li>Results are ranked by relevance score</li>\n<li>Matching chunks with metadata are returned</li>\n</ol>\n<b>Filtering:</b> Use `filters` to narrow scope by connector,\nknowledge base, department, module, or record type. See\n`SemanticSearchFilters`.<br><br>\n<b>Notes for programmatic / MCP callers:</b><br>\n<ul>\n<li>To resolve a filename or topic to a downloadable record, call\n    this endpoint and read\n    <code>searchResponse.searchResults[*].metadata.recordId</code>\n    (or any key of <code>searchResponse.virtual_to_record_map</code>).\n    Then pass that id to\n    <code>GET /knowledgeBase/stream/record/{recordId}</code>.</li>\n<li>Use <code>limit</code> aggressively (5–10) when searching just to\n    resolve a record id; raise it only when you need ranked snippets.</li>\n</ul>\n");
//# sourceMappingURL=semanticsearchrequest.js.map