/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const SetMetricsPushIntervalRequest$zodSchema = z.object({
    pushIntervalMs: z.int(),
}).describe("Request payload");
export const SetMetricsPushIntervalResponse$zodSchema = z.object({
    message: z.string().optional(),
}).describe("Push interval updated successfully");
//# sourceMappingURL=setmetricspushintervalop.js.map