/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ShareRequest$zodSchema } from "./sharerequest.js";
export const ShareConversationRequest$zodSchema = z.object({
    body: ShareRequest$zodSchema,
    conversationId: z.string(),
});
//# sourceMappingURL=shareconversationop.js.map