/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ShareRequest$zodSchema } from "./sharerequest.js";
export const ShareAgentRequest$zodSchema = z
    .object({
    agentKey: z.string(),
    body: ShareRequest$zodSchema,
});
//# sourceMappingURL=shareagentop.js.map