/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const SSOAuthConfig$zodSchema = z.object({
    certificate: z.string(),
    emailKey: z.string(),
    entryPoint: z.string(),
}).describe("SAML SSO authentication configuration");
//# sourceMappingURL=ssoauthconfig.js.map