/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const SuspiciousLoginTemplateData$zodSchema = z.object({
    link: z.string(),
}).describe("Template data for suspicious login attempt security alert email");
//# sourceMappingURL=suspiciouslogintemplatedata.js.map