/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ToggleMetricsCollectionRequest$zodSchema = z.object({
    enableMetricCollection: z.boolean(),
}).describe("Request payload");
export const ToggleMetricsCollectionResponse$zodSchema = z.object({
    message: z.string().optional(),
}).describe("Metrics collection toggled successfully");
//# sourceMappingURL=togglemetricscollectionop.js.map