/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const TokenPasswordResetRequest$zodSchema = z.object({
    password: z.string(),
}).describe("Request to reset password using email token");
//# sourceMappingURL=tokenpasswordresetrequest.js.map