/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const UnshareSearchRequestBody$zodSchema = z.object({
    userIds: z.array(z.string()),
}).describe("Request body for Revoke search access");
export const UnshareSearchRequest$zodSchema = z
    .object({
    body: z.lazy(() => UnshareSearchRequestBody$zodSchema),
    searchId: z.string(),
});
//# sourceMappingURL=unsharesearchop.js.map