/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { AuthError$zodSchema } from "./autherror.js";
export const UpdateAuthMethodResponseBody$zodSchema = z.object({
    message: z.string().optional(),
}).describe("Authentication methods updated successfully");
export const UpdateAuthMethodResponse$zodSchema = z.union([
    z.lazy(() => UpdateAuthMethodResponseBody$zodSchema),
    AuthError$zodSchema,
]);
//# sourceMappingURL=updateauthmethodop.js.map