/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import * as b64$ from "../lib/base64.js";
export const UpdateDocumentBufferFile$zodSchema = z.object({
    content: z.string().describe("Base64-encoded binary content").transform(b64$.bytesFromBase64),
    fileName: z.string(),
});
export const UpdateDocumentBufferRequestBody$zodSchema = z.object({
    file: z.lazy(() => UpdateDocumentBufferFile$zodSchema),
}).describe("Request payload");
export const UpdateDocumentBufferRequest$zodSchema = z.object({
    body: z.lazy(() => UpdateDocumentBufferRequestBody$zodSchema),
    documentId: z.string().describe("Document ID (24-character MongoDB ObjectId)"),
});
export const UpdateDocumentBufferResponse$zodSchema = z.object({
    message: z.string().optional(),
    success: z.boolean().optional(),
}).describe("Buffer updated successfully");
//# sourceMappingURL=updatedocumentbufferop.js.map