/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { User$zodSchema } from "./user.js";
export const UpdateUserDesignationRequestBody$zodSchema = z.object({
    designation: z.string(),
}).describe("Request payload");
export const UpdateUserDesignationRequest$zodSchema = z.object({
    body: z.lazy(() => UpdateUserDesignationRequestBody$zodSchema),
    id: z.string().describe("User ID (24-character MongoDB ObjectId)"),
});
export const UpdateUserDesignationResponse$zodSchema = z.object({
    data: User$zodSchema.optional(),
    success: z.boolean().optional(),
}).describe("Designation updated successfully");
//# sourceMappingURL=updateuserdesignationop.js.map