/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Team$zodSchema } from "./team.js";
export const UpdateTeamRequestBody$zodSchema = z.object({
    description: z.string().optional(),
    name: z.string().optional(),
}).describe("Request payload");
export const UpdateTeamRequest$zodSchema = z
    .object({
    body: z.lazy(() => UpdateTeamRequestBody$zodSchema),
    teamId: z.string().describe("Team ID (24-character MongoDB ObjectId)"),
});
export const UpdateTeamResponse$zodSchema = z
    .object({
    data: Team$zodSchema.optional(),
    message: z.string().optional(),
    success: z.boolean().optional(),
}).describe("Team updated successfully");
//# sourceMappingURL=updateteamop.js.map