/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
/**
 * New role to assign to the user
 */
export const UpdateTeamUserPermissionsRole = {
    Owner: "owner",
    Admin: "admin",
    Member: "member",
    Viewer: "viewer",
};
export const UpdateTeamUserPermissionsRole$zodSchema = z.enum([
    "owner",
    "admin",
    "member",
    "viewer",
]).describe("New role to assign to the user");
export const UpdateTeamUserPermissionsRequestBody$zodSchema = z.object({
    role: UpdateTeamUserPermissionsRole$zodSchema,
    userId: z.string(),
}).describe("Request payload");
export const UpdateTeamUserPermissionsRequest$zodSchema = z.object({
    body: z.lazy(() => UpdateTeamUserPermissionsRequestBody$zodSchema),
    teamId: z.string().describe("Unique identifier of the team"),
});
export const UpdateTeamUserPermissionsResponse$zodSchema = z.object({
    message: z.string().optional(),
    newRole: z.string().optional(),
    previousRole: z.string().optional(),
    success: z.boolean().optional(),
}).describe("User role updated successfully");
//# sourceMappingURL=updateteamuserpermissionsop.js.map