/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { ConnectorAuthConfig$zodSchema, } from "./connectorauthconfig.js";
export const UpdateConnectorAuthRequest$zodSchema = z.object({
    auth: ConnectorAuthConfig$zodSchema,
    baseUrl: z.string().optional(),
}).describe("Request to update authentication config (clears OAuth tokens, requires re-auth)");
//# sourceMappingURL=updateconnectorauthrequest.js.map