/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const UpdateConnectorNameRequest$zodSchema = z.object({
    instanceName: z.string(),
}).describe("Request to update connector instance name");
//# sourceMappingURL=updateconnectornamerequest.js.map