/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import * as b64$ from "../lib/base64.js";
export const UploadRecordsToKBFile$zodSchema = z.object({
    content: z.string().describe("Base64-encoded binary content").transform(b64$.bytesFromBase64),
    fileName: z.string(),
});
export const UploadRecordsToKBRequestBody$zodSchema = z.object({
    files: z.array(z.lazy(() => UploadRecordsToKBFile$zodSchema)),
    files_metadata: z.string().optional(),
    isVersioned: z.boolean().default(true),
    recordType: z.string().default("FILE"),
}).describe("Request payload");
export const UploadRecordsToKBRequest$zodSchema = z.object({
    body: z.lazy(() => UploadRecordsToKBRequestBody$zodSchema),
    kbId: z.string().describe("Knowledge base ID"),
});
//# sourceMappingURL=uploadrecordstokbop.js.map