/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { Document$zodSchema } from "./document.js";
/**
 * Default permission level for shared access
 */
export const UploadDocumentPermissions = {
    Owner: "owner",
    Editor: "editor",
    Commentator: "commentator",
    Readonly: "readonly",
};
export const UploadDocumentPermissions$zodSchema = z.enum([
    "owner",
    "editor",
    "commentator",
    "readonly",
]).describe("Default permission level for shared access");
/**
 * Enable version control for this document
 */
export const IsVersionedFile = {
    True: "true",
    False: "false",
};
export const IsVersionedFile$zodSchema = z.enum([
    "true",
    "false",
]).describe("Enable version control for this document");
export const UploadDocumentFile$zodSchema = z
    .object({
    content: z.string().describe("Base64-encoded binary content").transform(b64$.bytesFromBase64),
    fileName: z.string(),
});
export const UploadDocumentRequest$zodSchema = z.object({
    alternateDocumentName: z.string().optional(),
    customMetadata: z.string().optional(),
    documentName: z.string(),
    documentPath: z.string().optional(),
    file: z.lazy(() => UploadDocumentFile$zodSchema),
    isVersionedFile: IsVersionedFile$zodSchema,
    permissions: UploadDocumentPermissions$zodSchema.default("owner"),
}).describe("Request payload");
export const UploadDocumentResponse$zodSchema = z.object({
    Headers: z.record(z.string(), z.array(z.string())).default({}),
    Result: Document$zodSchema,
});
//# sourceMappingURL=uploaddocumentop.js.map