/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const WeeklyScheduleConfigScheduleType = {
    Weekly: "weekly",
};
export const WeeklyScheduleConfigScheduleType$zodSchema = z.enum([
    "weekly",
]);
export const WeeklyScheduleConfig$zodSchema = z
    .object({
    daysOfWeek: z.array(z.int()),
    hour: z.int(),
    isEnabled: z.boolean().default(true),
    minute: z.int(),
    scheduleType: WeeklyScheduleConfigScheduleType$zodSchema,
    timezone: z.string().default("UTC"),
}).describe("Run crawling job on specified days of the week");
//# sourceMappingURL=weeklyscheduleconfig.js.map