workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    PipesHub API:
        inputs:
            - location: ../../open-api/source_specs/pipeshub-openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/pipeshub/test/pipes-hub-api
targets:
    pipeshub:
        target: mcp-typescript
        source: PipesHub API
