/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Template data for organization account creation welcome email
 */
export type AccountCreationTemplateData = { orgName: string; link: string };

export const AccountCreationTemplateData$zodSchema: z.ZodType<
  AccountCreationTemplateData
> = z.object({
  link: z.string(),
  orgName: z.string(),
}).describe("Template data for organization account creation welcome email");
