/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ActivateOAuthAppResponse,
  ActivateOAuthAppResponse$zodSchema,
} from "./activateoauthappresponse.js";
import {
  ApplicationJsonErrorResponse,
  ApplicationJsonErrorResponse$zodSchema,
} from "./applicationjsonerrorresponse.js";
import {
  OAuthClientManagementRateLimitError,
  OAuthClientManagementRateLimitError$zodSchema,
} from "./oauthclientmanagementratelimiterror.js";

export type ActivateOAuthAppRequest = { appId: string };

export const ActivateOAuthAppRequest$zodSchema: z.ZodType<
  ActivateOAuthAppRequest
> = z.object({
  appId: z.string().describe("OAuth app ID"),
});

export type ActivateOAuthAppResponseResponse =
  | ActivateOAuthAppResponse
  | ApplicationJsonErrorResponse
  | OAuthClientManagementRateLimitError;

export const ActivateOAuthAppResponseResponse$zodSchema: z.ZodType<
  ActivateOAuthAppResponseResponse
> = z.union([
  ActivateOAuthAppResponse$zodSchema,
  ApplicationJsonErrorResponse$zodSchema,
  OAuthClientManagementRateLimitError$zodSchema,
]);
