/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddMessageRequest,
  AddMessageRequest$zodSchema,
} from "./addmessagerequest.js";

export type AddAgentMessageRequest = {
  agentKey: string;
  conversationId: string;
  body: AddMessageRequest;
};

export const AddAgentMessageRequest$zodSchema: z.ZodType<
  AddAgentMessageRequest
> = z.object({
  agentKey: z.string(),
  body: AddMessageRequest$zodSchema,
  conversationId: z.string(),
});
