/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Archive counts and bounds for the current result page returned by
 *
 * @remarks
 * `GET /agents/{agentKey}/conversations/show/archives`.
 */
export type AgentArchivedConversationSummary = {
  totalArchived?: number | undefined;
  oldestArchive?: string | undefined;
  newestArchive?: string | undefined;
};

export const AgentArchivedConversationSummary$zodSchema: z.ZodType<
  AgentArchivedConversationSummary
> = z.object({
  newestArchive: z.iso.datetime({ offset: true }).optional(),
  oldestArchive: z.iso.datetime({ offset: true }).optional(),
  totalArchived: z.int().optional(),
}).describe(
  "Archive counts and bounds for the current result page returned by\n`GET /agents/{agentKey}/conversations/show/archives`.\n",
);
