/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AgentCreateKnowledge,
  AgentCreateKnowledge$zodSchema,
} from "./agentcreateknowledge.js";
import {
  AgentCreateModelEntryUnion,
  AgentCreateModelEntryUnion$zodSchema,
} from "./agentcreatemodelentryunion.js";
import {
  AgentCreateToolset,
  AgentCreateToolset$zodSchema,
} from "./agentcreatetoolset.js";
import {
  AgentCreateWebSearchUnion,
  AgentCreateWebSearchUnion$zodSchema,
} from "./agentcreatewebsearchunion.js";

export type AgentCreateRequest = {
  name: string;
  description?: string | undefined;
  startMessage?: string | undefined;
  systemPrompt?: string | undefined;
  instructions?: string | undefined;
  models: Array<AgentCreateModelEntryUnion>;
  tags?: Array<string> | undefined;
  shareWithOrg?: boolean | undefined;
  isServiceAccount?: boolean | undefined;
  toolsets?: Array<AgentCreateToolset> | undefined;
  knowledge?: Array<AgentCreateKnowledge> | undefined;
  webSearch?: AgentCreateWebSearchUnion | null | undefined;
};

export const AgentCreateRequest$zodSchema: z.ZodType<AgentCreateRequest> = z
  .object({
    description: z.string().optional(),
    instructions: z.string().optional(),
    isServiceAccount: z.boolean().default(false),
    knowledge: z.array(AgentCreateKnowledge$zodSchema).optional(),
    models: z.array(AgentCreateModelEntryUnion$zodSchema),
    name: z.string(),
    shareWithOrg: z.boolean().default(false),
    startMessage: z.string().optional(),
    systemPrompt: z.string().optional(),
    tags: z.array(z.string()).optional(),
    toolsets: z.array(AgentCreateToolset$zodSchema).optional(),
    webSearch: AgentCreateWebSearchUnion$zodSchema.nullable().optional(),
  });
