/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Web-search provider attachment for this agent, or `null` when none is attached.
 *
 * @remarks
 *
 * For `GET /agents`, the response formatter always emits `provider`.
 * It may also emit `providerKey` and `providerLabel` when those values
 * were present on the stored attachment. It does not emit `iconPath`
 * on this response path.
 */
export type AgentListItemWebSearch = {
  provider?: string | undefined;
  providerKey?: string | undefined;
  providerLabel?: string | undefined;
};

export const AgentListItemWebSearch$zodSchema: z.ZodType<
  AgentListItemWebSearch
> = z.object({
  provider: z.string().optional(),
  providerKey: z.string().optional(),
  providerLabel: z.string().optional(),
}).describe(
  "Web-search provider attachment for this agent, or `null` when none is attached.\n\nFor `GET /agents`, the response formatter always emits `provider`.\nIt may also emit `providerKey` and `providerLabel` when those values\nwere present on the stored attachment. It does not emit `iconPath`\non this response path.\n",
);

/**
 * Agent projection returned by `GET /agents`.
 *
 * @remarks
 *
 * This is the list-view envelope item emitted by the Python backend and
 * forwarded by the Node gateway. It is not the full detail projection
 * used by `GET /agents/{agentKey}`.
 */
export type AgentListItem = {
  _id: string;
  _key: string;
  _rev?: string | undefined;
  createdAtTimestamp: number;
  createdBy: string;
  description?: string | null | undefined;
  instructions?: string | null | undefined;
  isActive: boolean;
  isDeleted: boolean;
  isServiceAccount: boolean;
  models: Array<string>;
  name: string;
  startMessage?: string | null | undefined;
  systemPrompt?: string | null | undefined;
  tags: Array<string>;
  updatedAtTimestamp: number;
  updatedBy?: string | null | undefined;
  webSearch?: AgentListItemWebSearch | null | undefined;
  shareWithOrg: boolean;
  can_view: boolean;
  can_share: boolean;
  can_edit: boolean;
  can_delete: boolean;
  user_role: string;
  access_type: string;
};

export const AgentListItem$zodSchema: z.ZodType<AgentListItem> = z.object({
  _id: z.string(),
  _key: z.string(),
  _rev: z.string().optional(),
  access_type: z.string(),
  can_delete: z.boolean(),
  can_edit: z.boolean(),
  can_share: z.boolean(),
  can_view: z.boolean(),
  createdAtTimestamp: z.int(),
  createdBy: z.string(),
  description: z.string().nullable().optional(),
  instructions: z.string().nullable().optional(),
  isActive: z.boolean(),
  isDeleted: z.boolean(),
  isServiceAccount: z.boolean(),
  models: z.array(z.string()),
  name: z.string(),
  shareWithOrg: z.boolean(),
  startMessage: z.string().nullable().optional(),
  systemPrompt: z.string().nullable().optional(),
  tags: z.array(z.string()),
  updatedAtTimestamp: z.int(),
  updatedBy: z.string().nullable().optional(),
  user_role: z.string(),
  webSearch: z.lazy(() => AgentListItemWebSearch$zodSchema).nullable()
    .optional(),
}).describe(
  "Agent projection returned by `GET /agents`.\n\nThis is the list-view envelope item emitted by the Python backend and\nforwarded by the Node gateway. It is not the full detail projection\nused by `GET /agents/{agentKey}`.\n",
);
