/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { RequestMeta, RequestMeta$zodSchema } from "./requestmeta.js";
import {
  StoredAgentConversation,
  StoredAgentConversation$zodSchema,
} from "./storedagentconversation.js";

export type AgentConversationTitleUpdateResponse = {
  conversation: StoredAgentConversation;
  meta: RequestMeta;
};

export const AgentConversationTitleUpdateResponse$zodSchema: z.ZodType<
  AgentConversationTitleUpdateResponse
> = z.object({
  conversation: StoredAgentConversation$zodSchema,
  meta: RequestMeta$zodSchema,
});
