/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AgentCreateWebSearch = {
  provider: string;
  providerKey?: string | undefined;
  providerLabel?: string | undefined;
  iconPath?: string | undefined;
};

export const AgentCreateWebSearch$zodSchema: z.ZodType<AgentCreateWebSearch> = z
  .object({
    iconPath: z.string().optional(),
    provider: z.string(),
    providerKey: z.string().optional(),
    providerLabel: z.string().optional(),
  });

/**
 * Accepted web-search attachment for `POST /agents/create`.
 *
 * @remarks
 * The gateway accepts either a provider string or an object with at least
 * a `provider` field.
 */
export type AgentCreateWebSearchUnion = AgentCreateWebSearch | string;

export const AgentCreateWebSearchUnion$zodSchema: z.ZodType<
  AgentCreateWebSearchUnion
> = z.union([
  z.lazy(() => AgentCreateWebSearch$zodSchema),
  z.string(),
]).describe(
  "Accepted web-search attachment for `POST /agents/create`.\nThe gateway accepts either a provider string or an object with at least\na `provider` field.\n",
);
