/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApplicationJsonErrorResponseError = {
  code: string;
  message: string;
  metadata?: { [k: string]: any } | undefined;
};

export const ApplicationJsonErrorResponseError$zodSchema: z.ZodType<
  ApplicationJsonErrorResponseError
> = z.object({
  code: z.string(),
  message: z.string(),
  metadata: z.record(z.string(), z.any()).optional(),
});

/**
 * Standard JSON error envelope from `ErrorMiddleware` for `BaseError` subclasses (`error.middleware.ts`).
 *
 * @remarks
 * Returned for most API 4xx errors (unauthorized, forbidden, not found, validation failures, etc.).
 */
export type ApplicationJsonErrorResponse = {
  error: ApplicationJsonErrorResponseError;
};

export const ApplicationJsonErrorResponse$zodSchema: z.ZodType<
  ApplicationJsonErrorResponse
> = z.object({
  error: z.lazy(() => ApplicationJsonErrorResponseError$zodSchema),
}).describe(
  "Standard JSON error envelope from `ErrorMiddleware` for `BaseError` subclasses (`error.middleware.ts`).\nReturned for most API 4xx errors (unauthorized, forbidden, not found, validation failures, etc.).\n",
);
