/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AuthenticateFinalResponse,
  AuthenticateFinalResponse$zodSchema,
} from "./authenticatefinalresponse.js";
import {
  AuthenticateMultiStepResponse,
  AuthenticateMultiStepResponse$zodSchema,
} from "./authenticatemultistepresponse.js";

/**
 * Either the next step in a multi-factor flow (`status`, `nextStep`, `allowedMethods`, `authProviders`)
 *
 * @remarks
 * or final tokens (`message`, `accessToken`, `refreshToken`).
 */
export type AuthenticateResponse =
  | AuthenticateMultiStepResponse
  | AuthenticateFinalResponse;

export const AuthenticateResponse$zodSchema: z.ZodType<AuthenticateResponse> = z
  .union([
    AuthenticateMultiStepResponse$zodSchema,
    AuthenticateFinalResponse$zodSchema,
  ]).describe(
    "Either the next step in a multi-factor flow (`status`, `nextStep`, `allowedMethods`, `authProviders`)\nor final tokens (`message`, `accessToken`, `refreshToken`).\n",
  );
