/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AuthenticateToolsetInstanceRequest = {
  instanceId: string;
  body: { [k: string]: any };
};

export const AuthenticateToolsetInstanceRequest$zodSchema: z.ZodType<
  AuthenticateToolsetInstanceRequest
> = z.object({
  body: z.record(z.string(), z.any()),
  instanceId: z.string(),
});
