/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AuthenticateRequest,
  AuthenticateRequest$zodSchema,
} from "./authenticaterequest.js";
import {
  AuthenticateResponse,
  AuthenticateResponse$zodSchema,
} from "./authenticateresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type AuthenticateRequestRequest = {
  xSessionToken: string;
  body: AuthenticateRequest;
};

export const AuthenticateRequestRequest$zodSchema: z.ZodType<
  AuthenticateRequestRequest
> = z.object({
  body: AuthenticateRequest$zodSchema,
  xSessionToken: z.string().describe(
    "Session token received from `/initAuth` endpoint",
  ),
});

export type AuthenticateResponseResponse = ErrorResponse | AuthenticateResponse;

export const AuthenticateResponseResponse$zodSchema: z.ZodType<
  AuthenticateResponseResponse
> = z.union([
  ErrorResponse$zodSchema,
  AuthenticateResponse$zodSchema,
]);
