/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AvailableModel, AvailableModel$zodSchema } from "./availablemodel.js";

export const AvailableModelsResponseStatus = {
  Success: "success",
  Error: "error",
} as const;
export type AvailableModelsResponseStatus = ClosedEnum<
  typeof AvailableModelsResponseStatus
>;

export const AvailableModelsResponseStatus$zodSchema = z.enum([
  "success",
  "error",
]);

/**
 * Response from `GET /configurationManager/ai-models/available/{modelType}`.
 */
export type AvailableModelsResponse = {
  status: AvailableModelsResponseStatus;
  message?: string | undefined;
  models: Array<AvailableModel>;
};

export const AvailableModelsResponse$zodSchema: z.ZodType<
  AvailableModelsResponse
> = z.object({
  message: z.string().optional(),
  models: z.array(AvailableModel$zodSchema),
  status: AvailableModelsResponseStatus$zodSchema,
}).describe(
  "Response from `GET /configurationManager/ai-models/available/{modelType}`.",
);
