/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CheckPasswordStatusSecurity = { scopedToken: string };

export const CheckPasswordStatusSecurity$zodSchema: z.ZodType<
  CheckPasswordStatusSecurity
> = z.object({
  scopedToken: z.string().describe(
    "Scoped JWT token for service-to-service authentication.\nFormat: \"Bearer {scoped_token}\"\nRequired scopes vary by endpoint.\n",
  ),
});

/**
 * Password status retrieved
 */
export type CheckPasswordStatusResponse = { hasPassword?: boolean | undefined };

export const CheckPasswordStatusResponse$zodSchema: z.ZodType<
  CheckPasswordStatusResponse
> = z.object({
  hasPassword: z.boolean().optional(),
}).describe("Password status retrieved");
