/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Message, Message$zodSchema } from "./message.js";

/**
 * Current status of the conversation (mixed-case values, source of
 *
 * @remarks
 * truth is `CONVERSATION_STATUS` in
 * `enterprise_search/constants/constants.ts`):
 * <ul>
 * <li><code>Inprogress</code> — request received, AI is generating a response</li>
 * <li><code>Complete</code> — response ready</li>
 * <li><code>Failed</code> — AI backend or downstream error; see <code>failReason</code></li>
 * <li><code>None</code> — placeholder used for empty/legacy conversations</li>
 * </ul>
 */
export const ConversationStatus = {
  Complete: "Complete",
  Failed: "Failed",
  Inprogress: "Inprogress",
  None: "None",
} as const;
/**
 * Current status of the conversation (mixed-case values, source of
 *
 * @remarks
 * truth is `CONVERSATION_STATUS` in
 * `enterprise_search/constants/constants.ts`):
 * <ul>
 * <li><code>Inprogress</code> — request received, AI is generating a response</li>
 * <li><code>Complete</code> — response ready</li>
 * <li><code>Failed</code> — AI backend or downstream error; see <code>failReason</code></li>
 * <li><code>None</code> — placeholder used for empty/legacy conversations</li>
 * </ul>
 */
export type ConversationStatus = ClosedEnum<typeof ConversationStatus>;

export const ConversationStatus$zodSchema = z.enum([
  "Complete",
  "Failed",
  "Inprogress",
  "None",
]).describe(
  "Current status of the conversation (mixed-case values, source of\ntruth is `CONVERSATION_STATUS` in\n`enterprise_search/constants/constants.ts`):\n<ul>\n<li><code>Inprogress</code> — request received, AI is generating a response</li>\n<li><code>Complete</code> — response ready</li>\n<li><code>Failed</code> — AI backend or downstream error; see <code>failReason</code></li>\n<li><code>None</code> — placeholder used for empty/legacy conversations</li>\n</ul>\n",
);

/**
 * AI model configuration used
 */
export type ModelInfo = {
  modelKey?: string | undefined;
  modelName?: string | undefined;
  modelFriendlyName?: string | undefined;
  modelProvider?: string | undefined;
  chatMode?: string | undefined;
};

export const ModelInfo$zodSchema: z.ZodType<ModelInfo> = z.object({
  chatMode: z.string().optional(),
  modelFriendlyName: z.string().optional(),
  modelKey: z.string().optional(),
  modelName: z.string().optional(),
  modelProvider: z.string().optional(),
}).describe("AI model configuration used");

export const AccessLevel = {
  Read: "read",
  Write: "write",
} as const;
export type AccessLevel = ClosedEnum<typeof AccessLevel>;

export const AccessLevel$zodSchema = z.enum([
  "read",
  "write",
]);

export type SharedWith = {
  userId?: string | undefined;
  accessLevel?: AccessLevel | undefined;
};

export const SharedWith$zodSchema: z.ZodType<SharedWith> = z.object({
  accessLevel: AccessLevel$zodSchema.optional(),
  userId: z.string().optional(),
});

/**
 * A conversation represents a chat session between a user and the AI.
 *
 * @remarks
 * Conversations maintain context across multiple messages and can be
 * shared, archived, and organized.
 */
export type Conversation = {
  _id?: string | undefined;
  userId?: string | undefined;
  orgId?: string | undefined;
  title?: string | undefined;
  initiator?: string | undefined;
  messages?: Array<Message> | undefined;
  status?: ConversationStatus | undefined;
  failReason?: string | undefined;
  modelInfo?: ModelInfo | undefined;
  isShared?: boolean | undefined;
  shareLink?: string | undefined;
  sharedWith?: Array<SharedWith> | undefined;
  isArchived?: boolean | undefined;
  archivedBy?: string | undefined;
  lastActivityAt?: number | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const Conversation$zodSchema: z.ZodType<Conversation> = z.object({
  _id: z.string().optional(),
  archivedBy: z.string().optional(),
  createdAt: z.iso.datetime({ offset: true }).optional(),
  failReason: z.string().optional(),
  initiator: z.string().optional(),
  isArchived: z.boolean().default(false),
  isShared: z.boolean().default(false),
  lastActivityAt: z.int().optional(),
  messages: z.array(Message$zodSchema).optional(),
  modelInfo: z.lazy(() => ModelInfo$zodSchema).optional(),
  orgId: z.string().optional(),
  shareLink: z.string().optional(),
  sharedWith: z.array(z.lazy(() => SharedWith$zodSchema)).optional(),
  status: ConversationStatus$zodSchema.optional(),
  title: z.string().optional(),
  updatedAt: z.iso.datetime({ offset: true }).optional(),
  userId: z.string().optional(),
}).describe(
  "A conversation represents a chat session between a user and the AI.\nConversations maintain context across multiple messages and can be\nshared, archived, and organized.\n",
);
