/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request payload
 */
export type CreatePlaceholderDocumentRequest = {};

export const CreatePlaceholderDocumentRequest$zodSchema: z.ZodType<
  CreatePlaceholderDocumentRequest
> = z.object({}).describe("Request payload");

/**
 * Placeholder document created successfully
 */
export type CreatePlaceholderDocumentResponse = {
  message?: string | undefined;
};

export const CreatePlaceholderDocumentResponse$zodSchema: z.ZodType<
  CreatePlaceholderDocumentResponse
> = z.object({
  message: z.string().optional(),
}).describe("Placeholder document created successfully");
