/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteSearchRequest = { searchId: string };

export const DeleteSearchRequest$zodSchema: z.ZodType<DeleteSearchRequest> = z
  .object({
    searchId: z.string(),
  });
