/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Logo deleted successfully
 */
export type DeleteOrganizationLogoResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

export const DeleteOrganizationLogoResponse$zodSchema: z.ZodType<
  DeleteOrganizationLogoResponse
> = z.object({
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Logo deleted successfully");
