/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Must be "DELETE" to confirm deletion
 */
export const Confirm = {
  Delete: "DELETE",
} as const;
/**
 * Must be "DELETE" to confirm deletion
 */
export type Confirm = ClosedEnum<typeof Confirm>;

export const Confirm$zodSchema = z.enum([
  "DELETE",
]).describe("Must be \"DELETE\" to confirm deletion");

export type DeleteOrganizationRequest = { confirm: Confirm };

export const DeleteOrganizationRequest$zodSchema: z.ZodType<
  DeleteOrganizationRequest
> = z.object({
  confirm: Confirm$zodSchema,
});

/**
 * Organization deleted successfully
 */
export type DeleteOrganizationResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

export const DeleteOrganizationResponse$zodSchema: z.ZodType<
  DeleteOrganizationResponse
> = z.object({
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Organization deleted successfully");
