/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteSearchByIdRequest = { searchId: string };

export const DeleteSearchByIdRequest$zodSchema: z.ZodType<
  DeleteSearchByIdRequest
> = z.object({
  searchId: z.string().describe("Unique search identifier"),
});

/**
 * Search deleted successfully
 */
export type DeleteSearchByIdResponse = { message?: string | undefined };

export const DeleteSearchByIdResponse$zodSchema: z.ZodType<
  DeleteSearchByIdResponse
> = z.object({
  message: z.string().optional(),
}).describe("Search deleted successfully");
