/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteFolderRequest = { kbId: string; folderId: string };

export const DeleteFolderRequest$zodSchema: z.ZodType<DeleteFolderRequest> = z
  .object({
    folderId: z.string(),
    kbId: z.string(),
  });
