/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AgentDeleteResponse,
  AgentDeleteResponse$zodSchema,
} from "./agentdeleteresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type DeleteAgentRequest = { agentKey: string };

export const DeleteAgentRequest$zodSchema: z.ZodType<DeleteAgentRequest> = z
  .object({
    agentKey: z.string().describe(
      "Unique agent identifier (gateway Zod requires non-empty string).",
    ),
  });

export type DeleteAgentResponse = AgentDeleteResponse | ErrorResponse;

export const DeleteAgentResponse$zodSchema: z.ZodType<DeleteAgentResponse> = z
  .union([
    AgentDeleteResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
