/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteDocumentByIdRequest = { documentId: string };

export const DeleteDocumentByIdRequest$zodSchema: z.ZodType<
  DeleteDocumentByIdRequest
> = z.object({
  documentId: z.string(),
});

/**
 * Document deleted successfully
 */
export type DeleteDocumentByIdResponse = { message?: string | undefined };

export const DeleteDocumentByIdResponse$zodSchema: z.ZodType<
  DeleteDocumentByIdResponse
> = z.object({
  message: z.string().optional(),
}).describe("Document deleted successfully");
