/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const DoclingParsePdfOpServerList = [
  /**
   * Docling Service (Internal)
   */
  "http://localhost:8081",
] as const;

/**
 * Request payload
 */
export type DoclingParsePdfRequest = {
  record_name: string;
  pdf_binary: string;
};

export const DoclingParsePdfRequest$zodSchema: z.ZodType<
  DoclingParsePdfRequest
> = z.object({
  pdf_binary: z.string(),
  record_name: z.string(),
}).describe("Request payload");

/**
 * PDF parsed successfully
 */
export type DoclingParsePdfResponse = {
  success?: boolean | undefined;
  parse_result?: string | undefined;
};

export const DoclingParsePdfResponse$zodSchema: z.ZodType<
  DoclingParsePdfResponse
> = z.object({
  parse_result: z.string().optional(),
  success: z.boolean().optional(),
}).describe("PDF parsed successfully");
