/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DocumentVersion,
  DocumentVersion$zodSchema,
} from "./documentversion.js";

/**
 * Default permission level for shared access
 */
export const Permissions = {
  Owner: "owner",
  Editor: "editor",
  Commentator: "commentator",
  Readonly: "readonly",
} as const;
/**
 * Default permission level for shared access
 */
export type Permissions = ClosedEnum<typeof Permissions>;

export const Permissions$zodSchema = z.enum([
  "owner",
  "editor",
  "commentator",
  "readonly",
]).describe("Default permission level for shared access");

export type CustomMetadatum = {
  key?: string | undefined;
  value?: string | undefined;
};

export const CustomMetadatum$zodSchema: z.ZodType<CustomMetadatum> = z.object({
  key: z.string().optional(),
  value: z.string().optional(),
});

/**
 * Storage backend where the file is stored
 */
export const StorageVendor = {
  S3: "s3",
  AzureBlob: "azureBlob",
  Local: "local",
} as const;
/**
 * Storage backend where the file is stored
 */
export type StorageVendor = ClosedEnum<typeof StorageVendor>;

export const StorageVendor$zodSchema = z.enum([
  "s3",
  "azureBlob",
  "local",
]).describe("Storage backend where the file is stored");

/**
 * S3-specific storage information (if storageVendor is s3)
 */
export type DocumentS3 = { url?: string | undefined };

export const DocumentS3$zodSchema: z.ZodType<DocumentS3> = z.object({
  url: z.string().optional(),
}).describe("S3-specific storage information (if storageVendor is s3)");

/**
 * Azure Blob-specific storage information (if storageVendor is azureBlob)
 */
export type DocumentAzureBlob = { url?: string | undefined };

export const DocumentAzureBlob$zodSchema: z.ZodType<DocumentAzureBlob> = z
  .object({
    url: z.string().optional(),
  }).describe(
    "Azure Blob-specific storage information (if storageVendor is azureBlob)",
  );

/**
 * Local storage-specific information (if storageVendor is local)
 */
export type DocumentLocal = {
  url?: string | undefined;
  localPath?: string | undefined;
};

export const DocumentLocal$zodSchema: z.ZodType<DocumentLocal> = z.object({
  localPath: z.string().optional(),
  url: z.string().optional(),
}).describe("Local storage-specific information (if storageVendor is local)");

/**
 * Represents a document stored in PipesHub storage system. Documents can be versioned to maintain complete history of changes. Supports multiple storage backends (S3, Azure Blob, Local).
 *
 * @remarks
 */
export type Document = {
  _id: string;
  documentName: string;
  alternateDocumentName?: string | undefined;
  documentPath?: string | undefined;
  isVersionedFile: boolean;
  orgId: string;
  permissions?: Permissions | undefined;
  initiatorUserId?: string | undefined;
  sizeInBytes?: number | undefined;
  mimeType?: string | undefined;
  extension?: string | undefined;
  mutationCount?: number | undefined;
  versionHistory?: Array<DocumentVersion> | undefined;
  customMetadata?: Array<CustomMetadatum> | undefined;
  tags?: Array<string> | undefined;
  storageVendor: StorageVendor;
  s3?: DocumentS3 | undefined;
  azureBlob?: DocumentAzureBlob | undefined;
  local?: DocumentLocal | undefined;
  createdAt?: number | undefined;
  updatedAt?: number | undefined;
  isDeleted?: boolean | undefined;
  deletedByUserId?: string | undefined;
};

export const Document$zodSchema: z.ZodType<Document> = z.object({
  _id: z.string(),
  alternateDocumentName: z.string().optional(),
  azureBlob: z.lazy(() => DocumentAzureBlob$zodSchema).optional(),
  createdAt: z.int().optional(),
  customMetadata: z.array(z.lazy(() => CustomMetadatum$zodSchema)).optional(),
  deletedByUserId: z.string().optional(),
  documentName: z.string(),
  documentPath: z.string().optional(),
  extension: z.string().optional(),
  initiatorUserId: z.string().optional(),
  isDeleted: z.boolean().default(false),
  isVersionedFile: z.boolean(),
  local: z.lazy(() => DocumentLocal$zodSchema).optional(),
  mimeType: z.string().optional(),
  mutationCount: z.int().optional(),
  orgId: z.string(),
  permissions: Permissions$zodSchema.optional(),
  s3: z.lazy(() => DocumentS3$zodSchema).optional(),
  sizeInBytes: z.int().optional(),
  storageVendor: StorageVendor$zodSchema,
  tags: z.array(z.string()).optional(),
  updatedAt: z.int().optional(),
  versionHistory: z.array(DocumentVersion$zodSchema).optional(),
}).describe(
  "Represents a document stored in PipesHub storage system. Documents can be versioned to maintain complete history of changes. Supports multiple storage backends (S3, Azure Blob, Local).\n",
);
