/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type GetAllUsersWithGroupsRequest = {
  includeDeleted?: boolean | undefined;
};

export const GetAllUsersWithGroupsRequest$zodSchema: z.ZodType<
  GetAllUsersWithGroupsRequest
> = z.object({
  includeDeleted: z.boolean().default(false).describe(
    "Include soft-deleted users (admin only)",
  ),
});

export const GetAllUsersWithGroupsType = {
  Admin: "admin",
  Standard: "standard",
  Everyone: "everyone",
  Custom: "custom",
} as const;
export type GetAllUsersWithGroupsType = ClosedEnum<
  typeof GetAllUsersWithGroupsType
>;

export const GetAllUsersWithGroupsType$zodSchema = z.enum([
  "admin",
  "standard",
  "everyone",
  "custom",
]);

export type GetAllUsersWithGroupsGroup = {
  _id?: string | undefined;
  name?: string | undefined;
  type?: GetAllUsersWithGroupsType | undefined;
};

export const GetAllUsersWithGroupsGroup$zodSchema: z.ZodType<
  GetAllUsersWithGroupsGroup
> = z.object({
  _id: z.string().optional(),
  name: z.string().optional(),
  type: GetAllUsersWithGroupsType$zodSchema.optional(),
});

export type GetAllUsersWithGroupsData = {
  _id?: string | undefined;
  userId?: string | undefined;
  orgId?: string | undefined;
  fullName?: string | undefined;
  hasLoggedIn?: boolean | undefined;
  groups?: Array<GetAllUsersWithGroupsGroup> | undefined;
};

export const GetAllUsersWithGroupsData$zodSchema: z.ZodType<
  GetAllUsersWithGroupsData
> = z.object({
  _id: z.string().optional(),
  fullName: z.string().optional(),
  groups: z.array(z.lazy(() => GetAllUsersWithGroupsGroup$zodSchema))
    .optional(),
  hasLoggedIn: z.boolean().optional(),
  orgId: z.string().optional(),
  userId: z.string().optional(),
});

/**
 * Users with groups retrieved successfully
 */
export type GetAllUsersWithGroupsResponse = {
  success?: boolean | undefined;
  data?: Array<GetAllUsersWithGroupsData> | undefined;
};

export const GetAllUsersWithGroupsResponse$zodSchema: z.ZodType<
  GetAllUsersWithGroupsResponse
> = z.object({
  data: z.array(z.lazy(() => GetAllUsersWithGroupsData$zodSchema)).optional(),
  success: z.boolean().optional(),
}).describe("Users with groups retrieved successfully");
