/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Conversation, Conversation$zodSchema } from "./conversation.js";

export type GetAllConversationsPagination = {
  page?: number | undefined;
  limit?: number | undefined;
  totalCount?: number | undefined;
  totalPages?: number | undefined;
  hasNextPage?: boolean | undefined;
  hasPrevPage?: boolean | undefined;
};

export const GetAllConversationsPagination$zodSchema: z.ZodType<
  GetAllConversationsPagination
> = z.object({
  hasNextPage: z.boolean().optional(),
  hasPrevPage: z.boolean().optional(),
  limit: z.int().optional(),
  page: z.int().optional(),
  totalCount: z.int().optional(),
  totalPages: z.int().optional(),
});

/**
 * Applied and available filters
 */
export type GetAllConversationsFilters = {};

export const GetAllConversationsFilters$zodSchema: z.ZodType<
  GetAllConversationsFilters
> = z.object({}).describe("Applied and available filters");

export type GetAllConversationsMeta = {
  requestId?: string | undefined;
  timestamp?: string | undefined;
  duration?: number | undefined;
};

export const GetAllConversationsMeta$zodSchema: z.ZodType<
  GetAllConversationsMeta
> = z.object({
  duration: z.int().optional(),
  requestId: z.string().optional(),
  timestamp: z.iso.datetime({ offset: true }).optional(),
});

/**
 * List of conversations
 */
export type GetAllConversationsResponse = {
  conversations?: Array<Conversation> | undefined;
  sharedWithMeConversations?: Array<Conversation> | undefined;
  pagination?: GetAllConversationsPagination | undefined;
  filters?: GetAllConversationsFilters | undefined;
  meta?: GetAllConversationsMeta | undefined;
};

export const GetAllConversationsResponse$zodSchema: z.ZodType<
  GetAllConversationsResponse
> = z.object({
  conversations: z.array(Conversation$zodSchema).optional(),
  filters: z.lazy(() => GetAllConversationsFilters$zodSchema).optional(),
  meta: z.lazy(() => GetAllConversationsMeta$zodSchema).optional(),
  pagination: z.lazy(() => GetAllConversationsPagination$zodSchema).optional(),
  sharedWithMeConversations: z.array(Conversation$zodSchema).optional(),
}).describe("List of conversations");
