/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GetAgentResponse,
  GetAgentResponse$zodSchema,
} from "./getagentresponse.js";

export type GetAgentRequest = { agentKey: string };

export const GetAgentRequest$zodSchema: z.ZodType<GetAgentRequest> = z.object({
  agentKey: z.string().describe("Unique agent identifier"),
});

export type GetAgentResponseResponse = GetAgentResponse | ErrorResponse;

export const GetAgentResponseResponse$zodSchema: z.ZodType<
  GetAgentResponseResponse
> = z.union([
  GetAgentResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
