/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetAgentConversationRequest = {
  agentKey: string;
  conversationId: string;
};

export const GetAgentConversationRequest$zodSchema: z.ZodType<
  GetAgentConversationRequest
> = z.object({
  agentKey: z.string(),
  conversationId: z.string(),
});
