/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthConfig, AuthConfig$zodSchema } from "./authconfig.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type GetAuthMethodsResponse = AuthConfig | ErrorResponse;

export const GetAuthMethodsResponse$zodSchema: z.ZodType<
  GetAuthMethodsResponse
> = z.union([
  AuthConfig$zodSchema,
  ErrorResponse$zodSchema,
]);
