/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetDocumentByIdRequest = { documentId: string };

export const GetDocumentByIdRequest$zodSchema: z.ZodType<
  GetDocumentByIdRequest
> = z.object({
  documentId: z.string(),
});

/**
 * Document details retrieved
 */
export type GetDocumentByIdResponse = {};

export const GetDocumentByIdResponse$zodSchema: z.ZodType<
  GetDocumentByIdResponse
> = z.object({}).describe("Document details retrieved");
