/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetGroupStatisticsData = {};

export const GetGroupStatisticsData$zodSchema: z.ZodType<
  GetGroupStatisticsData
> = z.object({});

/**
 * Group statistics retrieved successfully
 */
export type GetGroupStatisticsResponse = {
  success?: boolean | undefined;
  data?: Array<GetGroupStatisticsData> | undefined;
};

export const GetGroupStatisticsResponse$zodSchema: z.ZodType<
  GetGroupStatisticsResponse
> = z.object({
  data: z.array(z.lazy(() => GetGroupStatisticsData$zodSchema)).optional(),
  success: z.boolean().optional(),
}).describe("Group statistics retrieved successfully");
