/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Google Workspace OAuth config retrieved
 */
export type GetGoogleWorkspaceOauthConfigResponse = {
  clientId: string;
  clientSecret: string;
};

export const GetGoogleWorkspaceOauthConfigResponse$zodSchema: z.ZodType<
  GetGoogleWorkspaceOauthConfigResponse
> = z.object({
  clientId: z.string(),
  clientSecret: z.string(),
}).describe("Google Workspace OAuth config retrieved");
