/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  KnowledgeHubNodesResponse,
  KnowledgeHubNodesResponse$zodSchema,
} from "./knowledgehubnodesresponse.js";

/**
 * Type of the parent node whose children to retrieve.
 *
 * @remarks
 *
 * Must be one of: `app`, `recordGroup`, `folder`, `record`.
 * Any other value returns a 400 error.
 */
export const ParentType = {
  App: "app",
  RecordGroup: "recordGroup",
  Folder: "folder",
  Record: "record",
} as const;
/**
 * Type of the parent node whose children to retrieve.
 *
 * @remarks
 *
 * Must be one of: `app`, `recordGroup`, `folder`, `record`.
 * Any other value returns a 400 error.
 */
export type ParentType = ClosedEnum<typeof ParentType>;

export const ParentType$zodSchema = z.enum([
  "app",
  "recordGroup",
  "folder",
  "record",
]).describe(
  "Type of the parent node whose children to retrieve.\n\nMust be one of: `app`, `recordGroup`, `folder`, `record`.\nAny other value returns a 400 error.\n",
);

/**
 * Field to sort results by. Omitted → default `updatedAt`.
 *
 * @remarks
 * Unknown value → silently falls back to `name`.
 */
export const GetKnowledgeHubChildNodesSortBy = {
  Name: "name",
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  Size: "size",
  Type: "type",
} as const;
/**
 * Field to sort results by. Omitted → default `updatedAt`.
 *
 * @remarks
 * Unknown value → silently falls back to `name`.
 */
export type GetKnowledgeHubChildNodesSortBy = ClosedEnum<
  typeof GetKnowledgeHubChildNodesSortBy
>;

export const GetKnowledgeHubChildNodesSortBy$zodSchema = z.enum([
  "name",
  "createdAt",
  "updatedAt",
  "size",
  "type",
]).describe(
  "Field to sort results by. Omitted → default `updatedAt`.\nUnknown value → silently falls back to `name`.\n",
);

/**
 * Sort direction. Omitted → default `desc`.
 *
 * @remarks
 * Unknown value → silently falls back to `asc`.
 */
export const GetKnowledgeHubChildNodesSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort direction. Omitted → default `desc`.
 *
 * @remarks
 * Unknown value → silently falls back to `asc`.
 */
export type GetKnowledgeHubChildNodesSortOrder = ClosedEnum<
  typeof GetKnowledgeHubChildNodesSortOrder
>;

export const GetKnowledgeHubChildNodesSortOrder$zodSchema = z.enum([
  "asc",
  "desc",
]).describe(
  "Sort direction. Omitted → default `desc`.\nUnknown value → silently falls back to `asc`.\n",
);

export type GetKnowledgeHubChildNodesRequest = {
  parentType: ParentType;
  parentId: string;
  onlyContainers?: boolean | undefined;
  page?: number | undefined;
  limit?: number | undefined;
  sortBy?: GetKnowledgeHubChildNodesSortBy | undefined;
  sortOrder?: GetKnowledgeHubChildNodesSortOrder | undefined;
  q?: string | undefined;
  nodeTypes?: string | undefined;
  recordTypes?: string | undefined;
  origins?: string | undefined;
  connectorIds?: string | undefined;
  indexingStatus?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  size?: string | undefined;
  include?: string | undefined;
};

export const GetKnowledgeHubChildNodesRequest$zodSchema: z.ZodType<
  GetKnowledgeHubChildNodesRequest
> = z.object({
  connectorIds: z.string().describe(
    "Comma-separated list of connector instance IDs (UUIDs) to filter by.\nMaximum 100 items. No enum validation — any string is accepted, but\nnon-existent IDs simply yield zero results.\n",
  ).optional(),
  createdAt: z.string().describe(
    "Created-date range filter. Format: `gte:<epochMs>,lte:<epochMs>`.\nBoth bounds are optional (you may send just `gte:...` or just\n`lte:...`). Timestamps must be in the range 0 to 9999999999999 and\n`gte` must be less than or equal to `lte` when both are present.\n",
  ).optional(),
  include: z.string().describe(
    "Comma-separated list of additional response sections to include.\nInvalid values are silently ignored. Maximum 100 items.\n\nValid values: `breadcrumbs`, `counts`, `availableFilters`, `permissions`\n",
  ).optional(),
  indexingStatus: z.string().describe(
    "Comma-separated list of indexing statuses to include. Invalid values\nare silently ignored. Maximum 100 items.\n\nValid values: `NOT_STARTED`, `PAUSED`, `IN_PROGRESS`, `COMPLETED`,\n`FAILED`, `FILE_TYPE_NOT_SUPPORTED`, `AUTO_INDEX_OFF`, `EMPTY`,\n`ENABLE_MULTIMODAL_MODELS`, `QUEUED`\n",
  ).optional(),
  limit: z.int().default(50).describe(
    "Maximum number of items to return per page.\n",
  ),
  nodeTypes: z.string().describe(
    "Comma-separated list of node types to include. Invalid values are\nsilently ignored. Maximum 100 items.\n\nValid values: `folder`, `app`, `recordGroup`, `record`\n",
  ).optional(),
  onlyContainers: z.boolean().default(false).describe(
    "When `true`, only nodes that have children are returned (useful for\nbuilding sidebar / tree navigation). Leaf nodes are excluded.\n",
  ),
  origins: z.string().describe(
    "Comma-separated list of origin types to include. Invalid values are\nsilently ignored. Maximum 100 items.\n\nValid values: `COLLECTION`, `CONNECTOR`\n",
  ).optional(),
  page: z.int().default(1).describe(
    "Page number (1-indexed). Combined with `limit` to paginate results.\n",
  ),
  parentId: z.string().describe(
    "Identifier of the parent node. Accepts two formats:\n- A standard UUID (e.g. `f3a4b5b6-5b6c-4e85-9097-3202cfe696fc`)\n- The Collection app sentinel `knowledgeBase_<orgId>`\n  (e.g. `knowledgeBase_org123`)\n\nAny value that does not match either format returns a 400 error.\n",
  ),
  parentType: ParentType$zodSchema,
  q: z.string().describe(
    "Full-text search query. Must be between 2 and 500 characters\n(inclusive). When provided, the endpoint searches across all\ndescendants of the parent node.\n",
  ).optional(),
  recordTypes: z.string().describe(
    "Comma-separated list of record types to include. Invalid values are\nsilently ignored. Maximum 100 items.\n\nValid values: `FILE`, `DRIVE`, `WEBPAGE`, `DATABASE`, `DATASOURCE`,\n`MESSAGE`, `MAIL`, `GROUP_MAIL`, `TICKET`, `COMMENT`,\n`INLINE_COMMENT`, `CONFLUENCE_PAGE`, `CONFLUENCE_BLOGPOST`,\n`SHAREPOINT_PAGE`, `SHAREPOINT_LIST`, `SHAREPOINT_LIST_ITEM`,\n`SHAREPOINT_DOCUMENT_LIBRARY`, `LINK`, `PROJECT`, `PULL_REQUEST`,\n`MEETING`, `PRODUCT`, `DEAL`, `CASE`, `TASK`, `ARTIFACT`,\n`CODE_FILE`, `SQL_TABLE`, `SQL_VIEW`, `OTHERS`\n",
  ).optional(),
  size: z.string().describe(
    "File-size range filter in bytes. Format: `gte:<bytes>,lte:<bytes>`.\nBoth bounds are optional. Values must be non-negative and at most\n1099511627776 (1 TB). `gte` must be less than or equal to `lte`\nwhen both are present.\n",
  ).optional(),
  sortBy: GetKnowledgeHubChildNodesSortBy$zodSchema.default("updatedAt"),
  sortOrder: GetKnowledgeHubChildNodesSortOrder$zodSchema.default("desc"),
  updatedAt: z.string().describe(
    "Updated-date range filter. Same format and constraints as `createdAt`.\n",
  ).optional(),
});

export const GetKnowledgeHubChildNodesCodeHTTPInternalServerError = {
  HttpInternalServerError: "HTTP_INTERNAL_SERVER_ERROR",
} as const;
export type GetKnowledgeHubChildNodesCodeHTTPInternalServerError = ClosedEnum<
  typeof GetKnowledgeHubChildNodesCodeHTTPInternalServerError
>;

export const GetKnowledgeHubChildNodesCodeHTTPInternalServerError$zodSchema = z
  .enum([
    "HTTP_INTERNAL_SERVER_ERROR",
  ]);

export type GetKnowledgeHubChildNodesErrorHTTPInternalServerError = {
  code: GetKnowledgeHubChildNodesCodeHTTPInternalServerError;
  message: string;
};

export const GetKnowledgeHubChildNodesErrorHTTPInternalServerError$zodSchema:
  z.ZodType<GetKnowledgeHubChildNodesErrorHTTPInternalServerError> = z.object({
    code: GetKnowledgeHubChildNodesCodeHTTPInternalServerError$zodSchema,
    message: z.string(),
  });

/**
 * An unexpected error occurred on the server.
 */
export type GetKnowledgeHubChildNodesInternalServerErrorResponseBody = {
  error: GetKnowledgeHubChildNodesErrorHTTPInternalServerError;
};

export const GetKnowledgeHubChildNodesInternalServerErrorResponseBody$zodSchema:
  z.ZodType<GetKnowledgeHubChildNodesInternalServerErrorResponseBody> = z
    .object({
      error: z.lazy(() =>
        GetKnowledgeHubChildNodesErrorHTTPInternalServerError$zodSchema
      ),
    }).describe("An unexpected error occurred on the server.");

export const GetKnowledgeHubChildNodesNotFoundCode = {
  HttpNotFound: "HTTP_NOT_FOUND",
} as const;
export type GetKnowledgeHubChildNodesNotFoundCode = ClosedEnum<
  typeof GetKnowledgeHubChildNodesNotFoundCode
>;

export const GetKnowledgeHubChildNodesNotFoundCode$zodSchema = z.enum([
  "HTTP_NOT_FOUND",
]);

export type GetKnowledgeHubChildNodesNotFoundError = {
  code: GetKnowledgeHubChildNodesNotFoundCode;
  message: string;
};

export const GetKnowledgeHubChildNodesNotFoundError$zodSchema: z.ZodType<
  GetKnowledgeHubChildNodesNotFoundError
> = z.object({
  code: GetKnowledgeHubChildNodesNotFoundCode$zodSchema,
  message: z.string(),
});

/**
 * Parent node not found.
 *
 * @remarks
 *
 * The `parentId` does not correspond to an existing node of the
 * specified `parentType`, or the node has been deleted.
 */
export type GetKnowledgeHubChildNodesNotFoundResponseBody = {
  error: GetKnowledgeHubChildNodesNotFoundError;
};

export const GetKnowledgeHubChildNodesNotFoundResponseBody$zodSchema: z.ZodType<
  GetKnowledgeHubChildNodesNotFoundResponseBody
> = z.object({
  error: z.lazy(() => GetKnowledgeHubChildNodesNotFoundError$zodSchema),
}).describe(
  "Parent node not found.\n\nThe `parentId` does not correspond to an existing node of the\nspecified `parentType`, or the node has been deleted.\n",
);

export const GetKnowledgeHubChildNodesForbiddenCode = {
  HttpForbidden: "HTTP_FORBIDDEN",
} as const;
export type GetKnowledgeHubChildNodesForbiddenCode = ClosedEnum<
  typeof GetKnowledgeHubChildNodesForbiddenCode
>;

export const GetKnowledgeHubChildNodesForbiddenCode$zodSchema = z.enum([
  "HTTP_FORBIDDEN",
]);

export type GetKnowledgeHubChildNodesErrorHTTPForbidden = {
  code: GetKnowledgeHubChildNodesForbiddenCode;
  message: string;
};

export const GetKnowledgeHubChildNodesErrorHTTPForbidden$zodSchema: z.ZodType<
  GetKnowledgeHubChildNodesErrorHTTPForbidden
> = z.object({
  code: GetKnowledgeHubChildNodesForbiddenCode$zodSchema,
  message: z.string(),
});

/**
 * Insufficient OAuth scope.
 *
 * @remarks
 *
 * Only applies to OAuth tokens. The token did not carry the `kb:read`
 * scope required by this endpoint. Regular (non-OAuth) JWT bearer
 * tokens are not subject to scope enforcement and will not receive
 * this error.
 */
export type GetKnowledgeHubChildNodesForbiddenResponseBody = {
  error: GetKnowledgeHubChildNodesErrorHTTPForbidden;
};

export const GetKnowledgeHubChildNodesForbiddenResponseBody$zodSchema:
  z.ZodType<GetKnowledgeHubChildNodesForbiddenResponseBody> = z.object({
    error: z.lazy(() => GetKnowledgeHubChildNodesErrorHTTPForbidden$zodSchema),
  }).describe(
    "Insufficient OAuth scope.\n\nOnly applies to OAuth tokens. The token did not carry the `kb:read`\nscope required by this endpoint. Regular (non-OAuth) JWT bearer\ntokens are not subject to scope enforcement and will not receive\nthis error.\n",
  );

export const GetKnowledgeHubChildNodesUnauthorizedCode = {
  HttpUnauthorized: "HTTP_UNAUTHORIZED",
} as const;
export type GetKnowledgeHubChildNodesUnauthorizedCode = ClosedEnum<
  typeof GetKnowledgeHubChildNodesUnauthorizedCode
>;

export const GetKnowledgeHubChildNodesUnauthorizedCode$zodSchema = z.enum([
  "HTTP_UNAUTHORIZED",
]);

export type GetKnowledgeHubChildNodesErrorHTTPUnauthorized = {
  code: GetKnowledgeHubChildNodesUnauthorizedCode;
  message: string;
};

export const GetKnowledgeHubChildNodesErrorHTTPUnauthorized$zodSchema:
  z.ZodType<GetKnowledgeHubChildNodesErrorHTTPUnauthorized> = z.object({
    code: GetKnowledgeHubChildNodesUnauthorizedCode$zodSchema,
    message: z.string(),
  });

/**
 * Missing or invalid authentication token.
 *
 * @remarks
 *
 * The bearer token was absent, expired, malformed, or could not be
 * verified by the auth middleware.
 */
export type GetKnowledgeHubChildNodesUnauthorizedResponseBody = {
  error: GetKnowledgeHubChildNodesErrorHTTPUnauthorized;
};

export const GetKnowledgeHubChildNodesUnauthorizedResponseBody$zodSchema:
  z.ZodType<GetKnowledgeHubChildNodesUnauthorizedResponseBody> = z.object({
    error: z.lazy(() =>
      GetKnowledgeHubChildNodesErrorHTTPUnauthorized$zodSchema
    ),
  }).describe(
    "Missing or invalid authentication token.\n\nThe bearer token was absent, expired, malformed, or could not be\nverified by the auth middleware.\n",
  );

export const GetKnowledgeHubChildNodesCodeHTTPBadRequest = {
  HttpBadRequest: "HTTP_BAD_REQUEST",
} as const;
export type GetKnowledgeHubChildNodesCodeHTTPBadRequest = ClosedEnum<
  typeof GetKnowledgeHubChildNodesCodeHTTPBadRequest
>;

export const GetKnowledgeHubChildNodesCodeHTTPBadRequest$zodSchema = z.enum([
  "HTTP_BAD_REQUEST",
]);

export type GetKnowledgeHubChildNodesErrorHTTPBadRequest = {
  code: GetKnowledgeHubChildNodesCodeHTTPBadRequest;
  message: string;
};

export const GetKnowledgeHubChildNodesErrorHTTPBadRequest$zodSchema: z.ZodType<
  GetKnowledgeHubChildNodesErrorHTTPBadRequest
> = z.object({
  code: GetKnowledgeHubChildNodesCodeHTTPBadRequest$zodSchema,
  message: z.string(),
});

/**
 * Invalid request parameters or path values. The backend's validation
 *
 * @remarks
 * message is returned verbatim in `error.message`. See the examples
 * below for the common triggers.
 */
export type GetKnowledgeHubChildNodesBadRequestResponseBody = {
  error: GetKnowledgeHubChildNodesErrorHTTPBadRequest;
};

export const GetKnowledgeHubChildNodesBadRequestResponseBody$zodSchema:
  z.ZodType<GetKnowledgeHubChildNodesBadRequestResponseBody> = z.object({
    error: z.lazy(() => GetKnowledgeHubChildNodesErrorHTTPBadRequest$zodSchema),
  }).describe(
    "Invalid request parameters or path values. The backend's validation\nmessage is returned verbatim in `error.message`. See the examples\nbelow for the common triggers.\n",
  );

export type GetKnowledgeHubChildNodesResponse =
  | KnowledgeHubNodesResponse
  | GetKnowledgeHubChildNodesBadRequestResponseBody
  | GetKnowledgeHubChildNodesUnauthorizedResponseBody
  | GetKnowledgeHubChildNodesForbiddenResponseBody
  | GetKnowledgeHubChildNodesNotFoundResponseBody
  | GetKnowledgeHubChildNodesInternalServerErrorResponseBody;

export const GetKnowledgeHubChildNodesResponse$zodSchema: z.ZodType<
  GetKnowledgeHubChildNodesResponse
> = z.union([
  KnowledgeHubNodesResponse$zodSchema,
  z.lazy(() => GetKnowledgeHubChildNodesBadRequestResponseBody$zodSchema),
  z.lazy(() => GetKnowledgeHubChildNodesUnauthorizedResponseBody$zodSchema),
  z.lazy(() => GetKnowledgeHubChildNodesForbiddenResponseBody$zodSchema),
  z.lazy(() => GetKnowledgeHubChildNodesNotFoundResponseBody$zodSchema),
  z.lazy(() =>
    GetKnowledgeHubChildNodesInternalServerErrorResponseBody$zodSchema
  ),
]);
