/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Sort order.
 */
export const SortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort order.
 */
export type SortOrder = ClosedEnum<typeof SortOrder>;

export const SortOrder$zodSchema = z.enum([
  "asc",
  "desc",
]).describe("Sort order.");

export type GetKnowledgeHubRootNodesRequest = {
  only_containers?: boolean | undefined;
  page?: number | undefined;
  limit?: number | undefined;
  sortBy?: string | undefined;
  sortOrder?: SortOrder | undefined;
  q?: string | undefined;
  nodeTypes?: string | undefined;
  recordTypes?: string | undefined;
  origins?: string | undefined;
  connectorIds?: string | undefined;
  indexingStatus?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  size?: string | undefined;
  flattened?: boolean | undefined;
  include?: string | undefined;
};

export const GetKnowledgeHubRootNodesRequest$zodSchema: z.ZodType<
  GetKnowledgeHubRootNodesRequest
> = z.object({
  connectorIds: z.string().describe(
    "Comma-separated connector instance ids to scope to.",
  ).optional(),
  createdAt: z.string().describe("Created date range as `gte:<ms>,lte:<ms>`.")
    .optional(),
  flattened: z.boolean().default(false).describe(
    "Return flattened view with all nested children.",
  ),
  include: z.string().describe(
    "Comma-separated includes — any of `breadcrumbs`, `counts`,\n`availableFilters`, `permissions`.\n",
  ).optional(),
  indexingStatus: z.string().describe("Comma-separated indexing statuses.")
    .optional(),
  limit: z.int().default(50).describe("Items per page."),
  nodeTypes: z.string().describe(
    "Comma-separated node types (`app`, `recordGroup`, `folder`, `record`).",
  ).optional(),
  only_containers: z.boolean().default(false).describe(
    "Only return nodes with children (for sidebar UIs).",
  ),
  origins: z.string().describe(
    "Comma-separated origins (`COLLECTION`, `CONNECTOR`).",
  ).optional(),
  page: z.int().default(1).describe("Page number (1-indexed)."),
  q: z.string().describe("Full-text search query against node names.")
    .optional(),
  recordTypes: z.string().describe("Comma-separated record types.").optional(),
  size: z.string().describe("Size range as `gte:<bytes>,lte:<bytes>`.")
    .optional(),
  sortBy: z.string().default("updatedAt").describe(
    "Sort field — one of `name`, `createdAt`, `updatedAt`, `size`, `type`.",
  ),
  sortOrder: SortOrder$zodSchema.default("desc"),
  updatedAt: z.string().describe("Updated date range as `gte:<ms>,lte:<ms>`.")
    .optional(),
});
