/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Folder, Folder$zodSchema } from "./folder.js";
import { RecordT, RecordT$zodSchema } from "./record.js";

export const GetKBChildrenSortOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetKBChildrenSortOrder = ClosedEnum<typeof GetKBChildrenSortOrder>;

export const GetKBChildrenSortOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type GetKBChildrenRequest = {
  kbId: string;
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
  recordTypes?: string | undefined;
  origins?: string | undefined;
  indexingStatus?: string | undefined;
  dateFrom?: number | undefined;
  dateTo?: number | undefined;
  sortBy?: string | undefined;
  sortOrder?: GetKBChildrenSortOrder | undefined;
};

export const GetKBChildrenRequest$zodSchema: z.ZodType<GetKBChildrenRequest> = z
  .object({
    dateFrom: z.int().describe("Start date filter (Unix timestamp)").optional(),
    dateTo: z.int().describe("End date filter (Unix timestamp)").optional(),
    indexingStatus: z.string().describe("Filter by indexing status").optional(),
    kbId: z.string().describe("Knowledge base ID"),
    limit: z.int().default(20),
    origins: z.string().describe("Filter by origin").optional(),
    page: z.int().default(1),
    recordTypes: z.string().describe("Filter by record types (comma-separated)")
      .optional(),
    search: z.string().describe("Search query for record names").optional(),
    sortBy: z.string().default("createdAtTimestamp"),
    sortOrder: GetKBChildrenSortOrder$zodSchema.default("desc"),
  });

export type GetKBChildrenContainer = {
  id?: string | undefined;
  name?: string | undefined;
  path?: string | undefined;
  type?: string | undefined;
  webUrl?: string | undefined;
  recordGroupId?: string | undefined;
};

export const GetKBChildrenContainer$zodSchema: z.ZodType<
  GetKBChildrenContainer
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  path: z.string().optional(),
  recordGroupId: z.string().optional(),
  type: z.string().optional(),
  webUrl: z.string().optional(),
});

export type GetKBChildrenCounts = {
  folders?: number | undefined;
  records?: number | undefined;
  totalItems?: number | undefined;
  totalFolders?: number | undefined;
  totalRecords?: number | undefined;
};

export const GetKBChildrenCounts$zodSchema: z.ZodType<GetKBChildrenCounts> = z
  .object({
    folders: z.int().optional(),
    records: z.int().optional(),
    totalFolders: z.int().optional(),
    totalItems: z.int().optional(),
    totalRecords: z.int().optional(),
  });

export type GetKBChildrenAvailableFilters = {};

export const GetKBChildrenAvailableFilters$zodSchema: z.ZodType<
  GetKBChildrenAvailableFilters
> = z.object({});

export type GetKBChildrenUserPermission = {
  role?: string | undefined;
  canUpload?: boolean | undefined;
  canCreateFolders?: boolean | undefined;
  canEdit?: boolean | undefined;
  canDelete?: boolean | undefined;
  canManagePermissions?: boolean | undefined;
};

export const GetKBChildrenUserPermission$zodSchema: z.ZodType<
  GetKBChildrenUserPermission
> = z.object({
  canCreateFolders: z.boolean().optional(),
  canDelete: z.boolean().optional(),
  canEdit: z.boolean().optional(),
  canManagePermissions: z.boolean().optional(),
  canUpload: z.boolean().optional(),
  role: z.string().optional(),
});

export type GetKBChildrenPagination = {
  page?: number | undefined;
  limit?: number | undefined;
  totalItems?: number | undefined;
  totalPages?: number | undefined;
  hasNext?: boolean | undefined;
  hasPrev?: boolean | undefined;
};

export const GetKBChildrenPagination$zodSchema: z.ZodType<
  GetKBChildrenPagination
> = z.object({
  hasNext: z.boolean().optional(),
  hasPrev: z.boolean().optional(),
  limit: z.int().optional(),
  page: z.int().optional(),
  totalItems: z.int().optional(),
  totalPages: z.int().optional(),
});

/**
 * Applied and available filters
 */
export type GetKBChildrenFilters = {};

export const GetKBChildrenFilters$zodSchema: z.ZodType<GetKBChildrenFilters> = z
  .object({}).describe("Applied and available filters");

/**
 * Successful operation
 */
export type GetKBChildrenResponse = {
  success?: boolean | undefined;
  container?: GetKBChildrenContainer | undefined;
  folders?: Array<Folder> | undefined;
  records?: Array<RecordT> | undefined;
  level?: number | undefined;
  totalCount?: number | undefined;
  counts?: GetKBChildrenCounts | undefined;
  availableFilters?: GetKBChildrenAvailableFilters | undefined;
  paginationMode?: string | undefined;
  userPermission?: GetKBChildrenUserPermission | undefined;
  pagination?: GetKBChildrenPagination | undefined;
  filters?: GetKBChildrenFilters | undefined;
};

export const GetKBChildrenResponse$zodSchema: z.ZodType<GetKBChildrenResponse> =
  z.object({
    availableFilters: z.lazy(() => GetKBChildrenAvailableFilters$zodSchema)
      .optional(),
    container: z.lazy(() => GetKBChildrenContainer$zodSchema).optional(),
    counts: z.lazy(() => GetKBChildrenCounts$zodSchema).optional(),
    filters: z.lazy(() => GetKBChildrenFilters$zodSchema).optional(),
    folders: z.array(Folder$zodSchema).optional(),
    level: z.int().optional(),
    pagination: z.lazy(() => GetKBChildrenPagination$zodSchema).optional(),
    paginationMode: z.string().optional(),
    records: z.array(RecordT$zodSchema).optional(),
    success: z.boolean().optional(),
    totalCount: z.int().optional(),
    userPermission: z.lazy(() => GetKBChildrenUserPermission$zodSchema)
      .optional(),
  }).describe("Successful operation");
