/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Queue statistics retrieved
 */
export type GetQueueStatsResponse = {};

export const GetQueueStatsResponse$zodSchema: z.ZodType<GetQueueStatsResponse> =
  z.object({}).describe("Queue statistics retrieved");
