/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Google authentication configuration
 */
export type GoogleAuthConfig = { clientId?: string | undefined };

export const GoogleAuthConfig$zodSchema: z.ZodType<GoogleAuthConfig> = z.object(
  {
    clientId: z.string().optional(),
  },
).describe("Google authentication configuration");
