/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Folder, Folder$zodSchema } from "./folder.js";

/**
 * User's role in this knowledge base
 */
export const UserRoleEnum = {
  Owner: "OWNER",
  Organizer: "ORGANIZER",
  Fileorganizer: "FILEORGANIZER",
  Writer: "WRITER",
  Commenter: "COMMENTER",
  Reader: "READER",
} as const;
/**
 * User's role in this knowledge base
 */
export type UserRoleEnum = ClosedEnum<typeof UserRoleEnum>;

export const UserRoleEnum$zodSchema = z.enum([
  "OWNER",
  "ORGANIZER",
  "FILEORGANIZER",
  "WRITER",
  "COMMENTER",
  "READER",
]).describe("User's role in this knowledge base");

export type KnowledgeBase = {
  id?: string | undefined;
  name: string;
  connectorId?: string | null | undefined;
  createdAtTimestamp?: number | undefined;
  updatedAtTimestamp?: number | undefined;
  createdBy?: string | undefined;
  userRole?: UserRoleEnum | undefined;
  folders?: Array<Folder> | undefined;
};

export const KnowledgeBase$zodSchema: z.ZodType<KnowledgeBase> = z.object({
  connectorId: z.string().nullable().optional(),
  createdAtTimestamp: z.int().optional(),
  createdBy: z.string().optional(),
  folders: z.array(Folder$zodSchema).optional(),
  id: z.string().optional(),
  name: z.string(),
  updatedAtTimestamp: z.int().optional(),
  userRole: UserRoleEnum$zodSchema.optional(),
});
