/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApplicationJsonErrorResponse,
  ApplicationJsonErrorResponse$zodSchema,
} from "./applicationjsonerrorresponse.js";
import {
  OAuthClientManagementRateLimitError,
  OAuthClientManagementRateLimitError$zodSchema,
} from "./oauthclientmanagementratelimiterror.js";
import {
  OAuthScopesGroupedResponse,
  OAuthScopesGroupedResponse$zodSchema,
} from "./oauthscopesgroupedresponse.js";

export type ListOAuthScopesResponse =
  | OAuthScopesGroupedResponse
  | ApplicationJsonErrorResponse
  | OAuthClientManagementRateLimitError;

export const ListOAuthScopesResponse$zodSchema: z.ZodType<
  ListOAuthScopesResponse
> = z.union([
  OAuthScopesGroupedResponse$zodSchema,
  ApplicationJsonErrorResponse$zodSchema,
  OAuthClientManagementRateLimitError$zodSchema,
]);
