/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ListAgentArchivedConversationsGroupedRequest = {
  agentPage?: number | undefined;
  agentLimit?: number | undefined;
};

export const ListAgentArchivedConversationsGroupedRequest$zodSchema: z.ZodType<
  ListAgentArchivedConversationsGroupedRequest
> = z.object({
  agentLimit: z.int().default(5),
  agentPage: z.int().default(1),
});
