/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConnectorInstance,
  ConnectorInstance$zodSchema,
} from "./connectorinstance.js";

/**
 * Inactive connectors retrieved
 */
export type ListInactiveConnectorsResponse = {
  success?: boolean | undefined;
  connectors?: Array<ConnectorInstance> | undefined;
};

export const ListInactiveConnectorsResponse$zodSchema: z.ZodType<
  ListInactiveConnectorsResponse
> = z.object({
  connectors: z.array(ConnectorInstance$zodSchema).optional(),
  success: z.boolean().optional(),
}).describe("Inactive connectors retrieved");
