/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MessageFeedbackAppendEntry,
  MessageFeedbackAppendEntry$zodSchema,
} from "./messagefeedbackappendentry.js";

export type Meta = { requestId: string; timestamp: string; duration: number };

export const Meta$zodSchema: z.ZodType<Meta> = z.object({
  duration: z.int(),
  requestId: z.string(),
  timestamp: z.iso.datetime({ offset: true }),
});

/**
 * Gateway response after appending feedback to a bot-response message.
 *
 * @remarks
 */
export type MessageFeedbackUpdateResponse = {
  conversationId: string;
  messageId: string;
  feedback: MessageFeedbackAppendEntry;
  meta: Meta;
};

export const MessageFeedbackUpdateResponse$zodSchema: z.ZodType<
  MessageFeedbackUpdateResponse
> = z.object({
  conversationId: z.string(),
  feedback: MessageFeedbackAppendEntry$zodSchema,
  messageId: z.string(),
  meta: z.lazy(() => Meta$zodSchema),
}).describe(
  "Gateway response after appending feedback to a bot-response message.\n",
);
