/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const MessageFeedbackSubmitRequestCategory = {
  IncorrectInformation: "incorrect_information",
  MissingInformation: "missing_information",
  IrrelevantInformation: "irrelevant_information",
  UnclearExplanation: "unclear_explanation",
  PoorCitations: "poor_citations",
  ExcellentAnswer: "excellent_answer",
  HelpfulCitations: "helpful_citations",
  WellExplained: "well_explained",
  Other: "other",
} as const;
export type MessageFeedbackSubmitRequestCategory = ClosedEnum<
  typeof MessageFeedbackSubmitRequestCategory
>;

export const MessageFeedbackSubmitRequestCategory$zodSchema = z.enum([
  "incorrect_information",
  "missing_information",
  "irrelevant_information",
  "unclear_explanation",
  "poor_citations",
  "excellent_answer",
  "helpful_citations",
  "well_explained",
  "other",
]);

/**
 * Free-text comments grouped by sentiment.
 */
export type MessageFeedbackSubmitRequestComments = {
  positive?: string | undefined;
  negative?: string | undefined;
};

export const MessageFeedbackSubmitRequestComments$zodSchema: z.ZodType<
  MessageFeedbackSubmitRequestComments
> = z.object({
  negative: z.string().optional(),
  positive: z.string().optional(),
}).describe("Free-text comments grouped by sentiment.");

/**
 * Gateway request body for submitting message feedback (Zod
 *
 * @remarks
 * `feedbackBodySchema`). All fields are optional; an empty object is
 * accepted. Matches the first-party chat UI payload shape.
 */
export type MessageFeedbackSubmitRequest = {
  isHelpful?: boolean | undefined;
  categories?: Array<MessageFeedbackSubmitRequestCategory> | undefined;
  comments?: MessageFeedbackSubmitRequestComments | undefined;
};

export const MessageFeedbackSubmitRequest$zodSchema: z.ZodType<
  MessageFeedbackSubmitRequest
> = z.object({
  categories: z.array(MessageFeedbackSubmitRequestCategory$zodSchema)
    .optional(),
  comments: z.lazy(() => MessageFeedbackSubmitRequestComments$zodSchema)
    .optional(),
  isHelpful: z.boolean().optional(),
}).describe(
  "Gateway request body for submitting message feedback (Zod\n`feedbackBodySchema`). All fields are optional; an empty object is\naccepted. Matches the first-party chat UI payload shape.\n",
);
