/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request payload
 */
export type MoveRecordRequestBody = {};

export const MoveRecordRequestBody$zodSchema: z.ZodType<MoveRecordRequestBody> =
  z.object({}).describe("Request payload");

export type MoveRecordRequest = {
  kbId: string;
  recordId: string;
  body: MoveRecordRequestBody;
};

export const MoveRecordRequest$zodSchema: z.ZodType<MoveRecordRequest> = z
  .object({
    body: z.lazy(() => MoveRecordRequestBody$zodSchema),
    kbId: z.string(),
    recordId: z.string(),
  });

/**
 * Record moved successfully
 */
export type MoveRecordResponse = { message?: string | undefined };

export const MoveRecordResponse$zodSchema: z.ZodType<MoveRecordResponse> = z
  .object({
    message: z.string().optional(),
  }).describe("Record moved successfully");
