/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  OAuthClientManagementRateLimitError,
  OAuthClientManagementRateLimitError$zodSchema,
} from "./oauthclientmanagementratelimiterror.js";
import {
  OAuthErrorResponse,
  OAuthErrorResponse$zodSchema,
} from "./oautherrorresponse.js";

export type OauthRevokeResponse =
  | OAuthErrorResponse
  | OAuthClientManagementRateLimitError;

export const OauthRevokeResponse$zodSchema: z.ZodType<OauthRevokeResponse> = z
  .union([
    OAuthErrorResponse$zodSchema,
    OAuthClientManagementRateLimitError$zodSchema,
  ]);
