/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  OAuthAppResponse,
  OAuthAppResponse$zodSchema,
} from "./oauthappresponse.js";

export type OAuthAppListResponsePagination = {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
};

export const OAuthAppListResponsePagination$zodSchema: z.ZodType<
  OAuthAppListResponsePagination
> = z.object({
  limit: z.int(),
  page: z.int(),
  total: z.int(),
  totalPages: z.int(),
});

/**
 * Paginated list of OAuth apps
 */
export type OAuthAppListResponse = {
  data: Array<OAuthAppResponse>;
  pagination: OAuthAppListResponsePagination;
};

export const OAuthAppListResponse$zodSchema: z.ZodType<OAuthAppListResponse> = z
  .object({
    data: z.array(OAuthAppResponse$zodSchema),
    pagination: z.lazy(() => OAuthAppListResponsePagination$zodSchema),
  }).describe("Paginated list of OAuth apps");
