/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Information about an OAuth scope
 */
export type OAuthScopeInfo = {
  name: string;
  description: string;
  category: string;
  requiresUserConsent: boolean;
};

export const OAuthScopeInfo$zodSchema: z.ZodType<OAuthScopeInfo> = z.object({
  category: z.string(),
  description: z.string(),
  name: z.string(),
  requiresUserConsent: z.boolean(),
}).describe("Information about an OAuth scope");
