/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Response from setting up organization auth configuration
 */
export type OrgAuthConfigSetupResponse = { message: string };

export const OrgAuthConfigSetupResponse$zodSchema: z.ZodType<
  OrgAuthConfigSetupResponse
> = z.object({
  message: z.string(),
}).describe("Response from setting up organization auth configuration");
