/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request payload
 */
export type RemoveUserFromTeamRequestBody = { userId?: string | undefined };

export const RemoveUserFromTeamRequestBody$zodSchema: z.ZodType<
  RemoveUserFromTeamRequestBody
> = z.object({
  userId: z.string().optional(),
}).describe("Request payload");

export type RemoveUserFromTeamRequest = {
  teamId: string;
  body: RemoveUserFromTeamRequestBody;
};

export const RemoveUserFromTeamRequest$zodSchema: z.ZodType<
  RemoveUserFromTeamRequest
> = z.object({
  body: z.lazy(() => RemoveUserFromTeamRequestBody$zodSchema),
  teamId: z.string(),
});

/**
 * User removed from team successfully
 */
export type RemoveUserFromTeamResponse = { message?: string | undefined };

export const RemoveUserFromTeamResponse$zodSchema: z.ZodType<
  RemoveUserFromTeamResponse
> = z.object({
  message: z.string().optional(),
}).describe("User removed from team successfully");
