/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Template data for password reset email
 */
export type ResetPasswordTemplateData = { name: string; link: string };

export const ResetPasswordTemplateData$zodSchema: z.ZodType<
  ResetPasswordTemplateData
> = z.object({
  link: z.string(),
  name: z.string(),
}).describe("Template data for password reset email");
