/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SearchRecordSummaryOrigin = {
  Upload: "UPLOAD",
  Connector: "CONNECTOR",
} as const;
export type SearchRecordSummaryOrigin = ClosedEnum<
  typeof SearchRecordSummaryOrigin
>;

export const SearchRecordSummaryOrigin$zodSchema = z.enum([
  "UPLOAD",
  "CONNECTOR",
]);

export const IndexingStatus = {
  NotStarted: "NOT_STARTED",
  InProgress: "IN_PROGRESS",
  Completed: "COMPLETED",
  Failed: "FAILED",
} as const;
export type IndexingStatus = ClosedEnum<typeof IndexingStatus>;

export const IndexingStatus$zodSchema = z.enum([
  "NOT_STARTED",
  "IN_PROGRESS",
  "COMPLETED",
  "FAILED",
]);

export const ExtractionStatus = {
  NotStarted: "NOT_STARTED",
  InProgress: "IN_PROGRESS",
  Completed: "COMPLETED",
  Failed: "FAILED",
} as const;
export type ExtractionStatus = ClosedEnum<typeof ExtractionStatus>;

export const ExtractionStatus$zodSchema = z.enum([
  "NOT_STARTED",
  "IN_PROGRESS",
  "COMPLETED",
  "FAILED",
]);

/**
 * Record-level summary surfaced under `searchResponse.records[]` and
 *
 * @remarks
 * `searchResponse.virtual_to_record_map`. Mirrors the row stored in the
 * records collection — strip down to the few fields you need
 * (`_key` / `recordName` / `mimeType` / `webUrl`).
 */
export type SearchRecordSummary = {
  _key?: string | undefined;
  _id?: string | undefined;
  _rev?: string | undefined;
  orgId?: string | undefined;
  recordName?: string | undefined;
  recordType?: string | undefined;
  externalRecordId?: string | undefined;
  externalRevisionId?: string | undefined;
  externalGroupId?: string | undefined;
  recordGroupId?: string | undefined;
  version?: number | undefined;
  origin?: SearchRecordSummaryOrigin | undefined;
  connectorName?: string | undefined;
  connectorId?: string | undefined;
  mimeType?: string | undefined;
  webUrl?: string | undefined;
  sizeInBytes?: number | undefined;
  md5Checksum?: string | undefined;
  indexingStatus?: IndexingStatus | undefined;
  extractionStatus?: ExtractionStatus | undefined;
  isDeleted?: boolean | undefined;
  isArchived?: boolean | undefined;
  isShared?: boolean | undefined;
  isInternal?: boolean | undefined;
  previewRenderable?: boolean | undefined;
  hideWeburl?: boolean | undefined;
  isVLMOcrProcessed?: boolean | undefined;
  isDirty?: boolean | undefined;
  isDependentNode?: boolean | undefined;
  virtualRecordId?: string | undefined;
  createdAtTimestamp?: number | undefined;
  updatedAtTimestamp?: number | undefined;
  sourceCreatedAtTimestamp?: number | undefined;
  sourceLastModifiedTimestamp?: number | undefined;
  lastIndexTimestamp?: number | undefined;
  lastExtractionTimestamp?: number | undefined;
};

export const SearchRecordSummary$zodSchema: z.ZodType<SearchRecordSummary> = z
  .object({
    _id: z.string().optional(),
    _key: z.string().optional(),
    _rev: z.string().optional(),
    connectorId: z.string().optional(),
    connectorName: z.string().optional(),
    createdAtTimestamp: z.int().optional(),
    externalGroupId: z.string().optional(),
    externalRecordId: z.string().optional(),
    externalRevisionId: z.string().optional(),
    extractionStatus: ExtractionStatus$zodSchema.optional(),
    hideWeburl: z.boolean().optional(),
    indexingStatus: IndexingStatus$zodSchema.optional(),
    isArchived: z.boolean().optional(),
    isDeleted: z.boolean().optional(),
    isDependentNode: z.boolean().optional(),
    isDirty: z.boolean().optional(),
    isInternal: z.boolean().optional(),
    isShared: z.boolean().optional(),
    isVLMOcrProcessed: z.boolean().optional(),
    lastExtractionTimestamp: z.int().optional(),
    lastIndexTimestamp: z.int().optional(),
    md5Checksum: z.string().optional(),
    mimeType: z.string().optional(),
    orgId: z.string().optional(),
    origin: SearchRecordSummaryOrigin$zodSchema.optional(),
    previewRenderable: z.boolean().optional(),
    recordGroupId: z.string().optional(),
    recordName: z.string().optional(),
    recordType: z.string().optional(),
    sizeInBytes: z.int().optional(),
    sourceCreatedAtTimestamp: z.int().optional(),
    sourceLastModifiedTimestamp: z.int().optional(),
    updatedAtTimestamp: z.int().optional(),
    version: z.int().optional(),
    virtualRecordId: z.string().optional(),
    webUrl: z.string().optional(),
  }).describe(
    "Record-level summary surfaced under `searchResponse.records[]` and\n`searchResponse.virtual_to_record_map`. Mirrors the row stored in the\nrecords collection — strip down to the few fields you need\n(`_key` / `recordName` / `mimeType` / `webUrl`).\n",
  );
