/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SearchHit, SearchHit$zodSchema } from "./searchhit.js";
import {
  SearchRecordSummary,
  SearchRecordSummary$zodSchema,
} from "./searchrecordsummary.js";

/**
 * The actual results body produced by the upstream search service.
 */
export type SearchResponsePayload = {
  searchResults: Array<SearchHit>;
  records: Array<SearchRecordSummary>;
  virtual_to_record_map?: { [k: string]: SearchRecordSummary } | undefined;
  status: string;
  status_code: number;
  message?: string | undefined;
};

export const SearchResponsePayload$zodSchema: z.ZodType<SearchResponsePayload> =
  z.object({
    message: z.string().optional(),
    records: z.array(SearchRecordSummary$zodSchema),
    searchResults: z.array(SearchHit$zodSchema),
    status: z.string(),
    status_code: z.int(),
    virtual_to_record_map: z.record(z.string(), SearchRecordSummary$zodSchema)
      .optional(),
  }).describe(
    "The actual results body produced by the upstream search service.",
  );
