/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Normalized bounding region for a chunk (when available).
 */
export type SemanticSearchBoundingBox = {
  x?: number | undefined;
  y?: number | undefined;
};

export const SemanticSearchBoundingBox$zodSchema: z.ZodType<
  SemanticSearchBoundingBox
> = z.object({
  x: z.number().optional(),
  y: z.number().optional(),
}).describe("Normalized bounding region for a chunk (when available).");
