/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Used for `available.sorting.{sortBy,sortOrder}` and
 *
 * @remarks
 * `available.sortingMessages.{sortBy,sortOrder}`. The `applied` flag
 * is present on `sorting.*` and absent on `sortingMessages.*`, so it
 * is optional here.
 */
export type SemanticSearchHistorySortField = {
  values: Array<string>;
  default: string;
  description: string;
  current: string;
  applied?: boolean | undefined;
};

export const SemanticSearchHistorySortField$zodSchema: z.ZodType<
  SemanticSearchHistorySortField
> = z.object({
  applied: z.boolean().optional(),
  current: z.string(),
  default: z.string(),
  description: z.string(),
  values: z.array(z.string()),
}).describe(
  "Used for `available.sorting.{sortBy,sortOrder}` and\n`available.sortingMessages.{sortBy,sortOrder}`. The `applied` flag\nis present on `sorting.*` and absent on `sortingMessages.*`, so it\nis optional here.\n",
);
