/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SemanticSearchHistoryDateRange,
  SemanticSearchHistoryDateRange$zodSchema,
} from "./semanticsearchhistorydaterange.js";
import {
  SemanticSearchHistoryFilterToggle,
  SemanticSearchHistoryFilterToggle$zodSchema,
} from "./semanticsearchhistoryfiltertoggle.js";
import {
  SemanticSearchHistoryPaginationField,
  SemanticSearchHistoryPaginationField$zodSchema,
} from "./semanticsearchhistorypaginationfield.js";
import {
  SemanticSearchHistorySortField,
  SemanticSearchHistorySortField$zodSchema,
} from "./semanticsearchhistorysortfield.js";

export type SemanticSearchHistoryFiltersAvailablePagination = {
  page: SemanticSearchHistoryPaginationField;
  limit: SemanticSearchHistoryPaginationField;
};

export const SemanticSearchHistoryFiltersAvailablePagination$zodSchema:
  z.ZodType<SemanticSearchHistoryFiltersAvailablePagination> = z.object({
    limit: SemanticSearchHistoryPaginationField$zodSchema,
    page: SemanticSearchHistoryPaginationField$zodSchema,
  });

export type Sorting = {
  sortBy: SemanticSearchHistorySortField;
  sortOrder: SemanticSearchHistorySortField;
};

export const Sorting$zodSchema: z.ZodType<Sorting> = z.object({
  sortBy: SemanticSearchHistorySortField$zodSchema,
  sortOrder: SemanticSearchHistorySortField$zodSchema,
});

export type DateFilters = { dateRange: SemanticSearchHistoryDateRange };

export const DateFilters$zodSchema: z.ZodType<DateFilters> = z.object({
  dateRange: SemanticSearchHistoryDateRange$zodSchema,
});

export type MessageFilters = { messageType: SemanticSearchHistoryFilterToggle };

export const MessageFilters$zodSchema: z.ZodType<MessageFilters> = z.object({
  messageType: SemanticSearchHistoryFilterToggle$zodSchema,
});

export type SortingMessages = {
  sortBy: SemanticSearchHistorySortField;
  sortOrder: SemanticSearchHistorySortField;
};

export const SortingMessages$zodSchema: z.ZodType<SortingMessages> = z.object({
  sortBy: SemanticSearchHistorySortField$zodSchema,
  sortOrder: SemanticSearchHistorySortField$zodSchema,
});

/**
 * Catalogue of filters the endpoint supports, plus their current values
 *
 * @remarks
 * and `applied` flags. Built by `buildFiltersMetadata` (utils.ts:430-624).
 */
export type SemanticSearchHistoryFiltersAvailable = {
  shared: SemanticSearchHistoryFilterToggle;
  tags: SemanticSearchHistoryFilterToggle;
  minMessages: SemanticSearchHistoryFilterToggle;
  search: SemanticSearchHistoryFilterToggle;
  pagination: SemanticSearchHistoryFiltersAvailablePagination;
  sorting: Sorting;
  dateFilters: DateFilters;
  messageFilters: MessageFilters;
  sortingMessages: SortingMessages;
};

export const SemanticSearchHistoryFiltersAvailable$zodSchema: z.ZodType<
  SemanticSearchHistoryFiltersAvailable
> = z.object({
  dateFilters: z.lazy(() => DateFilters$zodSchema),
  messageFilters: z.lazy(() => MessageFilters$zodSchema),
  minMessages: SemanticSearchHistoryFilterToggle$zodSchema,
  pagination: z.lazy(() =>
    SemanticSearchHistoryFiltersAvailablePagination$zodSchema
  ),
  search: SemanticSearchHistoryFilterToggle$zodSchema,
  shared: SemanticSearchHistoryFilterToggle$zodSchema,
  sorting: z.lazy(() => Sorting$zodSchema),
  sortingMessages: z.lazy(() => SortingMessages$zodSchema),
  tags: SemanticSearchHistoryFilterToggle$zodSchema,
}).describe(
  "Catalogue of filters the endpoint supports, plus their current values\nand `applied` flags. Built by `buildFiltersMetadata` (utils.ts:430-624).\n",
);
