/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Pagination block emitted by `buildPaginationMetadata` (utils.ts:417).
 *
 * @remarks
 * `totalPages` is `Math.ceil(totalCount / limit)`, so an empty result
 * has `totalPages: 0`, not `1`.
 */
export type SemanticSearchHistoryPagination = {
  page: number;
  limit: number;
  totalCount: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPrevPage: boolean;
};

export const SemanticSearchHistoryPagination$zodSchema: z.ZodType<
  SemanticSearchHistoryPagination
> = z.object({
  hasNextPage: z.boolean(),
  hasPrevPage: z.boolean(),
  limit: z.int(),
  page: z.int(),
  totalCount: z.int(),
  totalPages: z.int(),
}).describe(
  "Pagination block emitted by `buildPaginationMetadata` (utils.ts:417).\n`totalPages` is `Math.ceil(totalCount / limit)`, so an empty result\nhas `totalPages: 0`, not `1`.\n",
);
