/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request payload
 */
export type SetAtlassianOauthConfigRequest = {};

export const SetAtlassianOauthConfigRequest$zodSchema: z.ZodType<
  SetAtlassianOauthConfigRequest
> = z.object({}).describe("Request payload");

/**
 * Atlassian config saved
 */
export type SetAtlassianOauthConfigResponse = { message?: string | undefined };

export const SetAtlassianOauthConfigResponse$zodSchema: z.ZodType<
  SetAtlassianOauthConfigResponse
> = z.object({
  message: z.string().optional(),
}).describe("Atlassian config saved");
