/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request payload
 */
export type SetGoogleWorkspaceOauthConfigRequest = {};

export const SetGoogleWorkspaceOauthConfigRequest$zodSchema: z.ZodType<
  SetGoogleWorkspaceOauthConfigRequest
> = z.object({}).describe("Request payload");

/**
 * Google Workspace OAuth config saved
 */
export type SetGoogleWorkspaceOauthConfigResponse = {
  message?: string | undefined;
};

export const SetGoogleWorkspaceOauthConfigResponse$zodSchema: z.ZodType<
  SetGoogleWorkspaceOauthConfigResponse
> = z.object({
  message: z.string().optional(),
}).describe("Google Workspace OAuth config saved");
