/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request payload
 */
export type SetOneDriveCredentialsRequest = {};

export const SetOneDriveCredentialsRequest$zodSchema: z.ZodType<
  SetOneDriveCredentialsRequest
> = z.object({}).describe("Request payload");

/**
 * OneDrive credentials saved
 */
export type SetOneDriveCredentialsResponse = { message?: string | undefined };

export const SetOneDriveCredentialsResponse$zodSchema: z.ZodType<
  SetOneDriveCredentialsResponse
> = z.object({
  message: z.string().optional(),
}).describe("OneDrive credentials saved");
