/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ShareRequest, ShareRequest$zodSchema } from "./sharerequest.js";

export type ShareConversationRequest = {
  conversationId: string;
  body: ShareRequest;
};

export const ShareConversationRequest$zodSchema: z.ZodType<
  ShareConversationRequest
> = z.object({
  body: ShareRequest$zodSchema,
  conversationId: z.string(),
});
