/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApplicationJsonErrorResponse,
  ApplicationJsonErrorResponse$zodSchema,
} from "./applicationjsonerrorresponse.js";
import {
  OAuthClientManagementRateLimitError,
  OAuthClientManagementRateLimitError$zodSchema,
} from "./oauthclientmanagementratelimiterror.js";
import {
  SuspendOAuthAppResponse,
  SuspendOAuthAppResponse$zodSchema,
} from "./suspendoauthappresponse.js";

export type SuspendOAuthAppRequest = { appId: string };

export const SuspendOAuthAppRequest$zodSchema: z.ZodType<
  SuspendOAuthAppRequest
> = z.object({
  appId: z.string().describe("OAuth app ID"),
});

export type SuspendOAuthAppResponseResponse =
  | SuspendOAuthAppResponse
  | ApplicationJsonErrorResponse
  | OAuthClientManagementRateLimitError;

export const SuspendOAuthAppResponseResponse$zodSchema: z.ZodType<
  SuspendOAuthAppResponseResponse
> = z.union([
  SuspendOAuthAppResponse$zodSchema,
  ApplicationJsonErrorResponse$zodSchema,
  OAuthClientManagementRateLimitError$zodSchema,
]);
