/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TeamMemberSummaryRole = {
  Owner: "OWNER",
  Admin: "ADMIN",
  Writer: "WRITER",
  Reader: "READER",
} as const;
export type TeamMemberSummaryRole = ClosedEnum<typeof TeamMemberSummaryRole>;

export const TeamMemberSummaryRole$zodSchema = z.enum([
  "OWNER",
  "ADMIN",
  "WRITER",
  "READER",
]);

/**
 * Compact membership row embedded in `GET /teams/user/teams`. Joins
 *
 * @remarks
 * the user node, the user document, and the membership edge into a
 * single flat object suitable for rendering a team member list.
 */
export type TeamMemberSummary = {
  id?: string | undefined;
  userId?: string | undefined;
  userName?: string | undefined;
  userEmail?: string | undefined;
  role?: TeamMemberSummaryRole | undefined;
  joinedAt?: number | undefined;
  isOwner?: boolean | undefined;
};

export const TeamMemberSummary$zodSchema: z.ZodType<TeamMemberSummary> = z
  .object({
    id: z.string().optional(),
    isOwner: z.boolean().optional(),
    joinedAt: z.int().optional(),
    role: TeamMemberSummaryRole$zodSchema.optional(),
    userEmail: z.string().optional(),
    userId: z.string().optional(),
    userName: z.string().optional(),
  }).describe(
    "Compact membership row embedded in `GET /teams/user/teams`. Joins\nthe user node, the user document, and the membership edge into a\nsingle flat object suitable for rendering a team member list.\n",
  );
