/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApplicationJsonErrorResponse,
  ApplicationJsonErrorResponse$zodSchema,
} from "./applicationjsonerrorresponse.js";
import {
  OAuthClientManagementRateLimitError,
  OAuthClientManagementRateLimitError$zodSchema,
} from "./oauthclientmanagementratelimiterror.js";
import {
  UpdateOAuthAppRequest,
  UpdateOAuthAppRequest$zodSchema,
} from "./updateoauthapprequest.js";
import {
  UpdateOAuthAppResponse,
  UpdateOAuthAppResponse$zodSchema,
} from "./updateoauthappresponse.js";

export type UpdateOAuthAppRequestRequest = {
  appId: string;
  body: UpdateOAuthAppRequest;
};

export const UpdateOAuthAppRequestRequest$zodSchema: z.ZodType<
  UpdateOAuthAppRequestRequest
> = z.object({
  appId: z.string().describe("OAuth app ID"),
  body: UpdateOAuthAppRequest$zodSchema,
});

export type UpdateOAuthAppResponseResponse =
  | UpdateOAuthAppResponse
  | ApplicationJsonErrorResponse
  | OAuthClientManagementRateLimitError;

export const UpdateOAuthAppResponseResponse$zodSchema: z.ZodType<
  UpdateOAuthAppResponseResponse
> = z.union([
  UpdateOAuthAppResponse$zodSchema,
  ApplicationJsonErrorResponse$zodSchema,
  OAuthClientManagementRateLimitError$zodSchema,
]);
