/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthStep, AuthStep$zodSchema } from "./authstep.js";

/**
 * Response after updating organization authentication methods
 */
export type UpdateAuthMethodResponse = {
  message: string;
  authMethod: Array<AuthStep>;
};

export const UpdateAuthMethodResponse$zodSchema: z.ZodType<
  UpdateAuthMethodResponse
> = z.object({
  authMethod: z.array(AuthStep$zodSchema),
  message: z.string(),
}).describe("Response after updating organization authentication methods");
