/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { User, User$zodSchema } from "./user.js";

/**
 * Request payload
 */
export type UpdateUserDesignationRequestBody = { designation: string };

export const UpdateUserDesignationRequestBody$zodSchema: z.ZodType<
  UpdateUserDesignationRequestBody
> = z.object({
  designation: z.string(),
}).describe("Request payload");

export type UpdateUserDesignationRequest = {
  id: string;
  body: UpdateUserDesignationRequestBody;
};

export const UpdateUserDesignationRequest$zodSchema: z.ZodType<
  UpdateUserDesignationRequest
> = z.object({
  body: z.lazy(() => UpdateUserDesignationRequestBody$zodSchema),
  id: z.string().describe("User ID (24-character MongoDB ObjectId)"),
});

/**
 * Designation updated successfully
 */
export type UpdateUserDesignationResponse = {
  success?: boolean | undefined;
  data?: User | undefined;
};

export const UpdateUserDesignationResponse$zodSchema: z.ZodType<
  UpdateUserDesignationResponse
> = z.object({
  data: User$zodSchema.optional(),
  success: z.boolean().optional(),
}).describe("Designation updated successfully");
