/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Address, Address$zodSchema } from "./address.js";
import { Organization, Organization$zodSchema } from "./organization.js";

/**
 * Request payload
 */
export type UpdateOrganizationRequest = {
  registeredName?: string | undefined;
  shortName?: string | undefined;
  phoneNumber?: string | undefined;
  permanentAddress?: Address | undefined;
};

export const UpdateOrganizationRequest$zodSchema: z.ZodType<
  UpdateOrganizationRequest
> = z.object({
  permanentAddress: Address$zodSchema.optional(),
  phoneNumber: z.string().optional(),
  registeredName: z.string().optional(),
  shortName: z.string().optional(),
}).describe("Request payload");

/**
 * Organization updated successfully
 */
export type UpdateOrganizationResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  data?: Organization | undefined;
};

export const UpdateOrganizationResponse$zodSchema: z.ZodType<
  UpdateOrganizationResponse
> = z.object({
  data: Organization$zodSchema.optional(),
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Organization updated successfully");
