/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Request payload
 */
export type UpdateKnowledgeBaseRequestBody = { kbName?: string | undefined };

export const UpdateKnowledgeBaseRequestBody$zodSchema: z.ZodType<
  UpdateKnowledgeBaseRequestBody
> = z.object({
  kbName: z.string().optional(),
}).describe("Request payload");

export type UpdateKnowledgeBaseRequest = {
  kbId: string;
  body: UpdateKnowledgeBaseRequestBody;
};

export const UpdateKnowledgeBaseRequest$zodSchema: z.ZodType<
  UpdateKnowledgeBaseRequest
> = z.object({
  body: z.lazy(() => UpdateKnowledgeBaseRequestBody$zodSchema),
  kbId: z.string().describe("Knowledge base ID"),
});
