/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AgentUpdateRequest,
  AgentUpdateRequest$zodSchema,
} from "./agentupdaterequest.js";
import {
  AgentUpdateResponse,
  AgentUpdateResponse$zodSchema,
} from "./agentupdateresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type UpdateAgentRequest = { agentKey: string; body: AgentUpdateRequest };

export const UpdateAgentRequest$zodSchema: z.ZodType<UpdateAgentRequest> = z
  .object({
    agentKey: z.string().describe("Unique agent identifier"),
    body: AgentUpdateRequest$zodSchema,
  });

export type UpdateAgentResponse = AgentUpdateResponse | ErrorResponse;

export const UpdateAgentResponse$zodSchema: z.ZodType<UpdateAgentResponse> = z
  .union([
    AgentUpdateResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
