/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";

export type UploadDocumentFile = {
  fileName: string;
  content: Uint8Array | string;
};

export const UploadDocumentFile$zodSchema: z.ZodType<UploadDocumentFile> = z
  .object({
    content: z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    fileName: z.string(),
  });

export type UploadDocumentRequest = {
  file?: UploadDocumentFile | Blob | undefined;
};

export const UploadDocumentRequest$zodSchema: z.ZodType<UploadDocumentRequest> =
  z.object({
    file: z.lazy(() => UploadDocumentFile$zodSchema).optional(),
  });

/**
 * Document uploaded successfully
 */
export type UploadDocumentResponse = { message?: string | undefined };

export const UploadDocumentResponse$zodSchema: z.ZodType<
  UploadDocumentResponse
> = z.object({
  message: z.string().optional(),
}).describe("Document uploaded successfully");
