/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";

export type UploadNextVersionDocumentFile = {
  fileName: string;
  content: Uint8Array | string;
};

export const UploadNextVersionDocumentFile$zodSchema: z.ZodType<
  UploadNextVersionDocumentFile
> = z.object({
  content: z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  fileName: z.string(),
});

export type UploadNextVersionDocumentRequestBody = {
  file?: UploadNextVersionDocumentFile | Blob | undefined;
};

export const UploadNextVersionDocumentRequestBody$zodSchema: z.ZodType<
  UploadNextVersionDocumentRequestBody
> = z.object({
  file: z.lazy(() => UploadNextVersionDocumentFile$zodSchema).optional(),
});

export type UploadNextVersionDocumentRequest = {
  documentId: string;
  body: UploadNextVersionDocumentRequestBody;
};

export const UploadNextVersionDocumentRequest$zodSchema: z.ZodType<
  UploadNextVersionDocumentRequest
> = z.object({
  body: z.lazy(() => UploadNextVersionDocumentRequestBody$zodSchema),
  documentId: z.string(),
});

/**
 * New version uploaded successfully
 */
export type UploadNextVersionDocumentResponse = {
  message?: string | undefined;
};

export const UploadNextVersionDocumentResponse$zodSchema: z.ZodType<
  UploadNextVersionDocumentResponse
> = z.object({
  message: z.string().optional(),
}).describe("New version uploaded successfully");
