/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TeamMemberSummary,
  TeamMemberSummary$zodSchema,
} from "./teammembersummary.js";
import {
  TeamPermissionEdge,
  TeamPermissionEdge$zodSchema,
} from "./teampermissionedge.js";

/**
 * Per-caller view of a team, as returned by `GET /teams/user/teams`.
 *
 * @remarks
 * Extends the canonical `Team` document with the caller's
 * `currentUserPermission` edge and capability flags
 * (`canEdit` / `canDelete` / `canManageMembers`) computed from that
 * permission.
 */
export type UserTeamMembership = {
  id: string;
  name: string;
  description?: string | null | undefined;
  createdBy?: string | undefined;
  orgId: string;
  memberCount?: number | undefined;
  members?: Array<TeamMemberSummary> | undefined;
  createdAtTimestamp?: number | undefined;
  updatedAtTimestamp?: number | undefined;
  currentUserPermission?: TeamPermissionEdge | undefined;
  canEdit?: boolean | undefined;
  canDelete?: boolean | undefined;
  canManageMembers?: boolean | undefined;
};

export const UserTeamMembership$zodSchema: z.ZodType<UserTeamMembership> = z
  .object({
    canDelete: z.boolean().optional(),
    canEdit: z.boolean().optional(),
    canManageMembers: z.boolean().optional(),
    createdAtTimestamp: z.int().optional(),
    createdBy: z.string().optional(),
    currentUserPermission: TeamPermissionEdge$zodSchema.optional(),
    description: z.string().nullable().optional(),
    id: z.string(),
    memberCount: z.int().optional(),
    members: z.array(TeamMemberSummary$zodSchema).optional(),
    name: z.string(),
    orgId: z.string(),
    updatedAtTimestamp: z.int().optional(),
  }).describe(
    "Per-caller view of a team, as returned by `GET /teams/user/teams`.\nExtends the canonical `Team` document with the caller's\n`currentUserPermission` edge and capability flags\n(`canEdit` / `canDelete` / `canManageMembers`) computed from that\npermission.\n",
  );
