/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PaginationInfo, PaginationInfo$zodSchema } from "./paginationinfo.js";
import {
  UserGroupListItem,
  UserGroupListItem$zodSchema,
} from "./usergrouplistitem.js";

/**
 * Paginated response from `GET /userGroups`.
 */
export type UserGroupListResponse = {
  groups: Array<UserGroupListItem>;
  pagination: PaginationInfo;
};

export const UserGroupListResponse$zodSchema: z.ZodType<UserGroupListResponse> =
  z.object({
    groups: z.array(UserGroupListItem$zodSchema),
    pagination: PaginationInfo$zodSchema,
  }).describe("Paginated response from `GET /userGroups`.");
