/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Supported web search provider
 */
export const WebSearchProviderType = {
  Duckduckgo: "duckduckgo",
  Serper: "serper",
  Tavily: "tavily",
  Exa: "exa",
} as const;
/**
 * Supported web search provider
 */
export type WebSearchProviderType = ClosedEnum<typeof WebSearchProviderType>;

export const WebSearchProviderType$zodSchema = z.enum([
  "duckduckgo",
  "serper",
  "tavily",
  "exa",
]).describe("Supported web search provider");
