/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Normalized web search global settings returned by getWebSearchProviders
 */
export type WebSearchSettings = {
  includeImages: boolean;
  maxImages?: number | undefined;
};

export const WebSearchSettings$zodSchema: z.ZodType<WebSearchSettings> = z
  .object({
    includeImages: z.boolean(),
    maxImages: z.int().optional(),
  }).describe(
    "Normalized web search global settings returned by getWebSearchProviders",
  );
